### ISSUE TITLE
UI of footer section need to be improved

### ISSUE THREAD

**Issue by khushi-joshi-05** [arghadipmanna101/Flipkart_Clone#1]
This clone's  footer do not have a good UI , kindly assign this issue to me.

**Comment by CharanAdithya6505** [comment]
could you please assign it to me i will make the footer section more visually appealing

**Comment by vaishnavip27** [comment]
Hey! I would really like to work on this issue. As I have already built amazon, Flipkart and x-clone before. Can you please assign it to me? Looking forward for the approval

**Comment by arghadipmanna101** [comment]
@CharanAdithya6505 you have been assigned. Go ahead...

**Comment by CharanAdithya6505** [comment]
Thank you, i will do it

**Comment by arghadipmanna101** [comment]
> Thank you, i will do it

Do it fast. Thanks for your consideration.

**Comment by CharanAdithya6505** [comment]
ok sir

**Comment by akshita-86** [comment]
I would like to work on this issue. Please assign me this issue!

**Comment by Kish-an-gupta** [comment]
I would like to work on this issue. Please assign me this issue!
