### ISSUE TITLE
Design of the website

### ISSUE THREAD

**Issue by mousumideyy** [arghadipmanna101/Flipkart_Clone#100]
I would like to add live Chat Support, this will offer real-time chat support to assist users with queries, product recommendations, and order assistance, improving customer satisfaction and loyalty. 
And also improved User Reviews, enhancing the user review system by allowing photo and video reviews, fostering trust and authenticity among shoppers

Please assign me under @GSSoC

**Comment by arghadipmanna101** [comment]
sure. go ahead @mousumideyy
