### ISSUE TITLE
DOC: Adding Css to the Show items button

### ISSUE THREAD

**Issue by TAnisha016** [arghadipmanna101/Flipkart_Clone#1011]
### What's wrong with the existing documentation

The button's are made just using html, We can add CSS to improve the look and feel of the section and overall website.

### File to change

![Gssoc issue_flipkart](https://github.com/arghadipmanna101/Flipkart_Clone/assets/144906120/430cb6c3-bcc0-42bb-bca8-31bf4598bfc6)

### Details of the change

We can change the border, colour, add some padding , font of the text , allign it properly etc.

### Type of change
Improvement in style of button using CSS

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by TAnisha016** [comment]
@arghadipmanna101 I would love to work on this website and contribute my knowledge, I request you to please assign me this issue under GSSOC'24

**Comment by rohir1132yadav** [comment]
i want to work on this project .please assign me

**Comment by TAnisha016** [comment]
Thank you so much for assigning me these issues..I'll surely fix them in a
2-3 days.
