### ISSUE TITLE
BUG: images are not loading properly

### ISSUE THREAD

**Issue by dnyandeepchute** [arghadipmanna101/Flipkart_Clone#1023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

images are not loaded in the deals section

### What happened?

images not loaded

### Expected behavior

images should be loaded 

### Screenshots

![Screenshot 2024-06-04 201633](https://github.com/arghadipmanna101/Flipkart_Clone/assets/158272735/1ae72b21-27aa-4216-93ca-6d12beb172f0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by dnyandeepchute** [comment]
hey @arghadipmanna101, please assign this to me, thank you.

**Comment by dnyandeepchute** [comment]
@arghadipmanna101 please add the level, gssoc and other labels.

**Comment by arghadipmanna101** [comment]
After reviewing your PR, i will add levels. ok.
