### ISSUE TITLE
BUG: logo is not loaded and dark mode symbol is not properly adjusted

### ISSUE THREAD

**Issue by dnyandeepchute** [arghadipmanna101/Flipkart_Clone#1024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

logo is not loaded and dark mode symbol is not properly adjusted

### What happened?

logo can not be seen and dark mode symbol is going out of nav bar.

### Expected behavior

logo should be seen properly and dark mode symbol should be nab bar

### Screenshots

![Screenshot 2024-06-04 202234](https://github.com/arghadipmanna101/Flipkart_Clone/assets/158272735/3e4a7f8c-42b2-443d-ba12-d293dbdc2eec)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by dnyandeepchute** [comment]
hey @arghadipmanna101 , please assign this to me, thank you.

**Comment by 143divya** [comment]
Can you please assign me this issue for gssoc'24

**Comment by dnyandeepchute** [comment]
@arghadipmanna101 please add the level, gssoc and other labels.

**Comment by arghadipmanna101** [comment]
After reviewing your PR, i will add levels. ok.
