### ISSUE TITLE
update nav bar

### ISSUE THREAD

**Issue by dnyandeepchute** [arghadipmanna101/Flipkart_Clone#1025]
### Describe the feature

nav bar is not up to the mark

### Describe the solution you'd like

making more attractive by adding proper spacing, margin, border and padding.

### Describe alternatives you've considered

using CSS in better way

### Add ScreenShots

![Screenshot 2024-06-04 202234](https://github.com/arghadipmanna101/Flipkart_Clone/assets/158272735/b353cbd7-1ab2-4d1c-b1b4-bb818b85bf4a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by dnyandeepchute** [comment]
hey @arghadipmanna101 , please assign this to me, thank you.

**Comment by Sajiyasiddiqui** [comment]
I want to work on this project please assign me.

**Comment by dnyandeepchute** [comment]
@arghadipmanna101 please add the level, gssoc and other labels.

**Comment by arghadipmanna101** [comment]
After reviewing your PR, i will add levels. ok.

**Comment by honey7733** [comment]
I would like to work on this. Please assign it to me.
