### ISSUE TITLE
update footer

### ISSUE THREAD

**Issue by dnyandeepchute** [arghadipmanna101/Flipkart_Clone#1026]
### Describe the feature

want to add change on hover, proper spacing, margin, border and social media icons with proper size

### Describe the solution you'd like

adding change on hover, proper spacing, margin, border and social media icons with proper size for great look

### Describe alternatives you've considered

using CSS in proper way for better result.

### Add ScreenShots

![Screenshot 2024-06-04 203659](https://github.com/arghadipmanna101/Flipkart_Clone/assets/158272735/ac6aba4b-d84d-46ef-b2a2-37016126913d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Silentman87** [comment]
please assign me this issue i can fix it @arghadipmanna101

**Comment by dnyandeepchute** [comment]
@arghadipmanna101 please add the level, gssoc and other labels.

**Comment by arghadipmanna101** [comment]
After reviewing your PR, i will add levels. ok.
