### ISSUE TITLE
reconstruct/update full design of web site

### ISSUE THREAD

**Issue by dnyandeepchute** [arghadipmanna101/Flipkart_Clone#1027]
### Describe the feature

want to reconstruct/update full design of web site by properly adjusting all the images and different section.

### Describe the solution you'd like

full design of web site by properly adjusting all the images and different section.

### Describe alternatives you've considered

using proper CSS for design.

### Add ScreenShots

![Screenshot 2024-06-04 203909](https://github.com/arghadipmanna101/Flipkart_Clone/assets/158272735/7d65af68-17fb-4385-8ea1-430775158d1f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by dnyandeepchute** [comment]
@arghadipmanna101 please add the level, gssoc and other labels.

**Comment by arghadipmanna101** [comment]
After reviewing your PR, i will add levels. ok.
