### ISSUE TITLE
[Feature] : Login & Sign Up form

### ISSUE THREAD

**Issue by sivaprasath2004** [arghadipmanna101/Flipkart_Clone#1046]
### Describe the feature

- In this project Not available on the `Login` & `Sign Up` form.

### Describe the solution you'd like

- So i will implement the `Login` & `Sign Up` page ..
- It very more important of the user Details and product ordering.
- In this Feaute Implementation this issue can be more improve the project.

### Describe alternatives you've considered

- please assign me ..
- i will ready to work on it..

### Add ScreenShots

![Screenshot from 2024-06-05 21-44-54](https://github.com/arghadipmanna101/Flipkart_Clone/assets/121082414/4f672ad1-2081-4d18-9cd2-86593ed8ea64)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Iamkiranpanigrahi** [comment]
consider me for this task.
