### ISSUE TITLE
Feat: Add Quantity Button

### ISSUE THREAD

**Issue by SrinivasDevolper** [arghadipmanna101/Flipkart_Clone#1050]
### Describe the feature

When a user wants more than one product, we need to add a quantity button that gives users a convenient real-time experience.

**I am GSSOC24 Contributor
please assign me< I would like to work on it**

### Describe the solution you'd like

Add Quantity Button.

### Describe alternatives you've considered

Add Quantity Button.

### Add ScreenShots

![quantity button](https://github.com/arghadipmanna101/Flipkart_Clone/assets/121508628/0271270c-f8cf-4d56-baf5-d00de122cee3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by tomartanu** [comment]
I want to contribute in this issue, please assign it to me
