### ISSUE TITLE
Things which can be improved

### ISSUE THREAD

**Issue by swarajjaiswal** [arghadipmanna101/Flipkart_Clone#106]
~Enhance Navbar UI for better aesthetics and user experience.
~Improve Footer design to make it more visually appealing and informative.
~Incorporate various types of cards to display items, providing a visually engaging way to showcase content.
~Implement additional functionalities to buttons for enhanced user interaction and functionality.

**Comment by sys-atasi** [comment]
please assign me these tasks

**Comment by swarajjaiswal** [comment]
> please assign me these tasks

i have raised the issue hope so if it gets assigned,it is done to me

**Comment by SohaFarhana** [comment]
Hello
I am a GSSoC'24 contributor and looking forward to work on this

**Comment by arghadipmanna101** [comment]
Go ahead @swarajjaiswal
