### ISSUE TITLE
Aligning the contents of the page in the centre

### ISSUE THREAD

**Issue by PrithwikaDas** [arghadipmanna101/Flipkart_Clone#107]
I want to fix this issue.Please assign this to me under GSSOC 2024.

**Comment by sys-atasi** [comment]
I want to fix this issue.Please assign this to me.

**Comment by PDurgaAnusha** [comment]
I want to fix this issue.Please assign this to me. #gssoc

**Comment by Ashutosh-0506** [comment]
Hey there! I'm Ashutosh Kumar, a full-stack MERN web developer. With experience in numerous successful MERN stack  projects, I excel in  HTML, CSS,JavaScript,C, C++,jQuery, Node.js, React.js, Bootstrap, Tailwind, Express, MongoDB, API,GraphQL,WebRTC. 
You can find me on LinkedIn : https://www.linkedin.com/in/ashutosh-kumar-60b262251/ 
 GitHub : https://github.com/Ashutosh-0506. 
Looking forward to contributing to GSSOC 2024!

**Comment by yash21sriv** [comment]
Hey please assign me this I want fix this issue

**Comment by HarshSDE0** [comment]
Hey there! I'm Harsh Abhishek  MERN web developer. With experience in numerous successful MERN stack projects, I excel in HTML, CSS,JavaScript,java.
LinkedIn profile: https://www.linkedin.com/in/harsh-abhishek-463359222/

**Comment by arghadipmanna101** [comment]
Go ahead guys...

**Comment by anushreemehta6** [comment]
i think i can also contribute here , please assign me this task under GSSOC'24

**Comment by AbhinayBhadauria99** [comment]
I want to fix this issue.Please assign this to me.

**Comment by PrithwikaDas** [comment]
> Go ahead guys...

Already fixed this issue and created a PR @arghadipmanna101

**Comment by Aditya19110** [comment]
Please assign me the issue so i can work on it

**Comment by solanki505** [comment]
I want to work on this issue please assign me this under GSSOC'24

**Comment by LordVaibhav** [comment]
I want to work on this issue. Please assign this to me under GSSoC'24.

**Comment by Suruchibharti** [comment]
hii! ,
I'm GSSoC'24 contributor , I have experienced on HTML, CSS, JS, and react.js , so I want to work on this issue,
so, kindly requested to you to assign me the task.
