### ISSUE TITLE
BUG: Update Navbar Background Color and Size

### ISSUE THREAD

**Issue by Muskan2025** [arghadipmanna101/Flipkart_Clone#1071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We need to update the navbar to ensure a consistent look and feel across all webpages. This includes changing the background color to match the navbar on other pages and decreasing its size for better visual alignment.web pages

### What happened?

Requirements:

**Background Color:**

Change the navbar's background color to match the navbar color used on other webpages of the project. Ensure the color code matches exactly to maintain consistency.

**Navbar Size:**

Decrease the height of the navbar to match the size used on other pages. The new height should be consistent with the design guidelines provided or existing navbar dimensions on other pages.

### Expected behavior

Follow the existing color scheme of the project.
Ensure the navbar's text and icons remain clearly visible and accessible against the new background color.
Ensure the navbar's size adjustment does not impact the usability or readability of the navigation items.

### Screenshots

**The navbar to be changed.**
![navbar](https://github.com/arghadipmanna101/Flipkart_Clone/assets/104768631/9a3a8260-3109-4a1b-9104-ec8e52b9f6c0)

**Navbar which is indifferent.**
![error navbar](https://github.com/arghadipmanna101/Flipkart_Clone/assets/104768631/9f7844ee-69e8-4aa4-9c2a-953bb1443017)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sweta-66** [comment]
please assign the issue
