### ISSUE TITLE
Feat: Add hover to wishlist

### ISSUE THREAD

**Issue by MuraliDharan7** [arghadipmanna101/Flipkart_Clone#1086]
### Describe the feature

I want to add hover to wishlist

### Describe the solution you'd like

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/130668745/a934908f-95dc-4bb7-be0e-f487dca96430)

I want to add hover

### Describe alternatives you've considered

It will give the user more experience while using this website

### Add ScreenShots

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/130668745/f7e7a78c-315b-4040-be86-ff8801286637)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sakeel-103** [comment]
@arghadipmanna101 
Please assign me this task under gssoc'24 I will fix this .
