### ISSUE TITLE
Feat: Add Contact us

### ISSUE THREAD

**Issue by MadMax1311** [arghadipmanna101/Flipkart_Clone#1092]
### Describe the feature

Add the Contact Us page.

### Describe the solution you'd like

Adding a Contact Us page is helpful for customers.

### Describe alternatives you've considered

N/A

### Add ScreenShots

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/140179838/d598a3e4-39fb-4da7-ab45-9486cf2a8698)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PAPIYA-DUTTA** [comment]
please assign me I want to work on it.
