### ISSUE TITLE
BUG: Correcting the sell online page 

### ISSUE THREAD

**Issue by Bhavishya2601** [arghadipmanna101/Flipkart_Clone#1113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The sell online page does not have proper alignment and i would like to correct it

### Screenshots

![Screenshot 2024-06-08 141638](https://github.com/arghadipmanna101/Flipkart_Clone/assets/147748752/40c59087-a460-4c79-99da-dde90cb4118e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Gsha36** [comment]
Hi, I can solve this issue. Can you assign it to me?
Record

- [ *] I agree to follow this project's Code of Conduct
- [* ]  I'm a GSSOC'24 contributor
- [* ]  I want to work on this issue

**Comment by electrify-7** [comment]
@Bhavishya2601 There is already someone working on this, please check properly before marking 
[*] I have searched the existing issues
