### ISSUE TITLE
BUG:"Login Button Not Working in Navbar When Accessing Cart Without Logging In"

### ISSUE THREAD

**Issue by savvymonk05** [arghadipmanna101/Flipkart_Clone#1118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The login button in the navbar is not functioning when a user who is not logged in attempts to access the cart. This issue prevents users from logging in directly from the cart page, disrupting the user experience.

### What happened?

when i am trying to accessing the cart from index page without logging  it is showing a login button which is not working 

### Expected behavior

the login button should work in cart section of home page 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by savvymonk05** [comment]
@arghadipmanna101 please assign this issue to me

**Comment by sakeel-103** [comment]
@arghadipmanna101 
Please assign me this task under gssoc'24, I'll fix this issue.
