### ISSUE TITLE
Fix the navigation bar in Profile > Signup page.

### ISSUE THREAD

**Issue by justmirr** [arghadipmanna101/Flipkart_Clone#112]
I'm a freelance web developer and saw this issue so I'm willing to make changes - Adding responsiveness to the Signup page and fixing the visual issues in the same. So, please assign this to me.

**Comment by justmirr** [comment]
![Screenshot (2)](https://github.com/arghadipmanna101/Flipkart_Clone/assets/75358919/61981c20-0fa1-4cb7-8a63-94bf7a304759)

**Comment by Amrit-Raj-17** [comment]
Can you add as a contributor for this. I am very enthusiastic for this website

**Comment by Anshydv18** [comment]
i can do it in a better way than others, please assign me this project

**Comment by Anou25** [comment]
Hi, I would like to work on this issue, please can you assign this to me.

**Comment by Amrit-Raj-17** [comment]
Sure, I'll get started on it as soon as possible.
Thank you for this opportunity.

**Comment by DivyaCodingWorld** [comment]
Hii, 
I'm Divyani , I'm interested to work on this issues. Can u assign it to me on this project.
