### ISSUE TITLE
Grammatical mistakes in README.md

### ISSUE THREAD

**Issue by rajatya713** [arghadipmanna101/Flipkart_Clone#113]
There are some sentences in the readme.md which does give inconsistent meaning to the user.
Assign the issue to me to fix this under GSSOC'24.

**Comment by yashika0432** [comment]
I would like to contribute to the issue of this grammatical mistakes I am a contributor at GGSOC'24

**Comment by Pooja-c03** [comment]
I would love to correct the small mistakes and make it worth reading.

**Comment by SohaFarhana** [comment]
Hello
I am a GSSoC'24 contributor and looking forward to work on this

**Comment by Divya-1612-reddy** [comment]
hello, I would like to correct this issue. Please assign me this

**Comment by Khushinkm15** [comment]
Hey I would like to correct this issue. Please assign it to me

**Comment by Aryan01903** [comment]
I would like to correct this issue . Please assign it to me. My linkedin id is https://www.linkedin.com/in/aryan-kumar-shrivastav-638831268/

**Comment by creativeadi** [comment]
I would like to correct this issue, kindly assign this to me

**Comment by arghadipmanna101** [comment]
Go ahead @rajatya713
