### ISSUE TITLE
DOC: Auto Display Of Product details with image  frequently When users view of The Products!!

### ISSUE THREAD

**Issue by USERASHOKG** [arghadipmanna101/Flipkart_Clone#1134]
### What's wrong with the existing documentation

![AutoDispay](https://github.com/arghadipmanna101/Flipkart_Clone/assets/110445888/2be32b46-773c-4346-96d7-53419509985b)

### File to change

ProductDetails.js
index.html

### Details of the change

Display Frequently Bought Together Item!!
![AutoDispay](https://github.com/arghadipmanna101/Flipkart_Clone/assets/110445888/65857a1b-7d26-430d-b16e-b04cf861b600)

### Type of change

Adding new Sections  With Product Components.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by itsyourgirlgargi** [comment]
I'd like to work on this project, please assign it to me.
