### ISSUE TITLE
Feat: adding instagram

### ISSUE THREAD

**Issue by dnyandeepchute** [arghadipmanna101/Flipkart_Clone#1135]
### Describe the feature

adding instagram to social section

### Describe the solution you'd like

adding instagram to social section

### Describe alternatives you've considered

adding instagram to social section

### Add ScreenShots

![Screenshot 2024-06-09 100459](https://github.com/arghadipmanna101/Flipkart_Clone/assets/158272735/873a18fd-ecc6-4f13-abd2-e01130d9d155)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by dnyandeepchute** [comment]
please assign this to me.

**Comment by riddhimagoyal3** [comment]
Please assign this to me.
