### ISSUE TITLE
Feat: Add a remove item button .

### ISSUE THREAD

**Issue by arghadipmanna101** [arghadipmanna101/Flipkart_Clone#1165]
### Describe the feature

Add a button to remove the added item.

### Describe the solution you'd like

create a remove button.

### Describe alternatives you've considered

add a button

### Add ScreenShots

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/130065095/644eeae3-de73-45c5-90e4-d6d4ac3395aa)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by purvathnere** [comment]
assign me

**Comment by anvithagowda098** [comment]
I agree to follow code of conduct. I am a GSSoC'24 contributor proficient in HTML, CSS and JS. I'd like to work on this issue. Please assign this to me.

**Comment by khush1106** [comment]
i agree to follow the code of conduct and i am a a GSSOC'24 contributor getting my hands on html css and java scrpipt i would be highly obliged if you could assign me this issue
