### ISSUE TITLE
Feat:Add Hover effects on footer's social icons.

### ISSUE THREAD

**Issue by zalabhavy** [arghadipmanna101/Flipkart_Clone#1172]
### Describe the feature

I will add css to make more attractive social icons.

### Describe the solution you'd like

I will add hove effects , transitions ect.

### Describe alternatives you've considered

No alternatives. It must be include in website.

### Add ScreenShots

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/126322584/a9eac735-3d86-4272-b138-dc50abfb8408)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@arghadipmanna101 Please assign me !

**Comment by Tanishka023** [comment]
Hey @Harshil-Jani Please assign this to me under GSSoC'24, I can fix this easily as I have already worked on this.
