### ISSUE TITLE
drop down effect is not there in appliances and mobile section 

### ISSUE THREAD

**Issue by PrabhjotBajwa** [arghadipmanna101/Flipkart_Clone#1173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

@arghadipmanna101 plz assign this issue to me under gssoc24 label

### Screenshots

![sections](https://github.com/arghadipmanna101/Flipkart_Clone/assets/148677213/ae100b43-04d6-47d8-918f-4ed7fc8cff94)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by csathnere** [comment]
It's not even on the original flipkart
