### ISSUE TITLE
Feat: Responsive site

### ISSUE THREAD

**Issue by Vibha17** [arghadipmanna101/Flipkart_Clone#1176]
### Describe the feature

I would like to make site more responsive and improve ui

I am Vibha Gupta and I would like to fix the issue.

I am working under GSSoC'24. Please assign me this issue.

### Describe the solution you'd like

I will use css like media query 

### Describe alternatives you've considered

use flexbox

### Add ScreenShots

![Screenshot 2024-06-12 223816](https://github.com/arghadipmanna101/Flipkart_Clone/assets/152614708/92cf5121-c08a-4b35-b8a0-c791e0554b1e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by 143divya** [comment]
Can you please assign this issue to under gssoc24? I want to work on this.
