### ISSUE TITLE
Feat: Add a back button on pages

### ISSUE THREAD

**Issue by shruti110503** [arghadipmanna101/Flipkart_Clone#1177]
### Describe the feature

There is no button for going back on the pages like mobiles, appliances, cart, men etc

### Describe the solution you'd like

I want to add a working back button on these pages.

### Describe alternatives you've considered

There should be a functional back button.

### Add ScreenShots

![Screenshot 2024-06-13 014209](https://github.com/arghadipmanna101/Flipkart_Clone/assets/118251562/016c40ad-3c4b-42cb-b6a4-760840341fee)
It would look something like this after the button is added.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by iakshkhurana** [comment]
I would like to work on this. Please assign me this issue to contribute to this project
