### ISSUE TITLE
Feat: Resizing the nav bar

### ISSUE THREAD

**Issue by AryanAwtar** [arghadipmanna101/Flipkart_Clone#1180]
### Describe the feature

![Screenshot 2024-06-13 131746](https://github.com/arghadipmanna101/Flipkart_Clone/assets/67885970/d9ee4149-5669-423a-a980-f576770c7d30)
![Screenshot 2024-06-13 131754](https://github.com/arghadipmanna101/Flipkart_Clone/assets/67885970/c1133ed3-9577-4fac-a0a0-f41444814d1e)
# things to change
- change to login in the home page instead of account 
- resize the nav bar size accordingly
- also changing the category list item accordingly

### Describe the solution you'd like

# Things I will do
-  add login in the home page instead of account 
-  correcting the nav bar size accordingly
-  changing the category list and category name of all item accordingly
- getting proper padding in the category div

### Describe alternatives you've considered

If the website is not-meant to be exact replica the also the placement of all item looks odd 
# I would suggest 
- change the account to **login**
- make responsive 
- proper placement of nav bar **content** accordingly
- resize the category list item and provide proper padding to it

### Add ScreenShots

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/67885970/51c094a6-40a7-48c0-88b4-bdd1ee79f9cb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by jayanththalla** [comment]
please assign me @pa

**Comment by AryanAwtar** [comment]
Please assign me and add tag
I would like to contribute

**Comment by AryanAwtar** [comment]
i am facing problem in my pr
please help

**Comment by AryanAwtar** [comment]
> i am facing problem in my pr please help the code is working fine in my system i have only corrected some css yet i am facing problem

i haven't changed any div or name of any class
