### ISSUE TITLE
Improving the header of the home page

### ISSUE THREAD

**Issue by Jatin-gumber12** [arghadipmanna101/Flipkart_Clone#121]
The home of the website is not same as the original page.
![Screenshot (6)](https://github.com/arghadipmanna101/Flipkart_Clone/assets/93000878/e712ec64-bbe6-4d09-b0b8-034403d59561)
This is the original page

**Comment by Gyanshu-Kumar** [comment]
Can You Assign This issue to me

**Comment by AbhinayBhadauria99** [comment]
Assign me the issue please i am also working usnder GSSoc24

**Comment by gargimukherjee25** [comment]
Hello I am Gargi from IIT Kharagpur! I work with html,css,js,react.js and so on and am eager to learn more. I'd appreciate being assigned this task for GSSoC 24.

**Comment by prajna321** [comment]
It seems that the home page of the website is not identical to the original page. I'd like to ensure consistency between the two versions. 
You can find examples of my previous work and projects on my LinkedIn profile https://www.linkedin.com/in/prajna-paul-117086256/ and my GitHub account https://github.com/prajna321/.
Could you please assign me this task? I'll work on aligning the home page with the original design. 
Thank you!

**Comment by arghadipmanna101** [comment]
Go ahead guys @Jatin-gumber12 and @prajna321

**Comment by prajna321** [comment]
@arghadipmanna101 The issue has already been resolved in ##234. Kindly have a look and merge it.
