### ISSUE TITLE
The home page not loading correctly . let me fix that 

### ISSUE THREAD

**Issue by Helios-snd** [arghadipmanna101/Flipkart_Clone#122]

**Comment by Ayushvishwakarma04** [comment]
Hello! 😊 I'd appreciate being assigned this task for GSSoC 24.

**Comment by Aradhya-005** [comment]
please assign this to me under GSSoC'24

**Comment by MuraliDharan7** [comment]
I can fix the issue. Kindly assign this task to me under GSSoC'24

**Comment by prajna321** [comment]
@arghadipmanna101 
It appears that the home page is not loading correctly. I'm ready to address this issue and ensure that the page loads properly for all users.
You can find examples of my previous work and projects on my LinkedIn profile https://www.linkedin.com/in/prajna-paul-117086256/ and my GitHub account https://github.com/prajna321/.
Please assign me this task, and I'll work on fixing the home page loading issue promptly.
Thank you!

**Comment by Helios-snd** [comment]
Thanks a lot @arghadipmanna101
