### ISSUE TITLE
BUG: Wrong flight name is written 

### ISSUE THREAD

**Issue by kanishk-2** [arghadipmanna101/Flipkart_Clone#1222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Wrong flight name is written  as ixigo it should be akasa as akasa flights pics are there

### What happened?

Will add other flight option as ixigo is not a popular name for flights.

### Screenshots

<img width="565" alt="2" src="https://github.com/arghadipmanna101/Flipkart_Clone/assets/157130879/c5d6957c-c067-4c9e-9624-5bd4e7a9d453">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by adityasingh-0803** [comment]
we can add different deals and flights please assign under gssoc label
