### ISSUE TITLE
when we click on this it is not showing result.

### ISSUE THREAD

**Issue by PrabhjotBajwa** [arghadipmanna101/Flipkart_Clone#1234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

@arghadipmanna101 plz assign this issue to me under gssoc24 label .

### Screenshots

![link](https://github.com/arghadipmanna101/Flipkart_Clone/assets/148677213/d67a6cdd-f7ff-48e3-9420-fe1837d1e62c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by GOURAV-VERMAA** [comment]
please assign issue #1234
