### ISSUE TITLE
Links are not working will fix it .

### ISSUE THREAD

**Issue by PrabhjotBajwa** [arghadipmanna101/Flipkart_Clone#1238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

@arghadipmanna101 plz assign this issue to me under gssoc24 label.

### Screenshots

![links2 0](https://github.com/arghadipmanna101/Flipkart_Clone/assets/148677213/1a985f36-a395-407f-85a9-7d45b0c6f432)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by DhruvJohri** [comment]
please assign this issue to me @arghadipmanna101
