### ISSUE TITLE
BUG: The navbar doesn't look similar to the original flipkrt website

### ISSUE THREAD

**Issue by ayushrskiaa** [arghadipmanna101/Flipkart_Clone#1240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The navbar of the cloned website is not similar to the original website.

Cloned website navbar
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/130389607/720822ab-cb73-4e96-b82e-3ea3bd9803db)

Original website navbar
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/130389607/d37e7108-53f5-4adc-93c1-7f9db0247c4c)

### Expected behavior

it should be the same as the original website

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ayushrskiaa** [comment]
@arghadipmanna101, please assign it to me. I want to work on it.
Thank you

**Comment by Ananya-Nair20** [comment]
Hello,

I am interested in solving this issue. Please assign this issue to me under GSSOC'24 with appropriate GSSOC-level labels.

Thank you

**Comment by DhruvJohri** [comment]
please assign this issue to me @arghadipmanna101
