### ISSUE TITLE
DOC: Adding best Deal section on homepage

### ISSUE THREAD

**Issue by dhairyagothi** [arghadipmanna101/Flipkart_Clone#1245]
### What's wrong with the existing documentation

there is nothing to show in best deal section

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/142989448/2b574928-3833-4dd2-abbe-4827e3b58d45)

### File to change

to add best deal section

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by dhairyagothi** [comment]
@arghadipmanna101 please assign this issue to me under gssoc

**Comment by adityasingh-0803** [comment]
@arghadipmanna101 please assign this issue to me under gssoc

**Comment by DhruvJohri** [comment]
please assign this issue to me @arghadipmanna101

**Comment by dhairyagothi** [comment]
okay i will make PR @arghadipmanna101
