### ISSUE TITLE
fix navbar

### ISSUE THREAD

**Issue by Debanjannnn** [arghadipmanna101/Flipkart_Clone#125]

**Comment by MelissaSequeira** [comment]
I can do it...Plz consider me for the task
https://melissasequeira.github.io/fashionweb.github.io/

**Comment by Debanjannnn** [comment]
> I can do it...Plz consider me for the task https://melissasequeira.github.io/fashionweb.github.io/

pls  do

**Comment by bhaveshnegi** [comment]
I have made a Zomato clone, so I can help you to solve this issue

**Comment by MelissaSequeira** [comment]
> > I can do it...Plz consider me for the task https://melissasequeira.github.io/fashionweb.github.io/
> 
> pls do

But u need to assign it first to me

**Comment by Harshita2027** [comment]
i would like to work on this please assign it to me

**Comment by MelissaSequeira** [comment]
Thank You

also plz add level label....it was mentioned in live session today

**Comment by Sehar-Tahir** [comment]
I have made a Amazon clone, so I can do it. Kindly assign it to me.

**Comment by ShubhamPaliwal03** [comment]
I want to contribute to this, please assign this to me.
I have previously created navbars for websites, you can check out my work here : https://myamazonclone.000.pe/index.php

**Comment by Aradhya-005** [comment]
i would like to work on this . please assign it to me

**Comment by solanki505** [comment]
I want to work on this issue please assign me this under GSSOC'24

**Comment by AbhinayBhadauria99** [comment]
Assign me the issue please i am also working usnder GSSoc24

**Comment by chirag-tomar2003** [comment]
I have worked on these types of clones, i can imporve the navbar , please assign me this issue.

**Comment by SalehaTabassum** [comment]
Hi @arghadipmanna101 please assign this issue to me .I have already worked on Spotify , Netflix and Amazon clone .so ,I would solve this issue better please assign it to me

**Comment by Artuiro-23** [comment]
Earlier I've worked on Netflix clone. Kindly assign me the issue.
Thankyou.
