### ISSUE TITLE
Redesgin the Ui on Cart page 

### ISSUE THREAD

**Issue by Gokilp** [arghadipmanna101/Flipkart_Clone#1251]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Redesgin the Ui on Seller page Card not not impressive Ui some elements are Missing 

### Screenshots
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/76507378/75a31608-eac8-4470-85e9-78052ef5c30f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Gokilp** [comment]
Kindly please assign the  issue to me

**Comment by adityasingh-0803** [comment]
@arghadipmanna101 this task is interesting kindly assign

**Comment by Gokilp** [comment]
kindly please assign to me @arghadipmanna101

**Comment by Gokilp** [comment]
Thank you So assign to me

**Comment by Gokilp** [comment]
Kindly please review my pr @arghadipmanna101

**Comment by Gokilp** [comment]
Kindly please review my pr @arghadipmanna101

**Comment by Gokilp** [comment]
kindly please review my pr @adityasingh-0803

**Comment by adityasingh-0803** [comment]
I'm not the project admin @Gokilp

**Comment by Gokilp** [comment]
> I'm not the project admin @Gokilp 

Sorry 😔
