### ISSUE TITLE
improve the footer

### ISSUE THREAD

**Issue by jayanththalla** [arghadipmanna101/Flipkart_Clone#1253]
### Describe the feature

The height of the footer more alignment is not proper

### Describe the solution you'd like

By improve the footer the height will decrease and looks good

### Describe alternatives you've considered

alignemnt of the footer 

### Add ScreenShots

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/121346142/869a3719-8ab6-4d12-b265-c8835eb980c5)
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/121346142/f8933d2f-df29-4640-a357-4ae8aec73a4b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by DhruvJohri** [comment]
please assign this to me @arghadipmanna101

**Comment by DhruvJohri** [comment]
under gssoc24
