### ISSUE TITLE
BUG: Duplicate products on one page

### ISSUE THREAD

**Issue by root-0101** [arghadipmanna101/Flipkart_Clone#1258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As there is duplicate product showing for "vivo T3x 5g"

### Screenshots

![Screenshot 2024-06-18 211700](https://github.com/arghadipmanna101/Flipkart_Clone/assets/142779809/d568787b-4752-48cf-865a-ea312c2f177b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by adityasingh-0803** [comment]
@arghadipmanna101 i can do it
