### ISSUE TITLE
adding more sections to it and adding some formating 

### ISSUE THREAD

**Issue by anushreemehta6** [arghadipmanna101/Flipkart_Clone#126]
@arghadipmanna101  i want to add new section to it , the small sections that are there in flipkart site . i have made amazon clone so i might know how to make the next section . 
GSSOC'24

**Comment by aasthax1** [comment]
I want to fix this issue. I am very versed in making clones,i have made amazon,spotify clones.
#GSSOC'24

**Comment by ShatakshiPalli** [comment]
I would like to work on this issue and add some sections in detail. Please assign me this issue.

**Comment by arghadipmanna101** [comment]
> @arghadipmanna101 i want to add new section to it , the small sections that are there in flipkart site . i have made amazon clone so i might know how to make the next section . GSSOC'24

You have been assigned @anushreemehta6
