### ISSUE TITLE
Feat: Contact Us section UI design CSS style improving.

### ISSUE THREAD

**Issue by sakeel-103** [arghadipmanna101/Flipkart_Clone#1264]
### Describe the feature

@arghadipmanna101 
Dear admin,
In contact Us section I want to Change the UI of the section,
Please assign this task to me under gssoc'24.

### Describe the solution you'd like

I'll modify the UI of the Contact Us section without any change in the format and the color of the contact Us section

### Describe alternatives you've considered

If this change will not be good then you can reject the PR

### Add ScreenShots

SS -
![p15](https://github.com/arghadipmanna101/Flipkart_Clone/assets/136844498/df70a66f-58c5-4fd6-903f-77f019e4e916)

Demo SS - 
![p19](https://github.com/arghadipmanna101/Flipkart_Clone/assets/136844498/3323fb2a-34e7-4955-b356-a2d12b30e8ac)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sarthaksharma39** [comment]
I would like to work on this issue. It would be great if you assign this to me. I am good at UI.
Thank you
Your sincerely,
Sarthak Sharma

**Comment by sakeel-103** [comment]
@arghadipmanna101 
I have solved this feature and I attached at demo SS. Please check it.
