### ISSUE TITLE
Feat: Hover effect on social media icon 

### ISSUE THREAD

**Issue by heli0707** [arghadipmanna101/Flipkart_Clone#1267]
### Describe the feature

A hover effect on a social media icon typically involves a color change, animation (like scaling or fading), or a cursor change to indicate interactivity, enhancing user engagement.
please assign this Issue to me!

### Describe the solution you'd like

![Screenshot (177)](https://github.com/arghadipmanna101/Flipkart_Clone/assets/95361125/be53bcc2-9943-4aa1-a9b6-6a39d22e5699)

like this adding the hover effect on icons 

### Describe alternatives you've considered

Visual mechanism activated by cursor hover on social media icons.

### Add ScreenShots

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/95361125/647c646f-3c44-41c8-801a-e5363476a40e)

improve this 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sarthaksharma39** [comment]
I would like to work on this issue. It would be great if you assign this to me.
Thank you
Your sincerely,
Sarthak Sharma
