### ISSUE TITLE
Feat: UI enhanment 

### ISSUE THREAD

**Issue by krishnas2004** [arghadipmanna101/Flipkart_Clone#1269]
### Describe the feature

in the navigation 
<img width="218" alt="image" src="https://github.com/arghadipmanna101/Flipkart_Clone/assets/171499802/e036d297-0dd0-4d88-8a87-9bab0d14f315">
login {v} arrow is mis placed and Become Seller is there the text is cutted 

### Describe the solution you'd like

the login section should be in centered and Become Seller part will be in should in good padding 

### Describe alternatives you've considered

will use styling  and padding issues to solve

### Add ScreenShots

<img width="218" alt="image" src="https://github.com/arghadipmanna101/Flipkart_Clone/assets/171499802/177f6be8-3a38-444c-a03f-354bfd617f52">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by krishnas2004** [comment]
@arghadipmanna101 pls assign me this issue

**Comment by Sandeepkumargond** [comment]
@arghadipmanna101 pls assign me this issue. I want to contribute on this project.
Before--

![Screenshot 2024-06-25 122923](https://github.com/arghadipmanna101/Flipkart_Clone/assets/157467932/9aa25946-497a-42b8-8716-d33cc4172af6)

After--

![Screenshot 2024-06-25 122934](https://github.com/arghadipmanna101/Flipkart_Clone/assets/157467932/1168e746-b652-4021-aeec-320016d0f781)
