### ISSUE TITLE
Feat: Adding hover effects on the "Frequently asked Question" paragraph.

### ISSUE THREAD

**Issue by sakeel-103** [arghadipmanna101/Flipkart_Clone#1270]
### Describe the feature

In the "Frequently Asked Question" section. Here I want to add an effect on the paragraph tag.

### Describe the solution you'd like

If you think it will look good after adding. Then, please assign this to me under gssoc'24.

### Describe alternatives you've considered

@arghadipmanna101 
Dear admin,
I have explained feature I want to add.
Please assign this to me under gssoc'24.

### Add ScreenShots

SS -
![p20](https://github.com/arghadipmanna101/Flipkart_Clone/assets/136844498/7282bce9-e28a-4ba0-9af3-58aa6b4d8dfb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sakeel-103** [comment]
@arghadipmanna101 
Dear PA,
Please check this issue and assign this task to me under gssoc'24

**Comment by GOURAV-VERMAA** [comment]
please assign issue #1270

**Comment by sakeel-103** [comment]
Dear PA,
please check the website, there in frequently asked question section answer texts not displaying. without merging my PR this happed, I think you have merged some PR's may be this happed from that.

video - 

https://github.com/arghadipmanna101/Flipkart_Clone/assets/136844498/1dd8a218-08c9-448a-bccf-95ea411f8e31
