### ISSUE TITLE
Improved Hovering Effect

### ISSUE THREAD

**Issue by AbhinayBhadauria99** [arghadipmanna101/Flipkart_Clone#128]
While Hovering at "follow us on" section at footer ,icons turns bluish with underline and in navbar hovering is not proper.

**Comment by AbhinayBhadauria99** [comment]
I want to fix this issue.Please assign this to me.

**Comment by richasriva** [comment]
Please assign this task to me. I can fix this issue properly.

**Comment by SuhainaFathimaM** [comment]
please assign this task to me

**Comment by arghadipmanna101** [comment]
Go ahead guys

**Comment by codebreaker3008** [comment]
Could you assign this to me @arghadipmanna101

**Comment by Saimanjari777** [comment]
Hi, I want to fix this issue because it needs  hovering effect on the footer section and header section properly. Please assign the task to me.

**Comment by AditiJeena** [comment]
can you please assign this issue to me?

**Comment by Anusrita-Karmakar** [comment]
I'm looking forward to work on this issue @arghadipmanna101  under GSSoC'24. It would be a pleasure for me to contribute to this issue. Kindly assign this issue to me.

**Comment by Artuiro-23** [comment]
I can resolve this issue. Kindly assign me this task.
Thankyou.

**Comment by richasriva** [comment]
That pull request is for this issue.

**Comment by SuhainaFathimaM** [comment]
#155

**Comment by SuhainaFathimaM** [comment]
@arghadipmanna101  you can close this issue as it has been fixed
