### ISSUE TITLE
BUG : Unusual spacing and Fonts issues

### ISSUE THREAD

**Issue by sauraabhh** [arghadipmanna101/Flipkart_Clone#1280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the Frequently Asked Questions sections there is an unusal spacing and the font colors also seems off so it looks more unorganised which I would like to modify it 

### Expected behavior

I want a FAQ section which seems more attractive to user which would help them and the color scheme seems off in that particular section . 

### Screenshots

![Screenshot 2024-06-21 223105](https://github.com/arghadipmanna101/Flipkart_Clone/assets/142777810/3d0fd43e-4d76-46dd-ad9a-5c058fe5971b)
@arghadipmanna101  please assign me this issue under GSSoC'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kashi-verma** [comment]
please assign me this issue it is important for me to make my profile much better.

**Comment by sauraabhh** [comment]
hey @arghadipmanna101 please review the above PR .
