### ISSUE TITLE
BUG:hover effect on nav bar

### ISSUE THREAD

**Issue by dhairyagothi** [arghadipmanna101/Flipkart_Clone#1286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/142989448/18b8fcc0-9aa7-47ae-92d6-f80b87f72740)

hover effect showing on wrong item 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by minakshikr7** [comment]
Please assign me this issue under @GSS0C24

**Comment by dhairyagothi** [comment]
please add level badge @arghadipmanna101
