### ISSUE TITLE
favicon missing again

### ISSUE THREAD

**Issue by Meetjain1** [arghadipmanna101/Flipkart_Clone#129]
@arghadipmanna101 sir assign me this issue someone have removed the favicon that i added , I am working under gssoc24

**Comment by Aditya19110** [comment]
Hey if possible please asssign this task to me i can work on it

**Comment by Khushinkm15** [comment]
hey please assign this issue to me

**Comment by T1rth1** [comment]
i would like to work upon this issue..please assign me this issue.

**Comment by Manojit-Das-10** [comment]
@arghadipmanna101 Please assign me the task.

**Comment by arghadipmanna101** [comment]
Go ahead @Meetjain1

**Comment by Meetjain1** [comment]
@arghadipmanna101 sure sir

**Comment by Meetjain1** [comment]
@arghadipmanna101 just created a pr #246, related to this Thankyou

**Comment by Meetjain1** [comment]
Have a look on PR #246 related to this issue sir , Thankyou

**Comment by Dev-AyushTrivedi** [comment]
Could you please assign this issue to me i can solve this bug quicky please assign this to me...
