### ISSUE TITLE
Feat: Add dark mode toggle button in the nav bar to improve user experience 

### ISSUE THREAD

**Issue by Vikashchou-dhary** [arghadipmanna101/Flipkart_Clone#1299]
### Describe the feature

Adding toggle button for dark and light mode

### Describe the solution you'd like

Adding toggle button for dark and light mode

### Describe alternatives you've considered

adding toggle button will improve the user experience

### Add ScreenShots

![toggle button](https://github.com/arghadipmanna101/Flipkart_Clone/assets/158028747/a2819084-9135-49a3-9be0-2adfec680bed)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by minakshikr7** [comment]
Please assign me this issue under @GSS0C24
