### ISSUE TITLE
BUG: Improve the UI of about us in home page 

### ISSUE THREAD

**Issue by Jyoti040** [arghadipmanna101/Flipkart_Clone#1307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![Screenshot_2024-06-25-15-52-06-413_com android chrome](https://github.com/arghadipmanna101/Flipkart_Clone/assets/133634700/eb8cd6b5-87ec-4f9a-a691-c9f76866c975)
I want to improve the UI of this section of page , so that it is easy to differentiate between heading and subheadings .

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by minakshikr7** [comment]
Please assign me this issue under @GSS0C24
