### ISSUE TITLE
Feature to add and remove products from wishlist.

### ISSUE THREAD

**Issue by urgetolearn** [arghadipmanna101/Flipkart_Clone#1308]
### Describe the feature

There is no feature to add a product to the wishlist. Similarly, no option to remove products from the wishlist button is not working.

### Describe the solution you'd like

Working of remove button on the wishlist and adding the add to wishlist button to the product.

### Describe alternatives you've considered

N/A

### Add ScreenShots

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/131844481/0c084e43-5162-4492-a3f1-50a912275a5d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by minakshikr7** [comment]
Please assign me this issue under @GSS0C24
