### ISSUE TITLE
Enhancing Contact Us Page

### ISSUE THREAD

**Issue by tempestanya** [arghadipmanna101/Flipkart_Clone#1309]
I propose revamping the website's Contact Us page for improved aesthetics and usability. The current design lacks appeal, hindering user engagement. By enhancing its visual elements and user interface, we can create a more welcoming and effective platform for visitor interaction.

Here's what I propose:

- **Increase Contrast:** Improve text and background color contrast for better readability.
- **Boost Readability:** Use larger and bolder fonts for clearer input field labels and text.
- **Refine Gradient:** Tone down the background gradient to reduce visual distraction.
- **Adjust Spacing:** Ensure even padding and margins for a cleaner form layout.

Current Contact Us Section lacks contrast and readability:
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/98050185/f0e245f8-28df-4a27-803e-1cd36f631999)

If assigned I'll do it justice (assign under GSSOC please).

**Comment by ShraddhaSabde** [comment]
I would like to do this task can you please assign this to me I can make it more interactive, Can you please assign it to me ?

**Comment by 143divya** [comment]
Can you please assign this issue to under gssoc24? I want to work on this.

**Comment by Tanishka023** [comment]
Hey!! Can you please assign this to me. I have already worked on this issue, I can fix this easily.
@arghadipmanna101

**Comment by sahkanishk01** [comment]
I would like to work on this task. Please assign this issue to me under GSSoC'24.

**Comment by minakshikr7** [comment]
Please assign me this issue under @GSS0C24

**Comment by tempestanya** [comment]
Thanks! Will start working on it asap.
