### ISSUE TITLE
signin,singnup page_BUG:

### ISSUE THREAD

**Issue by Meetjain1** [arghadipmanna101/Flipkart_Clone#131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I want to create signin , signup page for the clone which is missing in current flipkart clone

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aditya19110** [comment]
I can work on this issue and create a login sigup page using PHP and mysql data base so please assign me this issue so i can work on it

**Comment by ShatakshiPalli** [comment]
I would like to work on creating the sign-in and sign-up pages. Please assign me this issue.

**Comment by arghadipmanna101** [comment]
Go ahead @Meetjain1

**Comment by Meetjain1** [comment]
@arghadipmanna101 sure sir

**Comment by say-het** [comment]
Can you assign me this issue I have already solved it

**Comment by Meetjain1** [comment]
created signin,signup page successfully @arghadipmanna101 sir , using proper Html,css,js I request you to please check it once Thankyou PR #253 #254 #256 #257
