### ISSUE TITLE
 Orders page should be more interactive - columns adjustments

### ISSUE THREAD

**Issue by ShraddhaSabde** [arghadipmanna101/Flipkart_Clone#1310]
### Describe the feature

proper positioning of data

### Describe the solution you'd like

I would like to make it more interactice columns should be in proper box with completion of sentences in same line. there should be proper position for search order box and no more results to display.
Please assign this task to me.

### Describe alternatives you've considered

-

### Add ScreenShots

![orders](https://github.com/arghadipmanna101/Flipkart_Clone/assets/152782195/13053547-cdbb-4a15-ad58-62e232efedee)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by minakshikr7** [comment]
Please assign me this issue under @GSS0C24

**Comment by ShraddhaSabde** [comment]
Thank you for assigning task.

**Comment by ShraddhaSabde** [comment]
@arghadipmanna101 Please assign the label to issue.
