### ISSUE TITLE
Feat: Redesign the search results in the search bar as Flipkart

### ISSUE THREAD

**Issue by SrinivasDevolper** [arghadipmanna101/Flipkart_Clone#1315]
### Describe the feature

Redesign the search results in the search bar as Flipkart

### Describe the solution you'd like

Redesign the search results in the search bar as Flipkart

### Describe alternatives you've considered

Redesign the search results in the search bar as Flipkart

### Add ScreenShots

https://github.com/arghadipmanna101/Flipkart_Clone/assets/121508628/448d0d96-7841-43a2-87ef-4ec1b55ce51b

**I'm GSSOC24 Contributor
Please assign me, I would like to work on it**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by 143divya** [comment]
Can you please assign this issue to under gssoc24? I want to work on this.
