### ISSUE TITLE
Feature ✨: Add progress bar in scroll to top button

### ISSUE THREAD

**Issue by TheNikhilRaj** [arghadipmanna101/Flipkart_Clone#1316]
### Describe the feature

Hey @arghadipmanna101 ,
I have noticed a small issue that I believe could enhance the user experience. Currently, there is no progress bar in the scroll to top button present on the website, which makes navigation a bit cumbersome, especially when users need to return to the top of a lengthy page.

Though it may seem minor, the absence of this feature can impact the overall usability and performance of the website.

### Describe the solution you'd like

@arghadipmanna101 ,Could you please assign me this issue under gssoc'24 ?

GSSOC'24

### Describe alternatives you've considered

Add progress in scroll to top button!

### Add ScreenShots

Screenshot(Mandatory):

![343046177-a64505c3-c4e1-432e-bd29-29228d4ab763](https://github.com/arghadipmanna101/Flipkart_Clone/assets/129590267/404f8025-9ca5-4dbc-b660-cac20005d1c3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by 143divya** [comment]
Can you please assign this issue to under gssoc24? I want to work on this.

**Comment by TheNikhilRaj** [comment]
@arghadipmanna101 add the labels??
