### ISSUE TITLE
DOC: add animations.css

### ISSUE THREAD

**Issue by AKSHITHA-CHILUKA** [arghadipmanna101/Flipkart_Clone#1331]
### What's wrong with the existing documentation

add custom CSS animations that can be used throughout the site.

### File to change

adding new file 

### Details of the change

animations to be added 

### Type of change

adding new sections 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by minakshikr7** [comment]
Please assign me this issue under @GSS0C24

**Comment by AKSHITHA-CHILUKA** [comment]
please assign mee

**Comment by pragatiiib** [comment]
please assign this to  me
