### ISSUE TITLE
On hovering on social media icons the color is not visible in footer

### ISSUE THREAD

**Issue by Shanukumar2929** [arghadipmanna101/Flipkart_Clone#136]
### Describe the feature

Enhance the user experiene by making user friendly color of the social media icons

### Add ScreenShots

![Screenshot (610)](https://github.com/arghadipmanna101/Flipkart_Clone/assets/98840506/d3abebd3-5791-46c9-a8ea-9ab061ae56c3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sheryar-bit** [comment]
i would love to work on this can you please assign it to me @arghadipmanna101

**Comment by ShatakshiPalli** [comment]
I would like to work on the issue and improve the footer section. Please assign me this issue.

**Comment by arghadipmanna101** [comment]
You have been assigned. Go ahead @Shanukumar2929

**Comment by Shanukumar2929** [comment]
I have updated the changes .Please Check it as I have  created Pull request.

**Comment by LordVaibhav** [comment]
please assign this to me @arghadipmanna101
