### ISSUE TITLE
Feat: Register Page 

### ISSUE THREAD

**Issue by AnshRehan04** [arghadipmanna101/Flipkart_Clone#1376]
### Describe the feature

Want to make a Register page for the new user in the login into account section.
Please assign me this task under GSSoC'24.
Thank You.

### Describe the solution you'd like

The solution for this is to make a register page with username email id and create password fields.

### Describe alternatives you've considered

alternative can be using firebase continue using google.

### Add ScreenShots

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/118544177/df8b63b2-2705-41ad-98a6-bfb18bab41ea)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhisek2004** [comment]
i want to contribute
