### ISSUE TITLE
BUG: Button text is not perfectly centered.

### ISSUE THREAD

**Issue by AMANVISHWAKARMA27** [arghadipmanna101/Flipkart_Clone#141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I found that the button text "View All News" in the main page is not perfectly at the center.
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/143862235/49b3d12a-4110-4b72-b7cd-65e4e17af179)
I would like to correct it.
@arghadipmanna101 , kindly assign me the issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by arghadipmanna101** [comment]
Go ahead

**Comment by gargimukherjee25** [comment]
Hello I am Gargi from IIT Kharagpur! I work with html,css,js,react.js and so on and am eager to learn more. I'd appreciate being assigned this task for GSSoC 24.

**Comment by Caliber-Ruchi** [comment]
Hey  I want to contribute in this issue. Kindly assign it .

**Comment by richasriva** [comment]
I can fix this issue properly. Kindly assign this task to me.

**Comment by arghadipmanna101** [comment]
Go ahead guys

**Comment by MuraliDharan7** [comment]
I am able to fix the issue. Kindly assign the task to me as well

**Comment by Nikhilsaini481-tech** [comment]
Hello @arghadipmanna101 My name is Nikhil saini I am from NIT Kurukshetra. I have experience in HTML ,css tailwind , react and javascript . i can fix this issue effectively can you assign this issue to me

**Comment by shendgeshraddha** [comment]
I am Gssoc'24 contributor and I wanna to work on this issue

**Comment by arghadipmanna101** [comment]
the issue solved.
