### ISSUE TITLE
Feat:  reduce the size of submit button

### ISSUE THREAD

**Issue by reshamsai150** [arghadipmanna101/Flipkart_Clone#1425]
### Describe the feature

In rating section reduce the size of submit button 

### Describe the solution you'd like

i will adjust the size of submit button

### Add ScreenShots

![image](https://github.com/user-attachments/assets/14098b6d-56b2-4791-89af-00d51eac822e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by dharna27** [comment]
Please assign this issue to me.
