### ISSUE TITLE
Feat: Adding Terms to Use Page in Flipkart Clone

### ISSUE THREAD

**Issue by SadafKausar2025** [arghadipmanna101/Flipkart_Clone#1427]
### Describe the feature
Flipkart terms of use is missing in this clone which is very important I want to add this

### Describe the solution you'd like

.

### Describe alternatives you've considered

.

### Add ScreenShots

![Screenshot (2193)](https://github.com/user-attachments/assets/b2cb3134-2c77-4114-924a-1d864aa7a724)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ritik7739** [comment]
Hi @arghadipmanna101,

I'd like to take on this issue. Could you please assign it to me? I will work on fixing it.

Thanks!
