### ISSUE TITLE
Feat: Adding a NavBar

### ISSUE THREAD

**Issue by Sheryar-bit** [arghadipmanna101/Flipkart_Clone#143]
### Describe the feature

I would like to add a navbar to the website as there is not one added, I would really appreciate it, if you could assign this task to me @arghadipmanna101 

### Add ScreenShots

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/132276541/33bef4d7-6b26-4992-b879-ea18528e0b0c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by gargimukherjee25** [comment]
Hello I am Gargi from IIT Kharagpur! I work with html,css,js,react.js and so on and am eager to learn more. I'd appreciate being assigned this task for GSSoC 24.

**Comment by Sneha4580** [comment]
I would like to work on this project. Please assign it to me.

**Comment by Pujan-sarkar** [comment]
@arghadipmanna101 i have already added the navbar check the pr

**Comment by Varsani2520** [comment]
i really want to work on this issue ,please assign me

**Comment by Rish-tech1** [comment]
I would like to work on this issue. Pls assign me this!!

**Comment by arghadipmanna101** [comment]
> ### Describe the feature
> I would like to add a navbar to the website as there is not one added, I would really appreciate it, if you could assign this task to me @arghadipmanna101
> 
> ### Add ScreenShots
> ![image](https://private-user-images.githubusercontent.com/132276541/329696077-33bef4d7-6b26-4992-b879-ea18528e0b0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MTI0MTYsIm5iZiI6MTcxNTQxMjExNiwicGF0aCI6Ii8xMzIyNzY1NDEvMzI5Njk2MDc3LTMzYmVmNGQ3LTZiMjYtNDk5Mi1iODc5LWVhMTg1MjhlMGIwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwNzIxNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMmJlOWNmMjczMDQyZDMzMzE4NjE1Yjg5NjYzYzM5YTYyODBmZjlhMzllMTVjMzcyMTA3NzRiMmU4ZTQ0YWFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cNllM4YeKG3MIq5MtbKxFMF_a0jB9cDG5P113gxCrCg)
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Go ahead @Sheryar-bit

**Comment by Sheryar-bit** [comment]
> > ### Describe the feature
> > I would like to add a navbar to the website as there is not one added, I would really appreciate it, if you could assign this task to me @arghadipmanna101
> > ### Add ScreenShots
> > ![image](https://private-user-images.githubusercontent.com/132276541/329696077-33bef4d7-6b26-4992-b879-ea18528e0b0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MTI0MTYsIm5iZiI6MTcxNTQxMjExNiwicGF0aCI6Ii8xMzIyNzY1NDEvMzI5Njk2MDc3LTMzYmVmNGQ3LTZiMjYtNDk5Mi1iODc5LWVhMTg1MjhlMGIwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwNzIxNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMmJlOWNmMjczMDQyZDMzMzE4NjE1Yjg5NjYzYzM5YTYyODBmZjlhMzllMTVjMzcyMTA3NzRiMmU4ZTQ0YWFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cNllM4YeKG3MIq5MtbKxFMF_a0jB9cDG5P113gxCrCg)
> > ### Record
> > 
> > * [x]   I agree to follow this project's Code of Conduct
> > * [x]   I'm a GSSOC'24 contributor
> > * [x]   I want to work on this issue
> 
> Go ahead @Sheryar-bit

Thank you, I’ll start working on this one.

**Comment by arghadipmanna101** [comment]
> > > ### Describe the feature
> > > I would like to add a navbar to the website as there is not one added, I would really appreciate it, if you could assign this task to me @arghadipmanna101
> > > ### Add ScreenShots
> > > ![image](https://private-user-images.githubusercontent.com/132276541/329696077-33bef4d7-6b26-4992-b879-ea18528e0b0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MTI0MTYsIm5iZiI6MTcxNTQxMjExNiwicGF0aCI6Ii8xMzIyNzY1NDEvMzI5Njk2MDc3LTMzYmVmNGQ3LTZiMjYtNDk5Mi1iODc5LWVhMTg1MjhlMGIwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwNzIxNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMmJlOWNmMjczMDQyZDMzMzE4NjE1Yjg5NjYzYzM5YTYyODBmZjlhMzllMTVjMzcyMTA3NzRiMmU4ZTQ0YWFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cNllM4YeKG3MIq5MtbKxFMF_a0jB9cDG5P113gxCrCg)
> > > ### Record
> > > 
> > > * [x]    I agree to follow this project's Code of Conduct
> > > * [x]    I'm a GSSOC'24 contributor
> > > * [x]    I want to work on this issue
> > 
> > 
> > Go ahead @Sheryar-bit
> 
> Thank you, I’ll start working on this one.

Best of luck 🤞

**Comment by Sheryar-bit** [comment]
The issue is resolved. check PR #181

**Comment by Sheryar-bit** [comment]
The issue is resolved. check PR #181
