### ISSUE TITLE
Feat: Need to remove extra white space beneath the footer section and update the footer section!!

### ISSUE THREAD

**Issue by saysab29** [arghadipmanna101/Flipkart_Clone#144]
### Describe the feature

1. The footer section will look clean after removing the white space.
2. After adding more sections in the footer sections, it will look similar to the Flipkart website.
3. Need to fix alignment issues (A thin line inside the footer needs to be extended to the edges).

### Add ScreenShots

![Screenshot 2024-05-11 014207](https://github.com/arghadipmanna101/Flipkart_Clone/assets/90868012/de31a37a-acc9-4d65-b5a3-c0d833a14e16)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by motuncoded** [comment]
Helo, I am currently a GSSOC contributor, kindly assign the issue to me

**Comment by prajna321** [comment]
The proposed feature involves refining the footer section to eliminate white space, adding more sections for a layout similar to Flipkart's website, and addressing alignment issues by extending a thin line to the edges.
With my expertise in frontend design, I'm prepared to implement these enhancements effectively. You can review my background on my LinkedIn profile https://www.linkedin.com/in/prajna-paul-117086256/ and my GitHub account https://github.com/prajna321/.
Please assign me this task. Thank you!

**Comment by Anou25** [comment]
Hi, I would like to work on this issue, please can you assign this to me.

**Comment by Harshit279096** [comment]
we can remove white space and add some FAQ section in place of the same.
kindly assign this task to me.
