### ISSUE TITLE
Feat: Add Security Page to the Website

### ISSUE THREAD

**Issue by jency1** [arghadipmanna101/Flipkart_Clone#1446]
### Describe the feature

The website currently lacks a dedicated security page that provides users with information about the site's security measures, data protection practices, and guidelines for staying secure. Adding a security page will enhance user trust and transparency.

@arghadipmanna101 Please assign this issue to me.

### Describe the solution you'd like

1. Design and Layout
2. Navigation
3. Functionality
4. Content

### Add ScreenShots

![Screenshot 2024-07-22 215035](https://github.com/user-attachments/assets/2e2955ee-2282-42a1-bf4f-6386d61794e5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SadafKausar2025** [comment]
hello @jency1 
please check I think it is already added

**Comment by jency1** [comment]
> hello @jency1 please check I think it is already added

@SadafKausar2025 No, it is not there. I had checked it and then raised the issue. So, I have added it today only. 

I have made the page from scratch and added it to the website along with linking it in the footer section in the home page. 

Please do check it and merge this PR. 

Thank you.
