### ISSUE TITLE
Feat:Fixing the nav bar and Addition of "list of categories"

### ISSUE THREAD

**Issue by CharviPalem** [arghadipmanna101/Flipkart_Clone#146]
### Describe the feature

i would i like to fix up the nav bar such that it fits the width and remove the duplicate icons 
please assign me the task 

### Add ScreenShots

![Screenshot 2024-05-11 063448](https://github.com/arghadipmanna101/Flipkart_Clone/assets/145920684/97561085-07ef-413d-8f4f-343e44676bc7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Yashaswini-raj** [comment]
Fixing the navigation bar to ensure proper functionality and user experience.

Could you please assign this work to me for implementation under GSSOC'24?

**Comment by Manojit-Das-10** [comment]
Could you please assign me the task of fixing up the navigation bar so that it fits the width properly and removing any duplicate icons?
![Uploading Flipkart Clone.png…]()

**Comment by arghadipmanna101** [comment]
sure go ahead guys

**Comment by CharviPalem** [comment]
@arghadipmanna101 
sir i have fixed the nav bar as well as added the categories list...

could u please assign another task.......Iam willing up to make a profile page  

![Screenshot 2024-05-11 182621](https://github.com/arghadipmanna101/Flipkart_Clone/assets/145920684/4c8630fc-f3e5-41f1-92ef-82cfb69c4cf1)
