### ISSUE TITLE
improvements in design adding navbar and login/signup page

### ISSUE THREAD

**Issue by RiyaaBhatt** [arghadipmanna101/Flipkart_Clone#148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

 existing website is not so good in design i want to improve that design and wanna add navbar and login/signup page please assign this under GSsoc'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by arghadipmanna101** [comment]
Go ahead @RiyaaBhatt

**Comment by codebreaker3008** [comment]
Could you please assign this to me ?

**Comment by RiyaaBhatt** [comment]
hello sir please have look at pr #236  as i have **completed** my task

**Comment by Suruchibharti** [comment]
hii! ,
I'm GSSoC'24 contributor , I have experienced on HTML, CSS, JS, and react.js , so I want to work on this issue,
so, kindly requested to you to assign me the task.

**Comment by RiyaaBhatt** [comment]
Hello! Just a gentle reminder to check PR #236 as I have completed my task. Thank you!
