### ISSUE TITLE
Feat: Adding hovering effects on Buy now and add to Cart Buttons

### ISSUE THREAD

**Issue by sahithinandikula** [arghadipmanna101/Flipkart_Clone#1481]
### Describe the feature

when a product is clicked the buttons Buy now and Add to Cart lacks hovering effectsNow

### Describe the solution you'd like

adding hovering effects makes them look better and also user can track what option he is choosing

### Describe alternatives you've considered

 Adding hover effects to your “Buy Now” and “Add to Cart” buttons can enhance user interaction and make your website more engaging we can customize the buy now button and add hovering effects to the add to cart button

### Add ScreenShots

![Screenshot 2024-07-25 200053](https://github.com/user-attachments/assets/dcbff68a-b63f-4c4d-a037-b56bef40121c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Deepali109** [comment]
Hello, I can add the amazing hover effects on these buttons so please assign me this issue under gssoc24.
