### ISSUE TITLE
Feat:Changing the color of the login button

### ISSUE THREAD

**Issue by sahithinandikula** [arghadipmanna101/Flipkart_Clone#1485]
### Describe the feature

The color of the login button has to be changed since it matches  the nav bar color and it isn't easy to find login button  

### Describe the solution you'd like

we can change the color to make it appear good and easily visible

### Describe alternatives you've considered

we can also adjust the font of login as it marks important place in the website

### Add ScreenShots

![image](https://github.com/user-attachments/assets/ab3eda90-411e-4ffc-a387-922df55b13ee)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ishag8** [comment]
Please assign this issue to me
