### ISSUE TITLE
Feat: Giving proper alignment to some elements

### ISSUE THREAD

**Issue by shraddhha** [arghadipmanna101/Flipkart_Clone#1497]
### Describe the feature

The alignment of some elements is not proper

### Describe the solution you'd like

Fixing the alignment of some elements.

### Describe alternatives you've considered

Fixing the alignment of some elements.

### Add ScreenShots

![Screenshot 2024-07-26 224355](https://github.com/user-attachments/assets/ea87966e-3f57-453f-a5f0-46a500d4f487)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by raju2109** [comment]
Hii i want to fix the alignment of some element.
please assign me this issue.
