### ISSUE TITLE
Missing links of social media in social section of footer

### ISSUE THREAD

**Issue by Meetjain1** [arghadipmanna101/Flipkart_Clone#15]
I will add the links of social media accounts in the footer section of social links  , I think we should place the social section below our footer , with icons

**Comment by Meetjain1** [comment]
@arghadipmanna101 assign this issue to me , I am working under gssoc24

**Comment by arghadipmanna101** [comment]
@Meetjain1 go ahead .

**Comment by Meetjain1** [comment]
@arghadipmanna101 sure

**Comment by Meetjain1** [comment]
@arghadipmanna101 sir , please label it as Gssoc24 . Thankyou

**Comment by Meetjain1** [comment]
@arghadipmanna101 PR #47 is already merged for this issue and hence this issue is completed ,
I request you to please label this issue as gssoc24, so that I will close this issue . Thankyou

**Comment by Meetjain1** [comment]
@arghadipmanna101 sir please label this issue under gssoc . Thankyou
