### ISSUE TITLE
Content page is not responsive BUG:

### ISSUE THREAD

**Issue by SuhainaFathimaM** [arghadipmanna101/Flipkart_Clone#151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The content page looks static.. it is not responsive for screen sizes . 
I'm a GSSOC'24 contributor
 I want to work on this issue

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by arghadipmanna101** [comment]
sure go ahead @SuhainaFathimaM

**Comment by SuhainaFathimaM** [comment]
@arghadipmanna101 I have fixed it ..

**Comment by SuhainaFathimaM** [comment]
Can I close the issue as I have fixed it?? @arghadipmanna101

**Comment by SuhainaFathimaM** [comment]
#241 PR has resolved this issue.. I have made the PR and it is merged..
@arghadipmanna101 Please mark it under GSSoC'24 and assign me this issue.. and close this issue

**Comment by SuhainaFathimaM** [comment]
@arghadipmanna101  PR has resolved this issue.. I have made the PR and it is merged..
