### ISSUE TITLE
Flipkart plus page is blank BUG:

### ISSUE THREAD

**Issue by SuhainaFathimaM** [arghadipmanna101/Flipkart_Clone#152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I would like to work on this page.. please give the overview on what to do? please assign this task to me

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by arghadipmanna101** [comment]
Go ahead @SuhainaFathimaM

**Comment by SuhainaFathimaM** [comment]
#500 Resolves this issue
