### ISSUE TITLE
Fix navbar of the website

### ISSUE THREAD

**Issue by Sneha123-zudo** [arghadipmanna101/Flipkart_Clone#153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There are repetetion of the elements in the navbar ., and it is not fixed too.
I want to fix that , please assign me this issue under GSSOC'24.
<img width="939" alt="image" src="https://github.com/arghadipmanna101/Flipkart_Clone/assets/145490348/d7140fe4-2b83-47b9-81ea-a8414ab1c7bc">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by arghadipmanna101** [comment]
Go ahead @Sneha123-zudo

**Comment by YB11102004** [comment]
please assign this issue to me @arghadipmanna101

**Comment by anshumanmondal2006** [comment]
pls assign this to me i have already fixed it and raised an issue for the navigation bar being loaded improperly @arghadipmanna101 I'm a frontend developer from IITG

**Comment by vaishnavip27** [comment]
Hey, I have worked on such projects before and i have a good experience building it. Please assign me with this issue. Looking forward for the approval
