### ISSUE TITLE
DOC:

### ISSUE THREAD

**Issue by anushreemehta6** [arghadipmanna101/Flipkart_Clone#154]
### What's wrong with the existing documentation

 @arghadipmanna101  there is no screenshot or any video of the project . i would like to add screenshot of the existing project .

### Add ScreenShots

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/104919688/fb577e26-2e38-4a59-997f-43b971e0fab0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by arghadipmanna101** [comment]
Go ahead @anushreemehta6

**Comment by Paavni-Goyal** [comment]
Hey, I would like to work on the same. Can you please assign this to me under GSSoC'24.

**Comment by MuraliDharan7** [comment]
I would like to work on this isuue. Can you please assign this to me under GSSoC'24

**Comment by Paavni-Goyal** [comment]
@arghadipmanna101 committed few changes.

**Comment by anushreemehta6** [comment]
@arghadipmanna101 i have completed this task .
