### ISSUE TITLE
Feat: adding favicon icon

### ISSUE THREAD

**Issue by solanki505** [arghadipmanna101/Flipkart_Clone#157]
### Describe the feature

I would like to add favicon icon of flipkart please assign this to me under GSSOC'24.

### Add ScreenShots

![Screenshot 2024-05-11 100454](https://github.com/arghadipmanna101/Flipkart_Clone/assets/158484284/3909b608-a7e5-43ce-95d0-cdc51011cfa1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Varsani2520** [comment]
i want to work with your project ,please assign to me ,

@arghadipmanna101 

in your web i found that 
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/137641079/a4e22cdb-4a8c-4060-bc2b-de5b91295e1d)

and also i able to solve that ,please assign me

**Comment by PRATHAMU200** [comment]
I can work on this project as early as possible and get it done assign it to me please.

**Comment by prajna321** [comment]
@arghadipmanna101
I propose adding a favicon icon of Flipkart to enhance the branding and visual identity of our website. As a frontend developer experienced in HTML and CSS, I'm well-equipped to implement this feature effectively.
You can review my extensive experience and projects on my LinkedIn profile https://www.linkedin.com/in/prajna-paul-117086256/ and my GitHub account https://github.com/prajna321/.
Please assign me this task under GSSoC'24, and I'll ensure it's completed to the highest standard.
Thank you!

**Comment by monali1653** [comment]
I would like to add favicon icon of Flipkart in this project. Please assign it to me

**Comment by samyakmaitre** [comment]
Please review my work on frontend development in [here](https://samyakmaitre.netlify.app/)!
and kindly assign the task to me, I will get it done precisely and ASAP!

**Comment by arghadipmanna101** [comment]
Go ahead @solanki505 do it fast

**Comment by ShrestyTyagi** [comment]
Describe the feature:
I would like to add favicon icon of flipkart.

Screenshot: 
from this 
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/166687676/260eb8c6-6a7b-4178-bc7c-e0a5f2ea88fb)
to 
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/166687676/b8a0b80b-58fc-45a6-8069-a928cafd40d5)

I would make that i will complete it as soon as possible.
I will be highly obliged to you if you could assign this to me.

**Comment by PRATHAMU200** [comment]
@arghadipmanna101 I have updated favicon and sent a PR please check #169

**Comment by PRATHAMU200** [comment]
I hope this issue has been resolved can you assign it to me before closing this issue? @arghadipmanna101

**Comment by arghadipmanna101** [comment]
> I hope this issue has been resolved can you assign it to me before closing this issue? @arghadipmanna101

merged it.
