### ISSUE TITLE
Feat: Navigation and home page design ,footer

### ISSUE THREAD

**Issue by Varsani2520** [arghadipmanna101/Flipkart_Clone#159]
### Describe the feature

Navigation is not display:

i able to create navigation and whole home page with footer as well as functionality  

i can create as it is like flipkart cwebsite ,i m expert on this 

### Add ScreenShots

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/137641079/74b2884b-7983-4b9c-bf66-9289f4e096f1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by prajna321** [comment]
@arghadipmanna101
I've undertaken numerous projects involving HTML, CSS, Tailwind CSS, JavaScript, and React.js, showcasing my proficiency in frontend development. Additionally, I'm presently engaged in a MERN stack project, demonstrating my capability across the entire web development spectrum.
Given my expertise, I'm confident in resolving the navigation display issue. You can review my experience and projects on my LinkedIn profile https://www.linkedin.com/in/prajna-paul-117086256/ and my GitHub account https://github.com/prajna321/.
Please assign me the task, and I'll ensure it's promptly addressed.
Thank you!

**Comment by thunders123** [comment]
I would like to work on this project . please assign it to me.

**Comment by ISHAAN-KKR** [comment]
hey i'm proficient with tailwind, i can resolve the issue in minutes, it would be great to work on this site, pls assign it to me...

**Comment by arghadipmanna101** [comment]
> ### Describe the feature
> Navigation is not display:
> 
> i able to create navigation and whole home page with footer as well as functionality
> 
> i can create as it is like flipkart cwebsite ,i m expert on this
> 
> ### Add ScreenShots
> ![image](https://private-user-images.githubusercontent.com/137641079/329754262-74b2884b-7983-4b9c-bf66-9289f4e096f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MTMwMDcsIm5iZiI6MTcxNTQxMjcwNywicGF0aCI6Ii8xMzc2NDEwNzkvMzI5NzU0MjYyLTc0YjI4ODRiLTc5ODMtNGI5Yy1iZjY2LTkyODlmNGUwOTZmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwNzMxNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNDAyOWM2MGJmMDFhYmVhOWNkMjQyNTZiODk3NWFiNDc0OGFjOWUwMDc2OTcxNjM1NzIyY2ZjZTU2ZTM4OWQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iQaU1oJK5skuMTi2r9fLb3wknuaKxEibEEWCIt7D-VM)
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Go ahead @Varsani2520

**Comment by Varsani2520** [comment]
merged it and close the issue

**Comment by Varsani2520** [comment]
@arghadipmanna101  I added the Navigation and Home Page Design ,Footer 

Check the PR and merged It.

**Comment by Varsani2520** [comment]
Hey @arghadipmanna101 ,
as a  mentor it's your responsibility to give response

check this pr and merge it

#159
