### ISSUE TITLE
updating profle button 

### ISSUE THREAD

**Issue by Meetjain1** [arghadipmanna101/Flipkart_Clone#16]
Current profile button UI is not much fascinating it should be more enhanced , its dropdown also .

**Comment by Meetjain1** [comment]
@arghadipmanna101 Assign this issue to me , I am working under Gssoc24

**Comment by arghadipmanna101** [comment]
Go ahead @Meetjain1 . do your best. best of luck......

**Comment by Meetjain1** [comment]
@arghadipmanna101 sure Thankyou

**Comment by Meetjain1** [comment]
@arghadipmanna101 just created a pr related to this issue with file name navbar.html

**Comment by Aayushi23jain** [comment]
@arghadipmanna101 Assign this issue to me , I am working under Gssoc24

**Comment by Meetjain1** [comment]
@arghadipmanna101 sir , please label it as Gssoc24 . Thankyou

**Comment by Meetjain1** [comment]
@arghadipmanna101 sir please label it as gssoc24. Thankyou

**Comment by Meetjain1** [comment]
@arghadipmanna101 sir please label this issue under gssoc . Thankyou
