### ISSUE TITLE
BUG: Add Margin Between FAQ and Contact Sections for Improved Spacing

### ISSUE THREAD

**Issue by Asin-Junior-Honore** [arghadipmanna101/Flipkart_Clone#1606]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Currently, the FAQ section and the Contact section are positioned too closely together on the Home (Landing page). This lack of margin or padding between the two sections leads to a visually cluttered layout, making it difficult for users to clearly distinguish between the FAQ content and the Contact section.

### Expected behavior

There should be a consistent margin or padding between the FAQ and Contact sections to create a clear visual separation. This will enhance readability and improve the overall user experience.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Asin-Junior-Honore** [comment]
hey @arghadipmanna101, please kindly assign this to me please

**Comment by Ranj8521Kumar** [comment]
I want to tackle this issue, please you assign this issue to me.

**Comment by Asin-Junior-Honore** [comment]
hey @arghadipmanna101 please review my linked pr, it has been opened for long now 🙏😥
