### ISSUE TITLE
Feat: header of the main page

### ISSUE THREAD

**Issue by ISHAAN-KKR** [arghadipmanna101/Flipkart_Clone#162]
### Describe the feature

the header is not there 

### Add ScreenShots

![Screenshot 2024-05-11 111235](https://github.com/arghadipmanna101/Flipkart_Clone/assets/116961842/5ac44e8c-4da4-4ba8-8ad4-e9aa2357ccd3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by YB11102004** [comment]
please assign this issue to me @ISHAAN-KKR

**Comment by ISHAAN-KKR** [comment]
with a indepth knowledge of tailwind i hope to solve this issue. it would be great if you assign it to me

**Comment by arghadipmanna101** [comment]
> ### Describe the feature
> the header is not there
> 
> ### Add ScreenShots
> ![Screenshot 2024-05-11 111235](https://private-user-images.githubusercontent.com/116961842/329757042-5ac44e8c-4da4-4ba8-8ad4-e9aa2357ccd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MTE0NDUsIm5iZiI6MTcxNTQxMTE0NSwicGF0aCI6Ii8xMTY5NjE4NDIvMzI5NzU3MDQyLTVhYzQ0ZThjLTRkYTQtNGJhOC04YWQ0LWU5YWEyMzU3Y2NkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwNzA1NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMWMxMjgxNTdhY2MzZTBhNDVjYTYxNmExZjJhMDE2ZjU5NmU0YzY2ZDIwZDI3MTU1MjMzMDQ5MjViZGRjM2U5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KFu79WhHYLZo5T1XYSp3I3UGrP_Oef2fxJMLub4B02Y)
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Sure, Go ahead @ISHAAN-KKR

**Comment by ISHAAN-KKR** [comment]
done, now you can review it and merge with the main branch
