### ISSUE TITLE
BUG:Flipkart blank page is having BUG

### ISSUE THREAD

**Issue by MuraliDharan7** [arghadipmanna101/Flipkart_Clone#163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I would like to work on this page.. please give the overview on what to do? please assign this task to me

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by arghadipmanna101** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> I would like to work on this page.. please give the overview on what to do? please assign this task to me
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Sure. go ahead @MuraliDharan7 you have been assigned
