### ISSUE TITLE
The text in the image is not properly certered

### ISSUE THREAD

**Issue by MuraliDharan7** [arghadipmanna101/Flipkart_Clone#164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![add1](https://github.com/arghadipmanna101/Flipkart_Clone/assets/130668745/3879f1e0-6768-4563-bf88-96e46411765c)
The text in this image is not perfectly centered and the images of flipkart too. This is not responsive as well

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by arghadipmanna101** [comment]
You have been assigned @MuraliDharan7 . solved it fast

**Comment by YB11102004** [comment]
please assign this issue to me @MuraliDharan7 .

**Comment by MuraliDharan7** [comment]
> You have been assigned @MuraliDharan7 . solved it fast

I have been solved it
check and add this to GSSoC'24
and add levels in to this issue

**Comment by MuraliDharan7** [comment]
What is going on..
I have already solved it. but not yet closed?

**Comment by yashika0432** [comment]
I have worked on flipkart clone before and the task is itself the main thing to make the website good, I am from GSSOC'24 and would like to contribute to this issue.
