### ISSUE TITLE
BUG:No category page 

### ISSUE THREAD

**Issue by kairveeehh** [arghadipmanna101/Flipkart_Clone#166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

no category page  , would like to create one ,
### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by arghadipmanna101** [comment]
You have been assigned @kairveeehh . Go ahead man..........

**Comment by Sudiksha18** [comment]
please asign this work under gssoc24
