### ISSUE TITLE
Adding the Logo

### ISSUE THREAD

**Issue by lakshyajn** [arghadipmanna101/Flipkart_Clone#17]
Hey there,
I just found issue about missing logo
I can add one or make one

Please assign this task to me :)

**Comment by arghadipmanna101** [comment]
Go ahead @lakshyajn .

**Comment by DhruvJohri** [comment]
Hello @arghadipmanna101 
I could fix this issue please assign it to me.


![Screenshot 2024-05-09 192426](https://github.com/arghadipmanna101/Flipkart_Clone/assets/111191087/6863b4c9-8279-4c54-b005-6f5ec9ff506c)

**Comment by arghadipmanna101** [comment]
> Hello @arghadipmanna101 I could fix this issue please assign it to me.
> 
> ![Screenshot 2024-05-09 192426](https://private-user-images.githubusercontent.com/111191087/329268684-6863b4c9-8279-4c54-b005-6f5ec9ff506c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNjMzMTYsIm5iZiI6MTcxNTI2MzAxNiwicGF0aCI6Ii8xMTExOTEwODcvMzI5MjY4Njg0LTY4NjNiNGM5LTgyNzktNGM1NC1iMDA1LTZmNWVjOWZmNTA2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQxMzU2NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjg3ZjlmNGU2NjE3ODA4ZDk0NzJlMGJmNzViMGFiMzM4NmVmZjU4YjQ3MjYwYTRhNDQ2ZDY5YTZhZDVhNzQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kWxGak-4l1flrhNefvU2R6I67TL5trIHPHnbkVtjC7s)

go ahead 👉

**Comment by DhruvJohri** [comment]
Ok sir  thank you 
Will you please resend the image

**Comment by DhruvJohri** [comment]
I have added the logo please check

**Comment by DhruvJohri** [comment]
Is it visible now

**Comment by DhruvJohri** [comment]
?

**Comment by bk408** [comment]
Hello @arghadipmanna101

I'm proposing to improve the Flipkart logo. Please assign me this issue.

**Comment by arghadipmanna101** [comment]
ok @bk408 go ahead

**Comment by PoojaGadagi08** [comment]
Hello @arghadipmanna101 sir
I would like to work on this issue as a contributor to the GSSOC. please assign this to me!
I have relevant skills that definitely help to enhance the website.

**Comment by Khushinkm15** [comment]
Hey I would like to look after this issue , so pls assign this task to me

**Comment by bk408** [comment]
Hello @arghadipmanna101

I update the logo but the status of my comment is showing open. Could you please tell me what is pending from my side

**Comment by SalehaTabassum** [comment]
Hi @arghadipmanna101 please assign this issue to me .i will add the logo make it look more better

**Comment by PoojaJoshi-25** [comment]
Hello Sir,
I would like to work on this issue as a contributor. Please assign me the task.

**Comment by Paavni-Goyal** [comment]
Hey, I would like to work on the same. Can you please assign this to me under GSSoC'24.

**Comment by arghadipmanna101** [comment]
done
