### ISSUE TITLE
tag typo

### ISSUE THREAD

**Issue by ananyabansal16** [arghadipmanna101/Flipkart_Clone#170]
### What's wrong with the existing documentation

The tag "Medium" for the level of issue is misspelt as "Midium".

### Add ScreenShots

![Screenshot 2024-05-11 at 12 21 23 PM](https://github.com/arghadipmanna101/Flipkart_Clone/assets/95698522/de9a6fc5-f73c-41f5-ac7a-cbd416e6fc68)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [x] I want to work on this issue

**Comment by ananyabansal16** [comment]
I can fix this issue.

**Comment by arghadipmanna101** [comment]
> ### What's wrong with the existing documentation
> The tag "Medium" for the level of issue is misspelt as "Midium".
> 
> ### Add ScreenShots
> ![Screenshot 2024-05-11 at 12 21 23 PM](https://private-user-images.githubusercontent.com/95698522/329760906-de9a6fc5-f73c-41f5-ac7a-cbd416e6fc68.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MTIyODgsIm5iZiI6MTcxNTQxMTk4OCwicGF0aCI6Ii85NTY5ODUyMi8zMjk3NjA5MDYtZGU5YTZmYzUtZjczYy00MWY1LWFjN2EtY2JkNDE2ZTZmYzY4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA3MTk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MTg0OGMzYWM2N2ZmNDZhMWFjZTM0MjdjYTQ4NzYxOTg2MDQ1YzZiOTBjMWFiMTMyZGI3ZTY5MmNmNWY4NjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9WwxAsiiDJ0G2Yn5luLkjiipbwdEpDrmRwKGjzDcKMw)
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Oops, It's my mistake you can't change it. I will do it. thank you
