### ISSUE TITLE
Adding options like grocery, mobiles, fashion etc

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [arghadipmanna101/Flipkart_Clone#171]
### Describe the feature

There is no kind options where a customer can easily find his/her desire things.

### Add ScreenShots

![Screenshot 2024-05-11 123427](https://github.com/arghadipmanna101/Flipkart_Clone/assets/138589633/cc17fe98-6c13-4a29-909a-b1b7c22273b8)
Here is the screenshot of how do I add the options like the flipkart app

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by arghadipmanna101** [comment]
yea sure. you have been assigned . Go ahead @Ishitamukherjee2004
