### ISSUE TITLE
No links on the footer section are working on home page

### ISSUE THREAD

**Issue by PRATHAMU200** [arghadipmanna101/Flipkart_Clone#172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Many links on the page are broken and they are not working. From social media to all footer links nothing is working.

Could you please assign this to me i will start the work as early as possible.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by arghadipmanna101** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> Many links on the page are broken and they are not working. From social media to all footer links nothing is working.
> 
> Could you please assign this to me i will start the work as early as possible.
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

sure. Go ahead

**Comment by PRATHAMU200** [comment]
@arghadipmanna101 Issue has been resolved #178 .
I will create new issue for new pages to be added by the time you can merge this request, and close the issue
