### ISSUE TITLE
Feat: Adding header in home page

### ISSUE THREAD

**Issue by bhargavshirin** [arghadipmanna101/Flipkart_Clone#173]
### Describe the feature

I want to work on the header section like Flipkart  please assign me this under gssoc level 3

### Add ScreenShots

<img width="1440" alt="Screenshot 2024-05-11 at 12 59 24 PM" src="https://github.com/arghadipmanna101/Flipkart_Clone/assets/106674601/47b8c2ce-7950-487f-9a33-2137f276bce7">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by arghadipmanna101** [comment]
> ### Describe the feature
> I want to work on the header section like Flipkart please assign me this under gssoc level 3
> 
> ### Add ScreenShots
> <img alt="Screenshot 2024-05-11 at 12 59 24 PM" width="1440" src="https://private-user-images.githubusercontent.com/106674601/329763109-47b8c2ce-7950-487f-9a33-2137f276bce7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MTI5NzIsIm5iZiI6MTcxNTQxMjY3MiwicGF0aCI6Ii8xMDY2NzQ2MDEvMzI5NzYzMTA5LTQ3YjhjMmNlLTc5NTAtNDg3Zi05YTMzLTIxMzdmMjc2YmNlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwNzMxMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wM2U4MWI4OTE0OGE5OTdmOWZiZDM4ZWJkN2UwMDZlMzBiMWUyZjdhNjdiMGFlYzQ5YTEzNDc2N2UxNWE3YTdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vYJRk2MtBguDa_zZgliR8HKNf9ganS_pXbAXNBXSroA">
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Go ahead

**Comment by Pat25Taylor** [comment]
I want to work on the header section like Flipkart please assign me this under gssoc level 1

Record

I agree to follow this project's Code of Conduct
I'm a GSSOC'24 contributor
I want to work on this issue

**Comment by Nikhilsaini481-tech** [comment]
@arghadipmanna101  I want to work on the header section please assign me this under gssoc level 1


RECORD: 

I agree to follow this project's Code of Conduct
I'm a GSSOC'24 contributor
I want to work on this issue

**Comment by AmrutaJayanti** [comment]
@arghadipmanna101 
I want to work on the header section please assign me this under gssoc'2024
I agree to follow this project's Code of Conduct
I'm a GSSOC'24 contributor
I want to work on this issue

**Comment by monali1653** [comment]
I want to work on the header section. Please assign this to me.

**Comment by Hacxmr** [comment]
@arghadipmanna101 I'm interested to resolve this issue. Kindly assign me this under GSSoC'24.
