### ISSUE TITLE
Add NavBar,Search Bar ,Add Best Deals List

### ISSUE THREAD

**Issue by RazaAli313** [arghadipmanna101/Flipkart_Clone#175]
### Describe the feature

I would add a navigation bar containing home, about,contact us buttons as well as cart and become a seller buttons .Moreover i would add a section which contains list of best deals of season  between header and footer,

 @arghadipmanna101 
Can you please assign me this project 

### Add ScreenShots

![Uploading flipkart_deals.PNG…]()

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by arghadipmanna101** [comment]
Go ahead @RazaAli313

**Comment by riteshjha61253** [comment]
@arghadipmanna101 can you assign this issue to me have knowledge of UI/UX  , CSS, JS,HTML.

**Comment by Upendra2003** [comment]
Hey @arghadipmanna101 can u assign this to me I can make the navbar look clean and attractive like the original ones and i will make footer look nicer.

**Comment by RazaAli313** [comment]
> Go ahead @RazaAli313

Thanks a lot Sir !!!
