### ISSUE TITLE
Update Nav panels

### ISSUE THREAD

**Issue by samyakmaitre** [arghadipmanna101/Flipkart_Clone#176]
### Describe the feature

I want to work on the nav section, please assign me this under gssoc level 2
I have attached a preview for the same.

### Add ScreenShots

![Screenshot 2024-05-11 130043](https://github.com/arghadipmanna101/Flipkart_Clone/assets/130790017/105becb3-fd76-4e78-8ff7-84a79cd8cb8d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by arghadipmanna101** [comment]
sure. go ahead

**Comment by royalrajputayush** [comment]
i want to work on it so kindly assign me so i can work more effectively

**Comment by LakshminarayanaBehera** [comment]
Hi ,could you please assign me this task i can work on it .

**Comment by samyakmaitre** [comment]
Completed.
