### ISSUE TITLE
Correcting the Nav-Bar Elements

### ISSUE THREAD

**Issue by lakshyajn** [arghadipmanna101/Flipkart_Clone#18]
There is not a desirable spacing in Nav-Bar in between Cart and Become a Seller
Also no drop-down in Cart

I can fix that too

Please assign it to me :)

**Comment by arghadipmanna101** [comment]
you have been assigned, go ahead  @lakshyajn

**Comment by PoojaGadagi08** [comment]
Hello @arghadipmanna101 sir
I would like to work on this issue as a contributor to the GSSOC. please assign this to me!
I have relevant skills that definitely help to enhance the website.

**Comment by ShivamPant1321** [comment]
I would like to contribute on this issue as a contributor to the GSSOC.
Kindly assign this to me!

**Comment by Komalpreet-Kaur112** [comment]
Hi @lakshyajn 
I would like to work on this issue.
Please assign this to me.

**Comment by akshita-86** [comment]
I would like to contribute on this issue as a contributor to the GSSOC. Please assign me this issue!

**Comment by lovelymahor** [comment]
I would like to contribute on this issue as a contributor to the GSSOC. Please assign me this issue!
