### ISSUE TITLE
Make nav bar stick to its position and more responsiveness

### ISSUE THREAD

**Issue by 1911aditi** [arghadipmanna101/Flipkart_Clone#185]
### Describe the feature

hi i want to work on the nav bar.As we scroll down nav bar is also moving if nav bar is stick to its position n when we scroll down it won't move it will look more professional.
i m a GSSOC contributor. i want to make my first contribution 

### Add ScreenShots

![Uploading Screenshot 2024-05-11 142236.png…]()

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by psychic-coder** [comment]
Hello I am Rohit Ganguly , I am a Full Stack Developer , I would love to contribute to this project , can you please assign me this under GSSoC'24 .

**Comment by SalehaTabassum** [comment]
Please assign this issue to me
