### ISSUE TITLE
BUG:responsive website

### ISSUE THREAD

**Issue by dhruv8433** [arghadipmanna101/Flipkart_Clone#186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Flipkart_clone website is not look good in responsive devices like mini Laptop,mobile,iPad...
I have a expert in this task
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/114583978/46e911a4-1b00-4839-88fb-55da904e325a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abizer007** [comment]
I would like to contribute to this issue under GSSOC'24
