### ISSUE TITLE
BUG: Too many errors

### ISSUE THREAD

**Issue by Abhinavpatra** [arghadipmanna101/Flipkart_Clone#187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## description
- The file links lead to wrong files
- 
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/149466436/27beea5c-9fa7-4dc2-aecb-3115dd19cc9a)

- There are styles inside the html documents even though there is a css document for it
- The nav bar is unorganized and haphazard
- 
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/149466436/de7874ec-0e36-429a-abb1-7cd73fee72c1)

The entire project is quite disorganized and needs to be structured better

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Abhinavpatra** [comment]
- I think you need this merge before others as the primary base so that others can work in it effectively. Let me know if you can assign this issue to me @arghadipmanna101

**Comment by nagamukesh** [comment]
Mnay html and css files are not found
please assign this issue to me under gssoc 2024
I can try to add some nice HTML and CSS files according to the needs
