### ISSUE TITLE
Feat: Working login page

### ISSUE THREAD

**Issue by nagamukesh** [arghadipmanna101/Flipkart_Clone#189]
### Describe the feature

I can add a properly working login page and register page using MongoDB/MySQL to store the details of users
another issue is it is even accepting emails even if they are not valid
please assign this issue to me under gssoc 2024 
I can fix it

### Add ScreenShots

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/112798996/6c2a2805-8272-405f-9dc2-a7418d08efa2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by S-Siri** [comment]
Hi I would like to work on both login and register page, I have experience in MongoDB, I would like to fix that up.
I would request you to give me this issue under GSSOC'24.
Thank you.

**Comment by Anjankumarkamalapur** [comment]
#189 I'm really interested in making a dynamic login page because I have done this work previously in my National level Hackathon(winners) can you pls assign this work to me.
