### ISSUE TITLE
Carousel Item image

### ISSUE THREAD

**Issue by lakshyajn** [arghadipmanna101/Flipkart_Clone#19]
Hey, there is only one image in the mid section that is-->
<img class="d-block w-100" src="https://rukminim1.flixcart.com/fk-p-flap/1600/270/image/3351c6e7bf60c6bc.png?q=20" alt="Second slide">

I can add more, also correcting the positioning for arrows (if needed)

Please assign this issue to me :)

**Comment by arghadipmanna101** [comment]
sure....... Go ahead bro

**Comment by Ansh101112** [comment]
hello @arghadipmanna101 could you assign this issue to me?

**Comment by arghadipmanna101** [comment]
@Ansh101112  you will assign this issue after @lakshyajn  completes. ok

**Comment by Ansh101112** [comment]
Okay then no issues but still I will work on this issue and make a pr on it is it okay? Then you can compare the work of us too..

**Comment by arghadipmanna101** [comment]
> Okay then no issues but still I will work on this issue and make a pr on it is it okay? Then you can compare the work of us too..

Wait for tomorrow. I will assign you after tomorrow ok. let him complete @lakshyajn 's work.

**Comment by Ansh101112** [comment]
okay then

**Comment by DhruvJohri** [comment]
Hello @arghadipmanna101 
please assign this issue to me i could contribute
![Screenshot 2024-05-09 192115](https://github.com/arghadipmanna101/Flipkart_Clone/assets/111191087/f25c1e23-49d4-4785-8b30-7450e9b8f9f4)

**Comment by arghadipmanna101** [comment]
> Hello @arghadipmanna101 please assign this issue to me i could contribute ![Screenshot 2024-05-09 192115](https://private-user-images.githubusercontent.com/111191087/329271184-f25c1e23-49d4-4785-8b30-7450e9b8f9f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNjM4MDUsIm5iZiI6MTcxNTI2MzUwNSwicGF0aCI6Ii8xMTExOTEwODcvMzI5MjcxMTg0LWYyNWMxZTIzLTQ5ZDQtNDc4NS04YjMwLTc0NTBlOWI4ZjlmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOVQxNDA1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODA4ZTNjN2I5Njc1ZDgxOWMzMDE3Y2NmMDNjZTQ2NTg0NjQxMDM5ODVlYjM4ZjA4ZDIwYjNlNDczMzEwZmM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uz8buaeZ1pTjtkIGNdaj7JEQBiyuubhe3v08L326GcE)

@lakshyajn already assigned.

**Comment by parth3083** [comment]
I can fix the carousel using the gasp animation and make it more interactive

**Comment by arghadipmanna101** [comment]
ok. go ahead @parth3083

**Comment by Ansh101112** [comment]
@arghadipmanna101 sir what about me to assign this issue you said to assign me first??

**Comment by arghadipmanna101** [comment]
> @arghadipmanna101 sir what about me to assign this issue you said to assign me first??

Go ahead man. no issue... GO GO GO 😊

**Comment by Ansh101112** [comment]
Thanks so much sir. Sir should I commit after the events start that is 7pm or before too?

**Comment by arghadipmanna101** [comment]
as you wish.

> Thanks so much sir. Sir should I commit after the events start that is 7pm or before too?

**Comment by Ansh101112** [comment]
Thank you sir will work on more issues very soon.
