### ISSUE TITLE
lesser cards in the home page 

### ISSUE THREAD

**Issue by khushi-joshi-05** [arghadipmanna101/Flipkart_Clone#2]
Increase the number of cards on the homepage to enrich content diversity and enhance user engagement. I would like to solve this kindly assign.

**Comment by Jithendranath8** [comment]
please kindly assign this issue to me , i want to work on it

**Comment by arghadipmanna101** [comment]
@khushi-joshi-05  you have been assigned. Go ahead.

**Comment by Shyambarua** [comment]
Assign this issue to me 
As a full stack Developer i can write optimized code and responsive and i can integrate with backend also.
