### ISSUE TITLE
Updating the Navbar

### ISSUE THREAD

**Issue by shailifadadu** [arghadipmanna101/Flipkart_Clone#20]
I'm proposing an update to the navbar design to enhance its aesthetics and usability. This update will include improvements in color scheme, typography, layout, and responsiveness.

**Comment by shailifadadu** [comment]
@arghadipmanna101 Can u plz assign this issue to me!!

**Comment by arghadipmanna101** [comment]
sure. you have been assigned. go ahead and do you best.

**Comment by Harsh-Vardhan-Yadav-03** [comment]
Please , assign this  issue to me

**Comment by PoojaGadagi08** [comment]
Hello @arghadipmanna101 sir
I would like to work on this issue as a contributor to the GSSOC. please assign this to me!
I have relevant skills that definitely help to enhance the website.

**Comment by arghadipmanna101** [comment]
> Hello @arghadipmanna101 sir I would like to work on this issue as a contributor to the GSSOC. please assign this to me! I have relevant skills that definitely help to enhance the website.

which update you want to do? please explain

**Comment by chaanakyaaM** [comment]
Hello @arghadipmanna101 sir, I would like to improve the header, nav bar including the hover effect and also the time for transition of it, and make the header more interactive and smooth.

would you assign it to me under GSSoC ?

**Comment by sahithinandikula** [comment]
@arghadipmanna101 I have already worked on a similar kind of clone.  I can fix the issue . Kindly assign this issue to me

**Comment by Aayushi23jain** [comment]
@arghadipmanna101 Can u plz assign this issue to me!!
