### ISSUE TITLE
Feat: Social media handles at footer 

### ISSUE THREAD

**Issue by Ayush170803** [arghadipmanna101/Flipkart_Clone#200]
### Describe the feature

At Footer of the Page Social Media Handles are not redirecting to the mentioned handles so kindly provide the social media respective account website links to fix this issue. Kindly assign me this issue, so i can work towards it under GSSOC'24. Thank You

### Add ScreenShots

https://github.com/arghadipmanna101/Flipkart_Clone/assets/115927008/27b6db8f-3d3a-4478-994f-c4b3861d7885

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by say-het** [comment]
@arghadipmanna101 
Can you assign me this issue?

**Comment by NAVJOT-786** [comment]
@arghadipmanna101 please assign me this issue
