### ISSUE TITLE
Feat: Add a proper Header section with responsive navbar

### ISSUE THREAD

**Issue by AnirbanGhosh2** [arghadipmanna101/Flipkart_Clone#202]
### Describe the feature

- At header section the buttons are not properly organized 
- The responsiveness is also missing in the header section and navbar section .So, I can update the header section with proper responsiveness.
- Please assign me this under GSSOC'24 I will solve and make proper responsive the header section.

### Add ScreenShots

![1a](https://github.com/arghadipmanna101/Flipkart_Clone/assets/110912334/acc569f8-8295-4752-882d-0df6993947fb)
![2b](https://github.com/arghadipmanna101/Flipkart_Clone/assets/110912334/19289aaa-1a53-48f0-a396-83ff35fdd8b0)
![3c](https://github.com/arghadipmanna101/Flipkart_Clone/assets/110912334/00e88119-8d98-43b1-ab00-d09d390cd3fd)

- In this ss it is clearly visible that header section and the navbar is not properly responsive and also it is not showing same like the original.
- Please assign me this under GSSOC'24 so that i can solve this

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shmbhvi101** [comment]
hi please assign this task to me as i've previously worked on websites and i have a strong grasp on html, css, javascript

**Comment by DharshiBalasubramaniyam** [comment]
> hi please assign this task to me as i've previously worked on websites and i have a strong grasp on html, css, javascript

I the one developed the header. I made it to be responsive. @shmbhvi101 I think it's because of the footer.

**Comment by Saimanjari777** [comment]
Hi, 
The header section is not appealing, the hovering effect needs to be changed and the nav bar needs to be organized.
Please assign this task to me.
