### ISSUE TITLE
BUG: Why is there two arrow bars

### ISSUE THREAD

**Issue by Unalia09** [arghadipmanna101/Flipkart_Clone#204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There are two arrow bars one is blue and the other is white, the white one is functional but the blue one isn't and it's just there. 

![Screenshot 2024-05-11 170427](https://github.com/arghadipmanna101/Flipkart_Clone/assets/147930477/8ce8b309-a34d-4f00-a98d-8f695c3489b1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Anjankumarkamalapur** [comment]
#204 I interested in this work because I can fix this issue faster with good perfection.

**Comment by LordVaibhav** [comment]
I want to work on this issue please assign it to me.
