### ISSUE TITLE
Feat: making the landing page less clustered 

### ISSUE THREAD

**Issue by shmbhvi101** [arghadipmanna101/Flipkart_Clone#205]
### Describe the feature

The landing page is not pleasing to look at, hence i can give it a better appearance. 

### Add ScreenShots

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/156112383/4e2ecd85-c851-4bb4-9677-0ad022ddde7c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shmbhvi101** [comment]
Hey i have a strong grasp on html, css , javascript. please assign this issue to me as it'd be great for my Gssoc'24 journey!

**Comment by abhishek7088** [comment]
can u please assign this to me. i will make it more good looking and professional .it will be great for my Gssoc'24
