### ISSUE TITLE
Dropdown Misplacement ( profile and  three dots in right corner)

### ISSUE THREAD

**Issue by Hemav009** [arghadipmanna101/Flipkart_Clone#207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-05-11 173609](https://github.com/arghadipmanna101/Flipkart_Clone/assets/109607812/7b450a6a-223e-47c9-851d-460c2dda2994)

Hey @arghadipmanna101 

Currently, when I click on the profile icon, the dropdown menu appears beneath the navigation bar. This can be inconvenient as it can sometimes overlap with the content below the navigation bar, making it difficult to see the options clearly.i want to fix the issue Please assign me.

Thank you!

![Screenshot 2024-05-11 173617](https://github.com/arghadipmanna101/Flipkart_Clone/assets/109607812/fab17d7c-43fe-4a83-aa9f-8da4cc266829)

I want to create a effect like above img.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Anjankumarkamalapur** [comment]
#207  Dropdown Misplacement ( profile and thre dots in right corner)

**Comment by shnwz-solves** [comment]
Hey PA,  I would like to contribute to this project. Please assign this to me. Thankyou!
