### ISSUE TITLE
Feat: can i add some smartphones in Electronics < smartphone in the navbar section .

### ISSUE THREAD

**Issue by snehabansal670** [arghadipmanna101/Flipkart_Clone#209]
### Describe the feature

the smartphone page will consist of different phone with their specifications and a button ...... which can be further redirected to other landing page of final product 

### Add ScreenShots

![2024-05-11 18_10_50-Greenshot](https://github.com/arghadipmanna101/Flipkart_Clone/assets/144333741/aef21030-8a9c-4cf9-a74b-13e3f7e660f1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Tarani12** [comment]
I would like to work on this. Please assign me this issue
