### ISSUE TITLE
Feat:gift card page and  best deals part of the home page ...

### ISSUE THREAD

**Issue by CharviPalem** [arghadipmanna101/Flipkart_Clone#210]
### Describe the feature

I would like to build the gift card page UI and  the best deals part of the home page ...
sir please assign me the task .....
![Screenshot 2024-05-11 182621](https://github.com/arghadipmanna101/Flipkart_Clone/assets/145920684/f3453109-ee53-4d34-b408-ef3c8162e0d5)
(also initially i,ve added the categories list in the homepage and fixed the navbar)

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/145920684/5e97142f-b966-4ce1-b91a-8e35a0027dd4)

### Add ScreenShots

![Screenshot 2024-05-11 183438](https://github.com/arghadipmanna101/Flipkart_Clone/assets/145920684/a3b1521d-7456-4091-90c0-5550ec3a6cf1)
this is to be added

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shnwz-solves** [comment]
Hey PA, I want to contribute, please assign this issue to me. Thankyou!
