### ISSUE TITLE
Adding dynamic icons in navbar and footer with hover for eye catchy design

### ISSUE THREAD

**Issue by cxde-Sujal** [arghadipmanna101/Flipkart_Clone#211]
### Describe the feature

Adding icons in hover navbar and  footer that would be moving for eye catchy look
and adding changes on hover of that specified link
As we can see the navbar looks adjusted too and icons are common and static in the screenshot attached

### Add ScreenShots

![Screenshot (143)](https://github.com/arghadipmanna101/Flipkart_Clone/assets/137087363/9a1592a0-638c-48a1-b428-2d16197daf16)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by cxde-Sujal** [comment]
I am a contributor please assign it to me for GSSoc'24
@PRATHAMU200 @Dominic-SR @saswat733

**Comment by muskantanwar7** [comment]
I have previously completed similar tasks, so please consider giving me an opportunity; I assure you that I will not disappoint you. Please assign the task to me.

**Comment by Gokilp** [comment]
i will do it
