### ISSUE TITLE
title & icon of flip kart 

### ISSUE THREAD

**Issue by Sehar-Tahir** [arghadipmanna101/Flipkart_Clone#214]
### Describe the feature

There is no proper title & icon of Flip kart Website.

### Add ScreenShots

<img width="576" alt="title + name issue" src="https://github.com/arghadipmanna101/Flipkart_Clone/assets/165343808/7bd29236-e522-4687-a74d-36cef6414187">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Utkarsh7368** [comment]
Please assign this task to me

**Comment by Harshit279096** [comment]
we can change icon of flipkart into real one and also the title.
kindle assign this task to me.

**Comment by arghadipmanna101** [comment]
already solved

**Comment by Sehar-Tahir** [comment]
But still there is no proper icon & title of your project
