### ISSUE TITLE
Feat: Update Footer and add Logo and address

### ISSUE THREAD

**Issue by SahithiDevalla** [arghadipmanna101/Flipkart_Clone#215]
### Describe the feature

The footer is clumsy I can make it look attractive and add a address and Logo in footer like in main website

### Add ScreenShots

![Screenshot (47)](https://github.com/arghadipmanna101/Flipkart_Clone/assets/107240268/bc052548-5025-40cd-8d4c-a6a8b3af375b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by dubeyadarsh862** [comment]
please assign me this issue under GSSoC'24

**Comment by arghadipmanna101** [comment]
Already solved
