### ISSUE TITLE
Search bar need to be fixed

### ISSUE THREAD

**Issue by pranav-nani** [arghadipmanna101/Flipkart_Clone#22]
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/88759848/72909386-7c09-436f-9096-915309b97533)
The outline of the search bar need to be fixed.
**Assing this issue for me under GSSoC24**

**Comment by pranav-nani** [comment]
Thank u sir

**Comment by arghadipmanna101** [comment]
> Thank u sir

Call me using my name Arghdip or Bro. not sir bro...❤️

**Comment by PoojaGadagi08** [comment]
Hello @arghadipmanna101 sir
I would like to work on this issue as a contributor to the GSSOC. please assign this to me!
I have relevant skills that definitely help to enhance the website.

**Comment by arghadipmanna101** [comment]
Already solved .
