### ISSUE TITLE
BUG: Footer is not appealing

### ISSUE THREAD

**Issue by Shivangi015** [arghadipmanna101/Flipkart_Clone#220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The footer section is not good enough, the content are not styled properly in the footer. I can make a perfect footer section for this e-commerce website which will look more appealing.
Also I can work on responsiveness of the website and can fix the style of entire website.

### Record

- [X] I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by say-het** [comment]
@arghadipmanna101 
Can you assign me this issue? I have good experience in working with UI/UX and Frontend.

**Comment by Sehar-Tahir** [comment]
@arghadipmanna101 
kindly assign me this issue. I will improve the footer section.

**Comment by TanviGandhotra** [comment]
@arghadipmanna101 plzz assign this issue to me i will make it  look attractive

**Comment by Mohityadav3036** [comment]
@arghadipmanna101  sir please assign this issue to  me. i will definitely fix it and i will make a attractive footer for it. Currently i have made a footer for StudyNotion which is EdTech plateform. This is a demo for it:-
![demofooter](https://github.com/arghadipmanna101/Flipkart_Clone/assets/123181137/07a3e8f8-8f6e-4833-b9c5-35e70a0fd639)
