### ISSUE TITLE
Adding links to social media

### ISSUE THREAD

**Issue by Shivangi015** [arghadipmanna101/Flipkart_Clone#224]
### Describe the feature

The social media section is not responding to clicks. The links should be added to the social media icons to make them respond while user clicks the icons.
Also styling the icons with perfect size and position as required for this website.

### Add ScreenShots

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/115791035/15dee97e-6bf0-4a62-ab6d-e3471d582869)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Vikashchou-dhary** [comment]
hello ma'am i am interested to work on this issue. please assign it to me

**Comment by samadritabhaumik** [comment]
I would like to work on this issue.Please assign a task to me.

**Comment by yashwagh30** [comment]
Hello i am interersted to work on this issue. I try may best to improve the icon's design and will insert the links of following social media.
Thank you
And can you please add the labels of gssoc and levels

**Comment by Kkt04** [comment]
Hello there, please assign me this issue.. I want to resolve this issue

**Comment by arghadipmanna101** [comment]
Already solved
