### ISSUE TITLE
BUG: Removing unnecessary arrow.

### ISSUE THREAD

**Issue by Shivangi015** [arghadipmanna101/Flipkart_Clone#226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The arrow is not leading to any changes on the page. This is an unnecessary arrow created on the page which should be removed.
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/115791035/db6cbe91-7231-4497-91ac-f96525cadf66)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SahilThakur02** [comment]
Hey, I am a contributor at GSSOC, Can I be assigned this issue?
