### ISSUE TITLE
Feat: Improving the Navigation Bar UI  

### ISSUE THREAD

**Issue by AnandK-pm** [arghadipmanna101/Flipkart_Clone#228]
### Describe the feature

Improving the Navigation Bar UI  so that it will look more like the actual Flipkart website.
Currently the navigation bar has unnecessary hover effects and other issues which the actual Flipkart website doesn't posess.
Please assign me this task so that i can work on these issues. I'am confident that i can pull off this effectively.
( Requesting as a part of GSSoC '24 contribution )

### Add ScreenShots

![Screenshot 2024-05-11 195715](https://github.com/arghadipmanna101/Flipkart_Clone/assets/142206618/c2d0c76c-f815-4c2e-acfc-93d8eaed9f43)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aakrati14** [comment]
I will improve the navbar and will also add hover effects on the navbar and make the navbar responsive on all devices. I am eager to take on this task of improving our website's navigation bar to ensure responsiveness across all devices. Additionally, I'll focus on improving the hover effects of the navbar. This will improve the user experience and contribute positively to our website's overall aesthetics. Please assign me this task, and I'll work diligently to make valuable contributions.

-I have checked the existing issues *
-I have read the Contributing Guidelines *
-I have starred the repository *
-Working under Gssoc24*

**Comment by arghadipmanna101** [comment]
Already solved
