### ISSUE TITLE
Fixing the footer of the page with better UI

### ISSUE THREAD

**Issue by kairveeehh** [arghadipmanna101/Flipkart_Clone#23]
with my proficiency in css and animations I would like to fix the footer of the page , 

## please assign this issue to me as I have created the local repo already under gssoc'24
![Screenshot 2024-05-09 185350](https://github.com/arghadipmanna101/Flipkart_Clone/assets/145572028/35450e82-1241-4d0b-b883-801d907dc23e)

**Comment by arghadipmanna101** [comment]
go ahead. best of luck  @kairveeehh 🤞

**Comment by PoojaGadagi08** [comment]
Hello @arghadipmanna101 sir
I would like to work on this issue as a contributor to the GSSOC. please assign this to me!
I have relevant skills that definitely help to enhance the website.

**Comment by kairveeehh** [comment]
> go ahead. best of luck @kairveeehh 🤞

I have completed it and created a PR , please merge it :))

**Comment by LordVaibhav** [comment]
@arghadipmanna101 please assign this issue to me

**Comment by devansh2311** [comment]
I will improve and make the footer almost the same as in the flipkart's website page!
<h4>Please assign me this issue<h4>

**Comment by kairveeehh** [comment]
> I will improve and make the footer almost the same as in the flipkart's website page!
> <h4>Please assign me this issue<h4>
> @arghadipmanna101 

Bro you can see the issue was assigned already and has been merged even ...so you should raise smt else

**Comment by devansh2311** [comment]
> > I will improve and make the footer almost the same as in the flipkart's website page!
> > <h4>Please assign me this issue<h4>
> > @arghadipmanna101 
> 
> Bro you can see the issue was assigned already and has been merged even ...so you should raise smt else 

Its my first time with open source, so didn't know much about it.. Will take care of this from next time😀

**Comment by kairveeehh** [comment]
> > > I will improve and make the footer almost the same as in the flipkart's website page!
> > > <h4>Please assign me this issue<h4>
> > > @arghadipmanna101 
> > 
> > Bro you can see the issue was assigned already and has been merged even ...so you should raise smt else 
> 
> Its my first time with open source, so didn't know much about it.. Will take care of this from next time😀

Yes same for me ...so advised taaki you don't end up wasting time , what i have observed is mentors assign the raised issues mostly to the person who raised them..( saw it in 3 projects) so yess , and best of luck to us 🥰

**Comment by chaanakyaaM** [comment]
Hello @arghadipmanna101 I can make the exact replica of this footer, including the responsiveness, hover effect, with transition.

![Screenshot (194)](https://github.com/arghadipmanna101/Flipkart_Clone/assets/131477601/e3cf249b-9cf3-432c-ab47-2902e4e94903)

would you assign me to it ??
