### ISSUE TITLE
Feat: Improving the nav bar and making it look more similar to the actual flipkart website

### ISSUE THREAD

**Issue by SalehaTabassum** [arghadipmanna101/Flipkart_Clone#239]
### Describe the feature

I found that the nav bar of this clone not much good ..I would like to create a nav bar which looks much similar to actual flipkart website. The search bar is aligned to the left i would like to fix it make the nav bar look better.
Please assign this issue to me under GSSOC 2024 @arghadipmanna101 

### Add ScreenShots

![Screenshot 2024-05-11 225550](https://github.com/arghadipmanna101/Flipkart_Clone/assets/169278740/db522652-1c00-4ef1-adff-c142a99d07d4)

This is the current nav bar of clone

![Screenshot 2024-05-11 225708](https://github.com/arghadipmanna101/Flipkart_Clone/assets/169278740/f4479982-c279-45b9-ba6e-d35ace08a146)

as u can see there is a huge difference in the actual one and clone ...i would like make the nav bar look more good

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SalehaTabassum** [comment]
@arghadipmanna101 please assign this issue to me under gssoc 24

**Comment by TanviGandhotra** [comment]
@arghadipmanna101 plz assign this isssue to me .wanted to work on this. will improve it

**Comment by SalehaTabassum** [comment]
@arghadipmanna101 can u add the labels for this issue
