### ISSUE TITLE
hover effect on navbar items

### ISSUE THREAD

**Issue by Sehar-Tahir** [arghadipmanna101/Flipkart_Clone#242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is no proper hovering effect in the nav bar . It needs an improvement ...

kindly assign me this issue as I already created the nav bar for website like amazon.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Gokilp** [comment]
please assign me

**Comment by Gokilp** [comment]
i working on issue
