### ISSUE TITLE
Feat: Changing the font style and the background

### ISSUE THREAD

**Issue by Kumud14** [arghadipmanna101/Flipkart_Clone#249]
### Describe the feature

The font style used and the images are not fascinating. They need to be improved to attract people.

### Add ScreenShots

![WhatsApp Image 2024-05-12 at 00 12 24](https://github.com/arghadipmanna101/Flipkart_Clone/assets/118610013/2dd4ef74-4f9b-4f04-8eda-fe01cd41f2db)
the front page need to be fixed and the picture font combo is not at all matching.

### Record

- [X] I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Artuiro-23** [comment]
Kindly provide me this task. Thanyou.

**Comment by Komalpreet-Kaur112** [comment]
Hey @arghadipmanna101 
Please assign this issue to me.

**Comment by Kumud14** [comment]
@arghadipmanna101 Thankyou
