### ISSUE TITLE
Swiper is not working in car carousel.html page

### ISSUE THREAD

**Issue by suraj-9849** [arghadipmanna101/Flipkart_Clone#25]
I would like to work on this. I will be using the swiper.js for this .This can help the images move. So can you please assign this to me under @GSSOC'24 @arghadipmanna101

**Comment by arghadipmanna101** [comment]
sure. go ahead @suraj-9849

**Comment by suraj-9849** [comment]
yeah sir the jqeury which is present in the index.html is making the problem I made the changes and included the carousel.html code in the index.html it is working perfectly but when I am keeping the code in the carousel.html it is not working. So what should I do! @arghadipmanna101

**Comment by arghadipmanna101** [comment]
ok. keep it in the index.html file

**Comment by suraj-9849** [comment]
I also added the auto play feature in it sir Thank you for assigning this work to me @arghadipmanna101  sir. I loved to work with this project.

**Comment by suraj-9849** [comment]
https://github.com/arghadipmanna101/Flipkart_Clone/assets/146669517/46a053c8-b7f5-4820-bda2-7fd86c57e1b5

**Comment by arghadipmanna101** [comment]
solve it @suraj-9849
