### ISSUE TITLE
BUG: Carousel is not working properly

### ISSUE THREAD

**Issue by HimankPatidar** [arghadipmanna101/Flipkart_Clone#259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The carousel on website is not working properly and image size is also not proper and there are extra two arrow which are unnecessary and also it is unresponsive
![Screenshot 2024-05-12 010949](https://github.com/arghadipmanna101/Flipkart_Clone/assets/87924614/80acfe6e-9f45-4734-be19-8f5a0d8580c0)
![Screenshot 2024-05-12 011010](https://github.com/arghadipmanna101/Flipkart_Clone/assets/87924614/3642b0dc-d588-4663-8cbb-8d4b628d9d92)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by M-ayank2005** [comment]
Worked on similar issue in one more project. Can you assign me this issue.
