### ISSUE TITLE
BUG: Images at the footer section are not visible

### ISSUE THREAD

**Issue by achlbatra** [arghadipmanna101/Flipkart_Clone#260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The images beside visa and MasterCard are not visible on the webpage. I would like to work on this issue under GSSOC'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by supersaif08** [comment]
As the images in the footer are not available in the file and it's also not displaying in the web page. 
I would like to work on it.
please assign it to me.

**Comment by achlbatra** [comment]
I think I should be assigned this issue as I raised it

**Comment by Khushiirani25** [comment]
@arghadipmanna101 please assign me this issue under GSSOC'24. i would update the images and make the necesssary changes if required.

**Comment by achlbatra** [comment]
Sorry but It is already assigned to me.

**Comment by newcodergit** [comment]
I would like to work on this project. Please assign it to me.
