### ISSUE TITLE
Hovering ,Icons and ToolTip Issues Navbar Items :

### ISSUE THREAD

**Issue by shreya7710** [arghadipmanna101/Flipkart_Clone#265]
![Screenshot 2024-05-12 035028](https://github.com/arghadipmanna101/Flipkart_Clone/assets/156280163/9c88496d-4b2e-48a2-ae69-e1202c65cc97)

 This is the original website and attached below is clone need to be improved because it lacks these functionalities.

1. Almost every feature has TOOLTIP generated with it and appears on hovering.
2. Few button or items of nav bar beside search bar opens its related dialog box just by hovering onto it but here it is a need to click items.
2 .Login button on hovering turns blue.
3. Every dialog box of nav bar container has dialog box showing  icons related to its related fields.
4. On hovering nav items looks like hyperlinks but and this should not be there.
5. Search Bar on hovering does not give any effect in original webpage but here it shows corners around search bar.

![Screenshot 2024-05-12 034051](https://github.com/arghadipmanna101/Flipkart_Clone/assets/156280163/a4b88eb8-78c2-47dc-9436-ecb6a1eccef6)
![Screenshot 2024-05-12 035056](https://github.com/arghadipmanna101/Flipkart_Clone/assets/156280163/2ea37f8e-39c4-4ff4-bd11-305c74597a70)

I request the project admin to kindly give me an opportunity to contribute in this project to improvise it by adding the lacking functionalities.

**Comment by TanviGandhotra** [comment]
i have done this type of task plzz assign me this issue .looking forward for ur response , enthusiatic to contribute in this
