### ISSUE TITLE
BUG: Content alignment

### ISSUE THREAD

**Issue by dishathakurata** [arghadipmanna101/Flipkart_Clone#267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

OnePlus phone box is not aligned with other phone boxes
![oneplus](https://github.com/arghadipmanna101/Flipkart_Clone/assets/146114938/ace4b789-deec-4c8e-8086-4317e4ae00fe)

I already fixed it, please assign me with this issue under GSSoC '24 first so that I can create a PR.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by dishathakurata** [comment]
@arghadipmanna101 
I created a PR #306 fixing this issue
Kindly review that

**Comment by YashkShrivas4491** [comment]
LGTM @arghadipmanna101 check this out

**Comment by ananyag309** [comment]
Hi, I hope this message finds you well.

I am writing to express my interest in contributing to the issue. I am enthusiastic about participating in GSSoC'24 and believe that working on this issue will allow me to make a meaningful contribution to the project.

Could you please assign this issue to me under GSSoC'24?

Thank you for considering my request.

**Comment by YashkShrivas4491** [comment]
> Hi, I hope this message finds you well.
> 
> I am writing to express my interest in contributing to the issue. I am enthusiastic about participating in GSSoC'24 and believe that working on this issue will allow me to make a meaningful contribution to the project.
> 
> Could you please assign this issue to me under GSSoC'24?
> 
> Thank you for considering my request.

you can create new issue because this issue-related PR has already merged ok
