### ISSUE TITLE
Feat: Add Mobile Phones Images

### ISSUE THREAD

**Issue by i-am-faith** [arghadipmanna101/Flipkart_Clone#272]
### Describe the feature

I want to add some popular Mobile Phones Images in Electronic section. 

### Add ScreenShots

Just like this ->
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/98275372/1e350364-ba40-4554-b5e1-fede1095d4f0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by i-am-faith** [comment]
Assign this issue to me @arghadipmanna101

**Comment by govinddwivedigit** [comment]
Can you please assign this issue to me ?

**Comment by DhruvJohri** [comment]
please assign this issue to me @arghadipmanna101
