### ISSUE TITLE
Feat: Enhance the navbar styling

### ISSUE THREAD

**Issue by ayush-848** [arghadipmanna101/Flipkart_Clone#274]
### Describe the feature

I can make the text highlighted on hover and do the shadowing effect in a more better way.

### Add ScreenShots

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/126975547/971a5b74-5483-42cf-af9c-4ffb42bb802c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ayush-848** [comment]
Please assign this issue to me

**Comment by yash21sriv** [comment]
please assign this issue to me under gssoc

**Comment by Suruchibharti** [comment]
hii! @arghadipmanna101  ,
I'm GSSoC'24 contributor , I have experienced on HTML, CSS, JS, and react.js , so I want to work on this issue,
so, kindly requested to you to assign me the task.

**Comment by ayush-848** [comment]
@arghadipmanna101 can you please tell me on which file is this content located?

**Comment by arghadipmanna101** [comment]
Check it you.

**Comment by ayush-848** [comment]
@arghadipmanna101 I have done the styling. Please check.

**Comment by ayush-848** [comment]
@arghadipmanna101 I've applied styling to the navbar items to enhance its appearance and readability.

**Comment by ayush-848** [comment]
@arghadipmanna101 Please check my PR #298
