### ISSUE TITLE
Missing CONTRIBUTING.md File in Repository 

### ISSUE THREAD

**Issue by suhanipaliwal** [arghadipmanna101/Flipkart_Clone#280]
The repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

Could you please assign this issue to me under GSSOC 24.

**Comment by suhanipaliwal** [comment]
Could you please add the label of appropriate level like level 1, 2 or 3 for GSSOC'24.

**Comment by ananyag309** [comment]
Hi, I hope this message finds you well.

I am writing to express my interest in contributing to the issue. I am enthusiastic about participating in GSSoC'24 and believe that working on this issue will allow me to make a meaningful contribution to the project.

Could you please assign this issue to me under GSSoC'24?

Thank you for considering my request.
