### ISSUE TITLE
BUG: Footer is not looking good

### ISSUE THREAD

**Issue by abhishekpathak4860** [arghadipmanna101/Flipkart_Clone#281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello sir ,I want to tell you that the footer part of your website is not looking so attractive .The size of the footer is too big on the home page and some of the content is going out of the screen .The color of the icons is also not same as the original one , also I want to change the font of the footer . So basically I want to work on the footer part of your website.

So please assign me the issue .
Thank you 

### Record

- [X] I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC'24 contributor
- [x] I want to work on this issue

**Comment by aryanmehra0** [comment]
@arghadipmanna101 @abhishekpathak4860 Hii my self raj aryan and i'm intrested in your given issue please assign this to me.....

**Comment by SAURABH-CHAMOLI** [comment]
@arghadipmanna101 
Hello sir , The font size of footer section is quite small as compared to the footer size and also it is not looking good .

So can you please assign me this issue.
Thank you

**Comment by Saloni-Kerketta** [comment]
hello sir , I am interested in it ,please assign it to me.

**Comment by abhishekpathak4860** [comment]
Hello sir , I want to tell you that I have changed the footer part and now
it is looking nice . I have made the pull request you can check it out and
I request to please merge it .
