### ISSUE TITLE
BUG: logo is not working properly in payment section 

### ISSUE THREAD

**Issue by Vedant285** [arghadipmanna101/Flipkart_Clone#284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot_2024-05-12-14-26-19-300_com android chrome](https://github.com/arghadipmanna101/Flipkart_Clone/assets/91669901/70b84b0c-e644-47d5-b9b7-9f7a7a6a765d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by jilupatel** [comment]
I would like to work on the issue. Please assign this task to me.
