### ISSUE TITLE
Adding a payment gateway

### ISSUE THREAD

**Issue by Rajguresiddhesh** [arghadipmanna101/Flipkart_Clone#287]
hello, @arghadipmanna101 I am gssoc'24 contributor. Could you please assign me this task  for adding a payment gateway in this flipkart clone

**Comment by SantoshiVerma** [comment]
Is there an existing issue for this?
 I have searched the existing issues

So , please assign me this issue @arghadipmanna101 and I will fix it.

Record
 I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue
