### ISSUE TITLE
Fixing the login icon 

### ISSUE THREAD

**Issue by shuhaki** [arghadipmanna101/Flipkart_Clone#29]
![WhatsApp Image 2024-05-09 at 19 50 56](https://github.com/arghadipmanna101/Flipkart_Clone/assets/145912232/9a588c09-ca66-47a6-bcd4-3d31ebb63bf1)

i want working of this issue, please assign me

**Comment by arghadipmanna101** [comment]
> ![WhatsApp Image 2024-05-09 at 19 50 56](https://private-user-images.githubusercontent.com/145912232/329276671-9a588c09-ca66-47a6-bcd4-3d31ebb63bf1.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNjUwMzQsIm5iZiI6MTcxNTI2NDczNCwicGF0aCI6Ii8xNDU5MTIyMzIvMzI5Mjc2NjcxLTlhNTg4YzA5LWNhNjYtNDdhNi1iY2Q0LTNkMzFlYmI2M2JmMS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDlUMTQyNTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjIwODI3ZDcxZWQxMzg4NmYzODkxMDRkZTZhZTI1NjM2NGI4MWE5NzM5YzU2OWQ1Y2YwZTNiOTZmNjBjMzEzZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nrarc4WYq4zg5RFnJybzNV7r6cCCUHThHsR6dejGTaM)
> 
> i want working of this issue, please assign me

sure. go ahead @shuhaki

**Comment by Gokilp** [comment]
Assign this issue to me under GSSoc'24 so that i can work on it

**Comment by arghadipmanna101** [comment]
@shuhaki  already assigned.


> Assign this issue to me under GSSoc'24 so that i can work on it

**Comment by SyedImtiyaz-1** [comment]
can you please assign me this issue ?

**Comment by aashkaaaaaa** [comment]
i want working of this issue, please assign me

**Comment by Madhusri02** [comment]
I can work on this issue so kindly assign me this task..

**Comment by gundellyvamshiyadav** [comment]
i would like to work on this issue
