### ISSUE TITLE
Feat: Fixing top deals section and adding new sections on store

### ISSUE THREAD

**Issue by Ansh101112** [arghadipmanna101/Flipkart_Clone#295]
### Describe the feature

Need to fix the UI desgin of top deal section and will add more section on webpage too. @arghadipmanna101 please assign the isssue to me

### Add ScreenShots

![Screenshot (69)](https://github.com/arghadipmanna101/Flipkart_Clone/assets/87803348/d4f0ae23-e795-4548-bd47-041cd2984999)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ansh101112** [comment]
@arghadipmanna101 the pr #300 resolving this issue please see.

**Comment by Shristi613** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue

**Comment by Ansh101112** [comment]
>  I agree to follow this project's Code of Conduct
>  I'm a GSSOC'24 contributor
>  I want to work on this issue

Already done see pr #300
