### ISSUE TITLE
BUG: The download button is not working

### ISSUE THREAD

**Issue by Saimanjari777** [arghadipmanna101/Flipkart_Clone#299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The download button in the header section is not working. I will link it to the playstore psge. 
Please assign this task to me. I want to do this. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Divi-1026** [comment]
please assign this to me !!
