### ISSUE TITLE
Redundant Content in the Footer Section

### ISSUE THREAD

**Issue by debolinaSaha** [arghadipmanna101/Flipkart_Clone#3]
Hello! 
While going through your website, I noticed that there is redundant (or repeated content) appearing across multiple sections of the footer on the website (especially in the ABOUT US, HELP, CONSUMER POLICY, ADDRESS and CONTACT US sections of the page). 

I suggest reviewing and refining the footer content in order to avoid confusion arising from the same.

I've attached screenshots for reference. 

![Flipkart - Google Chrome 09-05-2024 00_15_28](https://github.com/arghadipmanna101/Flipkart_Clone/assets/147256841/f1737901-e036-44f5-b4bd-96254dcd27cb)

![WhatsApp Image 2024-05-09 at 00 21 19](https://github.com/arghadipmanna101/Flipkart_Clone/assets/147256841/120e7ff2-1eb6-4a05-b540-10d53c500358)

I would like to work towards solving this issue for better usability. Thank You!

**Comment by bhavanishanker-png** [comment]
i would like to work on this project please this to me

**Comment by arghadipmanna101** [comment]
@debolinaSaha go ahead.
