### ISSUE TITLE
Adding Content to the pages about products

### ISSUE THREAD

**Issue by sshivangi882** [arghadipmanna101/Flipkart_Clone#30]
The pages seem to be empty let me add the products and their details.

**Comment by arghadipmanna101** [comment]
sure. go ahead @sshivangi882 .

**Comment by Gokilp** [comment]
Assign this issue to me under GSSoc'24 so that i can work on it

**Comment by arghadipmanna101** [comment]
@Gokilp go ahead 👍

**Comment by arghadipmanna101** [comment]
> please assigned me to add product details

assigned

**Comment by Kashish0047** [comment]
I want to add products to this section. Can i make changes?

**Comment by princyym** [comment]
Hello, I am eager to work on this project, could you please assign me @sshivangi882
