### ISSUE TITLE
Feat: Redesign the footer section

### ISSUE THREAD

**Issue by tyagismriti** [arghadipmanna101/Flipkart_Clone#305]
### Describe the feature

The footer section is not looking good I want to make changes in this section and apply some flex properties to position it correctly. Please assigned me this issue @arghadipmanna101 

### Add ScreenShots

![Screenshot (4)](https://github.com/arghadipmanna101/Flipkart_Clone/assets/130198645/ed5e998c-f9c6-472f-88a5-fee450fa21ff)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by siddub306** [comment]
Please assign me this issue sir

**Comment by Harshiacchu** [comment]
I’m harshitha and I’m good with web development. I would love to be assigned with this issue and would def make a better footer

**Comment by Dev-AyushTrivedi** [comment]
I’ve noticed that the footer section could use some improvements for better aesthetics and functionality. I would like to apply some flex properties to enhance its positioning. Could you please assign this issue to me.....

**Comment by pujakulkarni** [comment]
The footer is not look appealing . To make more attractive we can divide the footer into clear section using flex box properties . I would like to work on this section . please assign this issue to me ....@arghadipmanna101

**Comment by ananyag309** [comment]
Hi, I hope this message finds you well.

I am writing to express my interest in contributing to the issue. I am enthusiastic about participating in GSSoC'24 and believe that working on this issue will allow me to make a meaningful contribution to the project.

Could you please assign this issue to me under GSSoC'24?

Thank you for considering my request.

**Comment by riiyanegii** [comment]
Hi @arghadipmanna101 ,
I hope you're doing well. 
I want to make changes to the footer section and redesign it to make it look more user friendly, functioning and aesthetic looking, 
could you please assign this issue to me?
Thank you for your consideration.
