### ISSUE TITLE
Feat: Adding a favicon icon

### ISSUE THREAD

**Issue by tyagismriti** [arghadipmanna101/Flipkart_Clone#307]
### Describe the feature

Fevicon icon of flipkart is missing. Please assign me this task @arghadipmanna101 

### Add ScreenShots

![Screenshot (5)](https://github.com/arghadipmanna101/Flipkart_Clone/assets/130198645/80a9864e-2090-4494-b7e5-998ebdfca5a1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by tara122333** [comment]
Can you assign this task to me?
