### ISSUE TITLE
Google authentication feature_Feat:

### ISSUE THREAD

**Issue by Meetjain1** [arghadipmanna101/Flipkart_Clone#314]
### Describe the feature

I will add google authentication in the signup , sign page . To enable the user to login or signup easliy.
@arghadipmanna101 sir , please assign this issue to me I will add it . Thankyou 

### Add ScreenShots

![signup](https://github.com/arghadipmanna101/Flipkart_Clone/assets/133582566/0533659d-0d07-4530-9607-28d74d67182d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harihara04sudhan** [comment]
Hi @arghadipmanna101  sir,

I'm interested in contributing to Flipkart_Clone. While the Google authentication issue is assigned, I'd like to work on implementing social media authentication options for signup and login. Could you please consider assigning me this task?

Thank you!
