### ISSUE TITLE
Product cards in products section are improper

### ISSUE THREAD

**Issue by Sathya-reddy1658** [arghadipmanna101/Flipkart_Clone#32]
The cards in the product section are looking odd and the text needs alignment and proper styling like border, margin , padding is required and image needs to properly adjusted to fit the div , its was supressed to the left

assign me this issue and I'll make it look it great!!
thank you!!

**Comment by Gokilp** [comment]
assign to me

**Comment by arghadipmanna101** [comment]
Go ahead guys

**Comment by Shyambarua** [comment]
Assign this issue to me 
As a full stack Developer i can write optimized code and responsive and i can integrate with backend also.

**Comment by arghadipmanna101** [comment]
go ahead @Shyambarua

**Comment by Gokilp** [comment]
im started to working the issue  please assign me

**Comment by Gokilp** [comment]
Thank you so much

**Comment by amitkumar2308** [comment]
hey! can you assign me this project to make my contibution in this

**Comment by Shyambarua** [comment]
issue has been solved 
from this
![Screenshot 2024-05-11 121247](https://github.com/arghadipmanna101/Flipkart_Clone/assets/138357317/02a1ff90-8d46-4015-a8b4-4fa9c3987f0f)

to this

![Screenshot 2024-05-11 120635](https://github.com/arghadipmanna101/Flipkart_Clone/assets/138357317/61193bc3-66bc-498b-999a-83deb5f1757f)

**Comment by arghadipmanna101** [comment]
> issue has been solved from this ![Screenshot 2024-05-11 121247](https://private-user-images.githubusercontent.com/138357317/329760992-02a1ff90-8d46-4015-a8b4-4fa9c3987f0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MTE3MjAsIm5iZiI6MTcxNTQxMTQyMCwicGF0aCI6Ii8xMzgzNTczMTcvMzI5NzYwOTkyLTAyYTFmZjkwLThkNDYtNDAxNS1hOGI0LTRmYTljMzk4N2YwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwNzEwMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDlmNWZiMGZlMTMxNGZiNjE4OWI4Y2QyMmQwMmM3MzFhNjY1ZmZhNDgwZDU0MmM5YzEwYTYyZjgwNTMwOTc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XZ0SHLQuMd1eWz2YV1pryOhnzyp-YU2VfBBEYL2Q_H8)
> 
> to this
> 
> ![Screenshot 2024-05-11 120635](https://private-user-images.githubusercontent.com/138357317/329761007-61193bc3-66bc-498b-999a-83deb5f1757f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MTE3MjAsIm5iZiI6MTcxNTQxMTQyMCwicGF0aCI6Ii8xMzgzNTczMTcvMzI5NzYxMDA3LTYxMTkzYmMzLTY2YmMtNDk4Yi05OTlhLTgzZGViNWYxNzU3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQwNzEwMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjEzODIzMmIxODIzMmM5NmIwZGY5N2E3MzAzNmNjZWM2YTA5MDhhNGIwNDQ2YjBlZTM1M2I0NTM1NGFiOWM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IsOCGdAp7u7X6fjiNxt6KT65aUoBL5khRBazAYhhjI8)

Make a PR

**Comment by Shyambarua** [comment]
@arghadipmanna101 PR applied

**Comment by Gokilp** [comment]
Any working on the issue
