### ISSUE TITLE
Contact us 

### ISSUE THREAD

**Issue by Vaibhav0-07** [arghadipmanna101/Flipkart_Clone#320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the footer section the contact us page is not opening. I'll make a contact us page that open if the user tap on the contact us by which we can take users data and feedback regarding product or any issues . So please assign me this task

Uploading VID20240512181044.mp4…

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Vaibhav0-07** [comment]
Assign me this task I'll do it in the best way I can .

**Comment by Vaibhav0-07** [comment]
@arghadipmanna101 assign me this task I'll do it in the best and efficient way I can.

**Comment by Alokita004** [comment]
Please assign this task to me i 'll do it properly.

**Comment by Suvendu-UI** [comment]
plss assign me this issue

**Comment by Vaibhav0-07** [comment]
i completed this task and facing some issues and want some info like how i can push changes to the original one .
