### ISSUE TITLE
BUG: Navbar hover was not design properly.

### ISSUE THREAD

**Issue by sahiljarngal** [arghadipmanna101/Flipkart_Clone#323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The navbar link overlaps while hovering over it which looks very unprofessional.
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/97387822/f4964abe-1794-4593-8123-2fef70a59bf8)
So , please assign me this issue @arghadipmanna101 and I will fix it.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Dharmi-dev** [comment]
I am a fresh GSSOC'24 Contributor
I want to solve this problem of navbar links overlapping for you
I will not disagree you from my work
