### ISSUE TITLE
Drop-down in the grocery, electronic, clothing, home & furniture, beauty, travel and sports & stationery 

### ISSUE THREAD

**Issue by Vaibhav0-07** [arghadipmanna101/Flipkart_Clone#324]
### Describe the feature

I can add a drop-down in the sections i mentioned about which will look more good in the website and make it interactive and also can fix the bug in footer section that is the social media platforms links are not working. 

### Add ScreenShots

Uploading VID20240512182419.mp4…

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SadiyaTahsin29** [comment]
I request that you assign me this  following task. i would like to make contribution
