### ISSUE TITLE
Add features to Navbar .

### ISSUE THREAD

**Issue by prernasharma28** [arghadipmanna101/Flipkart_Clone#328]
### Describe the feature

Currently navbar has three features . Addition  of more features to it would  be an add-on to the website. 

Please assign this issue to me . 

### Add ScreenShots

![Screenshot (195)](https://github.com/arghadipmanna101/Flipkart_Clone/assets/159785240/85a047e1-9036-4c30-90ed-c5adcace433f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [x] I want to work on this issue

**Comment by prernasharma28** [comment]
Please assign this issue to me .

**Comment by madanmishra19** [comment]
> Please assign this issue to me .

I'll check issue and i try to do right.

**Comment by SantoshiVerma** [comment]
hey @arghadipmanna101 ,I am gssoc'24 contributor. Could you please assign me this task for adding the features  to navbar in this flipkart clone.

**Comment by kesava23** [comment]
Hi I would like to work on this issue under GSSOC . Please assign this to me
