### ISSUE TITLE
Feat: Back to top button

### ISSUE THREAD

**Issue by tat-tvam-asii** [arghadipmanna101/Flipkart_Clone#338]
### Describe the feature

A button in the footer section by clicking which we will directly go the the top of the webpage

### Add ScreenShots

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/143332267/4bd3d114-3289-4c9a-8f69-3079bdb79e52)
Like here on this website

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by tat-tvam-asii** [comment]
@arghadipmanna101  Please assign this issue to me under GSSOC'24

**Comment by khushi-chokshi-16** [comment]
I can help you with this problem, please assign me this issue.

**Comment by AnujaG1** [comment]
I can solve this issue could you please assign me.
