### ISSUE TITLE
BUG: Search Bar 

### ISSUE THREAD

**Issue by surya1926** [arghadipmanna101/Flipkart_Clone#339]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

While hovering on to the search bar in the right side of nav bar  it was hovering above the logo and same issue with "Become a Seller"  which looks odd sir,
please assign me these work i will work on it.
![Screenshot 2024-05-12 224257](https://github.com/arghadipmanna101/Flipkart_Clone/assets/110684511/6c56243f-4917-4a7b-9830-c1cbd969e8e2)

![Screenshot 2024-05-12 224652](https://github.com/arghadipmanna101/Flipkart_Clone/assets/110684511/236f29ac-2b45-45f9-bf47-d21e0c14e194)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Alokita004** [comment]
Hello sir i think if someone looking a website / app the user always  want that should be user friendly and as a developer we should make that much user friendly and our designing should me more perfect and attractive but in this issue  the search bar in the right side of nav bar it was hovering above the logo and same issue with "Become a Seller" which looks odd sir, so please assign this issue i want to work on this more proficient way.
