### ISSUE TITLE
Missing Social links_BUG:

### ISSUE THREAD

**Issue by Meetjain1** [arghadipmanna101/Flipkart_Clone#343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Social Links are missing in the footer section , @arghadipmanna101 Assign this issue to me I will add the links . Thankyou

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by arghadipmanna101** [comment]
Already solved

**Comment by Meetjain1** [comment]
OK sir

**Comment by Meetjain1** [comment]
@arghadipmanna101 but I cant find any social links in the footer section sir , Only Icon is present link is not there that is on clicking social media icon in our website , The respective social media handles are not opening . I request you to please check it once Thankyou .
