### ISSUE TITLE
BUG: Drop Down in Nav Bar

### ISSUE THREAD

**Issue by surya1926** [arghadipmanna101/Flipkart_Clone#344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Top right side in the nav bar there is an three dots in that drop down there is an issue while Hovering on it the blue was coming under it for "Profile" and "cart" and also while hovering on the above features like 24x7, notification, advertise, Download app. the background color was not appearing properly  which looks very unprofessional .

![Screenshot 2024-05-12 230042](https://github.com/arghadipmanna101/Flipkart_Clone/assets/110684511/2926ec0b-42e8-4521-b3b7-6b38955e5f23)
![Screenshot 2024-05-12 230803](https://github.com/arghadipmanna101/Flipkart_Clone/assets/110684511/e35816a8-1b8f-4dc6-9f06-0bf00745e6df)
![Screenshot 2024-05-12 230812](https://github.com/arghadipmanna101/Flipkart_Clone/assets/110684511/35d4edf1-4022-4fbd-80de-a9b16730c07b)
![Screenshot 2024-05-12 230828](https://github.com/arghadipmanna101/Flipkart_Clone/assets/110684511/bb7b021d-5123-430f-bc2b-3f080feef50f)
So , please assign me this issue @arghadipmanna101 and I will fix it

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Kiran-pro2001** [comment]
Kindly assign me the above issue, I am beginner into this, I will definitely gonna solve this issue.
