### ISSUE TITLE
Feat: Profile page is missing

### ISSUE THREAD

**Issue by kanishka-parmar** [arghadipmanna101/Flipkart_Clone#347]
### Describe the feature

The profile page is missing. When I click on the profile on the navbar it does not show anything. 
I would like to add the profile page. I would like to contribute this under GSSOC 2024.

### Add ScreenShots

![Screenshot 2024-05-12 235330](https://github.com/arghadipmanna101/Flipkart_Clone/assets/114792553/c5a81cad-2431-4593-8701-b78c24d94ff0)
![Screenshot 2024-05-12 235304](https://github.com/arghadipmanna101/Flipkart_Clone/assets/114792553/e07fb027-e103-4b64-8766-42a6780481f1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kanishka-parmar** [comment]
Thanks @arghadipmanna101 for assigning me I will start working on it.

**Comment by 21VV1A0541SAILU** [comment]
i want to work on this issue and add an profiel page

**Comment by 21VV1A0541SAILU** [comment]
Profile Page missing

https://github.com/arghadipmanna101/Flipkart_Clone/assets/101045793/7955d3bf-b238-4fb7-8119-cbe0f465bfd7

when I am clicking on the profile i was not able to see anykind of information regarding the user or seller,so I want to work on it.

I am GSSOC'24 Contributor
I want to work on this issue

**Comment by kanishka-parmar** [comment]
@arghadipmanna101 hey you assigned me the task of adding profile page but as i can see someone has already added it. How can you allow that?

**Comment by kanishka-parmar** [comment]
@arghadipmanna101 should i do changes in that one or make commit of what i have worked on?

**Comment by 21VV1A0541SAILU** [comment]
Sorry I haven't checked it

**Comment by kanishka-parmar** [comment]
> Sorry I haven't checked it

You have made the profile page ?
