### ISSUE TITLE
BUG: The hover of the profile and automatic movement of the big-offer banner is not there.

### ISSUE THREAD

**Issue by Unknownmaster0** [arghadipmanna101/Flipkart_Clone#352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When we go to the big-offer banner below the nav-bar then it should ideally slide automatically like the below one. But it is not working.
![Screenshot 2024-05-13 003336](https://github.com/arghadipmanna101/Flipkart_Clone/assets/117724228/7c699755-01b3-4b41-8835-0844c5d7b2ef)
And one more thing, the hover option should also be provided on the profile button in the nav bar. 

Kindly assign this task to me to do the further update.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Unknownmaster0** [comment]
Hii, PA kindly assign this to me .

**Comment by Unknownmaster0** [comment]
add the label too.

**Comment by arghadipmanna101** [comment]
Already solved
