### ISSUE TITLE
BUG: Category list is actually hiding behind header bar.

### ISSUE THREAD

**Issue by kuritika098** [arghadipmanna101/Flipkart_Clone#356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

As we can we , here is a bug . As category list is not showing perfectly.
![Screenshot 2024-05-13 011834](https://github.com/arghadipmanna101/Flipkart_Clone/assets/150791025/8008f0f7-6918-496d-b7ed-551b1c991cde)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kuritika098** [comment]
@arghadipmanna101, it would be great if you assign me this task . Thank you.

**Comment by arghadipmanna101** [comment]
Already solved
