### ISSUE TITLE
Feat: Description of deals must including rating and prizes.

### ISSUE THREAD

**Issue by kuritika098** [arghadipmanna101/Flipkart_Clone#358]
### Describe the feature

I thing we must include ratings , prizes , discount on every deal . As it will make it different and far more attractive than previous.

### Add ScreenShots

![Screenshot 2024-05-13 012939](https://github.com/arghadipmanna101/Flipkart_Clone/assets/150791025/3470cab2-58bc-480f-ab1b-7fed94703d4f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kuritika098** [comment]
I really wanna to work on this issue , please assign this to me.

**Comment by kuritika098** [comment]
thank you sir

**Comment by Karthikkariappa08** [comment]
i want to solve this issue please assign it to me sir
