### ISSUE TITLE
BUG: Flipkart Icon is not showing

### ISSUE THREAD

**Issue by i-am-faith** [arghadipmanna101/Flipkart_Clone#359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/98275372/a44b6b36-0846-4478-abac-97c0a21b8860)

In this image you can clearly see that Flipkart icon is not showing.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by i-am-faith** [comment]
@arghadipmanna101 Please assign this issue to me

**Comment by madanmishra19** [comment]
> @arghadipmanna101 Please assign this issue to me

Okk..! I'll check the problem.

**Comment by i-am-faith** [comment]
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/98275372/66b0f96e-ad5e-42ab-98a6-e474611ed86f)

Made exact same logo using Adobe Photoshop.
KIndly merge my PR.

**Comment by Akshatakapare** [comment]
I would like to contribute to this issue please consider me ...

**Comment by arghadipmanna101** [comment]
Already solved
