### ISSUE TITLE
Add  login page when clicked

### ISSUE THREAD

**Issue by PrabhjotBajwa** [arghadipmanna101/Flipkart_Clone#365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

hey mentor, I am Prabhjot Singh Bajwa web developer wants to add login and signup as a pop-up in flipkart website when we clicked signup and login button . plz assign this task to me under ggsoc24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by arghadipmanna101** [comment]
Already solved
