### ISSUE TITLE
Add Login feature 

### ISSUE THREAD

**Issue by SantoshiVerma** [arghadipmanna101/Flipkart_Clone#369]
### Describe the feature

add the login feature in navbar.

### Add ScreenShots

![filpcart clone](https://github.com/arghadipmanna101/Flipkart_Clone/assets/169477541/12979fc8-8a34-4004-89a2-6c884f8b0756)

__

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SantoshiVerma** [comment]
@arghadipmanna101 ,please assign me this work  i will work on it.

**Comment by arghadipmanna101** [comment]
Already solved
