### ISSUE TITLE
Navbar , Search Bar

### ISSUE THREAD

**Issue by oj1o1** [arghadipmanna101/Flipkart_Clone#37]
![Screenshot 2024-05-09 205627](https://github.com/arghadipmanna101/Flipkart_Clone/assets/122396350/806d2753-ad51-400e-9420-291e84ff2f93)
Hey @arghadipmanna101 
I am GSSOC Contributor. I have created couple of clones in the past 
I'll commit changes in search bar and also will change the logo and fonts .. please assign me

**Comment by Yuvika-14** [comment]
i would like to commit changes in navbar .please assign me this issue

**Comment by aanchalpahuja18** [comment]
Heyy @arghadipmanna101 I would like to fix the issue as I have made several clones in the past. So kindly accept my request of assigning me this issue

**Comment by arghadipmanna101** [comment]
Go ahead guys

**Comment by Akshar-Saxena** [comment]
Please assign me as I have worked on web for a long time

**Comment by Justaditi** [comment]
Please assign me this issue

**Comment by arghadipmanna101** [comment]
issue solved.

**Comment by Yuvika-14** [comment]
@arghadipmanna101  No submission before the induction will be counted for the leaderboard?

**Comment by supriyagaut** [comment]
@arghadipmanna101 i have a work experience on amazon prime clone , zomato clone so i have a better understanding please assign me this issue
