### ISSUE TITLE
It Does Not look likes Flipkarts Footer

### ISSUE THREAD

**Issue by rabinarayanpadhy07** [arghadipmanna101/Flipkart_Clone#372]
### Describe the feature

it does not look like flipkarts footer .Can you please assign me to fix this

### Add ScreenShots

![Screenshot (169)](https://github.com/arghadipmanna101/Flipkart_Clone/assets/132149572/21a158ca-9e32-4eeb-be68-19ed29b68bad)
it is the actual footer of your flipkarts
![Screenshot (170)](https://github.com/arghadipmanna101/Flipkart_Clone/assets/132149572/ff662400-7020-451f-b65b-35178da20f55)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ritikaguptaa** [comment]
@rabinarayanpadhy07 please assisgn this issue to me , i can solve this issue and please add this issue under gssoc.

**Comment by anupa-rb** [comment]
Hi there, I'm a beginner at open-source contribution so I want to gain hands-on experience by contributing to this project through GSSOC'24. Please assign this issue to me. Thank you.

**Comment by ayushiigarg** [comment]
hello please assign me this issue under gssoc'24

**Comment by usharani222** [comment]
Hi ,I'm a beginner at open-source contribution so I want to gain hands-on experience by contributing to this project through GSSOC'24. Please assign this issue to me.

**Comment by striton08** [comment]
I want to work on this issue.Please assign this issue to me.
