### ISSUE TITLE
BUG: Hovering effect on the search icon

### ISSUE THREAD

**Issue by HardCoder404** [arghadipmanna101/Flipkart_Clone#374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There should not be hovering effect on the search icon, it will reduce the efficiency of the web.
Assign me this bug, I'll be glad to work on that

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Dev-AyushTrivedi** [comment]
please assign me this task, i have created website using html, css, and js i have strong command on it , currently i am working as a contibuter in GSSOC'24 please assign this issue to me...

**Comment by AnujaG1** [comment]
I can contribute in hovering effect as  i know html , css and js. So assign me to see the great outcome

**Comment by AditiJ04** [comment]
Can you assign me this issue? I am working as a contributor in GSSOC'24.

**Comment by Kish-an-gupta** [comment]
Assign me this work I will create great hovering effect!!!
