### ISSUE TITLE
BUG:side buttons are not working 

### ISSUE THREAD

**Issue by sakshiiiii26** [arghadipmanna101/Flipkart_Clone#376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

This button are not responding. 
![Screenshot_2024-05-13-15-55-46-216-edit_com android chrome](https://github.com/arghadipmanna101/Flipkart_Clone/assets/157235573/0f4ab216-b3a5-40e9-b427-e499535b71c5)
And also image are not responsive 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sakshiiiii26** [comment]
Hello @arghadipmanna101 I'm contributor under GSSoC 24 I want to make this website responsive. I request you to assign this task to me. Thankyou!!

**Comment by Karthikkariappa08** [comment]
Hello , @arghadipmanna101 i request you to assign this issue to me
