### ISSUE TITLE
DOC: Responsive images 

### ISSUE THREAD

**Issue by sakshiiiii26** [arghadipmanna101/Flipkart_Clone#377]
### What's wrong with the existing documentation

On clicking image it doesn't open in new tab same site reloads. I'll make images responsive like actual Flipkart has on its website.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sakshiiiii26** [comment]
Hello @arghadipmanna101 I'm contributor under GSSoC 24 I want to work on this please assign me this task.

**Comment by AnujaG1** [comment]
Since i have strong knowledge on html , css and js. I  can contribute to this issue

**Comment by Karthikkariappa08** [comment]
Hello @arghadipmanna101 I'm contributor under GSSoC 24 I want to work on this please assign me this task. i have a good skills in HTML ,CSS, Js

**Comment by agkhushi** [comment]
Hello @arghadipmanna101 I'm a contributor under GSSoC'24 and i would like to work on this issue please assign me this task .
