### ISSUE TITLE
Dark Mode is not implemented properly

### ISSUE THREAD

**Issue by tat-tvam-asii** [arghadipmanna101/Flipkart_Clone#379]
The theme toggle button is not positioned correctly it is hiding the cart menu behind it
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/143332267/ac988c49-c841-43f3-bc18-9cb395aa2c5a)

Another issue is that the dark mode doesn't apply to the footer section
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/143332267/69c0b9b7-53ce-4ba0-bec4-fd92f58575fb)

Also the dark mode colours are not good on eyes.

@arghadipmanna101 Please assign this issue to me. I have implemented dark mode in the Swapreads website ,you can check.
Assign this issue to me under level 3 , i would make dark mode colour better, fix the problem in the footer section. And also fix the positon of the button and make it animated.

**Comment by revathishine** [comment]
Could you assign this task to  me I had worked as a web developer at iitm reseach park.With my experinece i could do better.

**Comment by MangaFlood** [comment]
hello, I'm a GSSOC'24 contributor and I would like to solve this issue for you sir @arghadipmanna101
