### ISSUE TITLE
DOC: Hover problem in search bar

### ISSUE THREAD

**Issue by Khanishsuresh** [arghadipmanna101/Flipkart_Clone#382]
### What's wrong with the existing documentation

The search bar is not been properly done the padding in the header section
This would make the search bar to look bad

### Add ScreenShots

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/136162512/05ab1b8e-7a1c-4a77-894d-5c60c1f6dc6b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Khanishsuresh** [comment]
Hii @arghadipmanna101 ,

i would like to contribute to this issue. Would u please assign me to this issue under GSSOC'24

**Comment by Aradhyajha** [comment]
Hello @arghadipmanna101...
 I'm contributor under GSSoC 24 ,  I want to work on this please assign me this task.

**Comment by Priyanjali24** [comment]
I want to work on this issue under Gssoc 2024.please assign me this.

**Comment by Snehakumari09** [comment]
Hello  @arghadipmanna101 I would like to work on this issue . Please assign me this task. Under GSSoC'24

**Comment by annu41432** [comment]
I would like to work on this project.please assign it to me,
