### ISSUE TITLE
DOC: Removal of unwanted paragraph

### ISSUE THREAD

**Issue by Khanishsuresh** [arghadipmanna101/Flipkart_Clone#384]
### What's wrong with the existing documentation

These informations are just required for the customer to see .
So I would like this to be removed and added in a separate section about 
By doing so, even the UI would be user-efficient and attractive 
The user will see only the required items in the web.

### Add ScreenShots

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/136162512/73c42ee0-de98-409d-be9d-ea429afaecaa)

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/136162512/f9fc0db2-07de-412e-9b87-be63593931da)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Khanishsuresh** [comment]
Hii @arghadipmanna101 ,

I would like to contribute to this issue .
Would u please assign this issue to me under GSSOC'24

**Comment by Adilkhan056** [comment]
I would like to work on this project. Please assign it to me.

**Comment by Khanishsuresh** [comment]
Hii @arghadipmanna101 ,

PR #464 
This issue has been solved 
Would u please accept my PR

**Comment by newcodergit** [comment]
I would like to work on this project. Please assign it to me.

**Comment by annu41432** [comment]
I would like to work on this issue.Please assign me this task.

**Comment by Khanishsuresh** [comment]
PR #508 

This PR would resolve this issue
please accept this PR

**Comment by ananyag309** [comment]
Hi, I hope this message finds you well.

I am writing to express my interest in contributing to the issue. I am enthusiastic about participating in GSSoC'24 and believe that working on this issue will allow me to make a meaningful contribution to the project.

Could you please assign this issue to me under GSSoC'24?

Thank you for considering my request.
