### ISSUE TITLE
Navbar_BUG:

### ISSUE THREAD

**Issue by Meetjain1** [arghadipmanna101/Flipkart_Clone#385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Our website is working fine but If we fix the Navbar it will be more user friendly. Thankyou

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by lassmara** [comment]
Please assign me this issue.
