### ISSUE TITLE
some sections of our website are colliding_BUG:

### ISSUE THREAD

**Issue by Meetjain1** [arghadipmanna101/Flipkart_Clone#386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

some sections are colliding in our website needs to be improved , @arghadipmanna101 assign this issue to me I will fix it. Thankyou 
Attaching screenshot for your reference

![colliding](https://github.com/arghadipmanna101/Flipkart_Clone/assets/133582566/dffd86a4-c268-46ce-98b0-53e8a27241ab)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by lassmara** [comment]
Please assign me this issue.
