### ISSUE TITLE
Hover_BUG:

### ISSUE THREAD

**Issue by Meetjain1** [arghadipmanna101/Flipkart_Clone#389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hover effect is somewhere too bad and somewhere not present attaching screenshots for your reference . @arghadipmanna101 assign this issue to me I will fix this bug . Thankyou 

![hover1](https://github.com/arghadipmanna101/Flipkart_Clone/assets/133582566/621d6e93-16c6-4b73-99fd-f498f557065e)

![hover2](https://github.com/arghadipmanna101/Flipkart_Clone/assets/133582566/2426919f-0d96-4255-a5dd-a85523a10b3e)

Here no hover effect , 

![hover3](https://github.com/arghadipmanna101/Flipkart_Clone/assets/133582566/1c7d3254-3521-4669-8d30-ccd81e98328a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Adilkhan056** [comment]
I would like to work on this project. Please assign it to me.

**Comment by Meetjain1** [comment]
@arghadipmanna101 sir just created pr #623 for this issue. Thanks

**Comment by Meetjain1** [comment]
Pr #623 merged hence closing this issue
