### ISSUE TITLE
Improve the footer of the website

### ISSUE THREAD

**Issue by Sneha123-zudo** [arghadipmanna101/Flipkart_Clone#39]
<img width="959" alt="image" src="https://github.com/arghadipmanna101/Flipkart_Clone/assets/145490348/50028eb2-50e5-4325-ae66-22c3a6bad224">

I want to improve the footer .
Please assign me this issue under GSSOC'24

**Comment by arghadipmanna101** [comment]
go ahead @Sneha123-zudo

**Comment by Kashish0047** [comment]
I want to improve this footer can you please assign this issue to me under GSSOC'24

**Comment by Pujan-sarkar** [comment]
I want to solve this issue , i am working under GSSOC'24. Will you assign this problem to me please ?

**Comment by arghadipmanna101** [comment]
Go ahead guys

**Comment by sys-atasi** [comment]
@arghadipmanna101 i also want to solve this issue, i am working under gssoc'24 will you assign me this task

**Comment by SalehaTabassum** [comment]
Hi @arghadipmanna101 please assign this issue to me

**Comment by GitNinja-bcd** [comment]
Kindly assign me this, I will solve this problem.
