### ISSUE TITLE
Repositioning Dark Theme Button Which Hiding the Cart button

### ISSUE THREAD

**Issue by Nithincoderboy** [arghadipmanna101/Flipkart_Clone#402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![screenshot](https://github.com/arghadipmanna101/Flipkart_Clone/assets/167434383/43a8decf-fcbc-4cc2-905f-2ef93273e6c8)

Hello **@arghadipmanna101** ,
      There is an Issue in front page of the Website. The **Dark Theme button is hiding over the cart button** ,So Users may feel a bad experience. So, I kindly request the Admin to assign me this Issue under GSSOC'24. I hope for a good result.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by madanmishra19** [comment]
@arghadipmanna101 i would like to work on this project. Please assign it to me.

**Comment by MuraliDharan7** [comment]
I am able to work on this issue. Please assign this task to me under GSSoC'24
