### ISSUE TITLE
Feat: Popup Login Box on Initial Page Load

### ISSUE THREAD

**Issue by SrishtiSonam** [arghadipmanna101/Flipkart_Clone#413]
### Describe the feature

When a user initially opens the page, we want to display a popup login box after a couple of time like 30 seconds. This will prompt users to login or register after a brief delay, providing a smoother user experience.

### Add ScreenShots

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/113123593/de6146b5-57f9-4878-aa0f-3e40cfb2577c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aradhya-005** [comment]
I would like to work on this issue .Please assign it to me.

**Comment by vidheeagrawal** [comment]
@arghadipmanna101 i can contribute here pls assign me this. You can assign me more.
