### ISSUE TITLE
BUG: Darkmode icon overlap

### ISSUE THREAD

**Issue by HK853** [arghadipmanna101/Flipkart_Clone#415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![chrome_n8Pc0cZGhB](https://github.com/arghadipmanna101/Flipkart_Clone/assets/113816862/b8e889a8-5fd2-40b2-b8ee-9dec6fbdcb45)

Here you can see that dark mode icon is overlapping with Cart 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by madanmishra19** [comment]
i have suggest you do not use dark mode icon.

**Comment by tanishkagupta27** [comment]
What happened?
Hello @arghadipmanna101
I hope this message finds you well. I wanted to bring to your attention an observation regarding our GitHub project's header section.

Upon reviewing the Flipkart Clone, the portion of the header, I noticed that there is "Darkmode Icon Overlap" in header section.

By solving "Overlap Problem" in the section of the header would enhance user experience.

I believe addressing this issue will contribute positively to our project's engagement and overall user satisfaction. Please let me know if you require any further information or assistance in implementing this change.

Thank you for your attention to this matter.

Best Regards,
Tanishka Gupta

Record
I agree to follow this project's Code of Conduct
I'm a GSSOC'24 contributor
I want to work on this issue

**Comment by Kalyan9064** [comment]
Subject: Request to Assign Dark Mode Icon Overlapping Issue (#415)

Hi Arghadip,

I hope this message finds
![Screenshot 2024-05-14 032631](https://github.com/arghadipmanna101/Flipkart_Clone/assets/154689485/7b30e3d4-1712-4dde-90b4-a5e5da3827cc)
