### ISSUE TITLE
Improving the nav bar

### ISSUE THREAD

**Issue by Manishar55** [arghadipmanna101/Flipkart_Clone#417]
### Describe the feature

Hello @arghadipmanna101 
The hover effect on the navbar icons are not looking good i want to make it more attractive
can you please assign this task to me under gssoc24

### Add ScreenShots

![Screenshot 2024-05-13 214329](https://github.com/arghadipmanna101/Flipkart_Clone/assets/154615478/2d8b8622-7c70-4b00-b0a8-571ff27d07e9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by madanmishra19** [comment]
i would like to on this project. Please assign it to me.

**Comment by Divyaraj33** [comment]
I would like to work on this project. Please assign it to me.

**Comment by Adilkhan056** [comment]
I would like to work on this project. Please assign it to me.

**Comment by Sreejita-code** [comment]
I would like to work on this project. Please assign it to me.

**Comment by janhvi1813** [comment]
I would like to add more features to the navbar ( fonts , border , hover effect , alignment etc. ) .Can you pls assign this task to me under Gssoc'24.

**Comment by Shivanipandey31** [comment]
I would like to work on this project(adding icons in the navbar just like the original website). Please assign it to me.
