### ISSUE TITLE
DOCI want to add requirements.txt to the documentation

### ISSUE THREAD

**Issue by hasmithagunda123** [arghadipmanna101/Flipkart_Clone#424]
### What's wrong with the existing documentation

assign it to me under gssoc

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by i-am-faith** [comment]
What is the usecase of "requirements.txt"??

It is not running in a virtual cloud. 
(Asking...)
