### ISSUE TITLE
Feat: Social Media Handles at footer are still not Working!!!!

### ISSUE THREAD

**Issue by Ayush170803** [arghadipmanna101/Flipkart_Clone#425]
### Describe the feature

Till Now at Footer of the Page Social Media Handles are not redirecting to the mentioned handles so kindly provide the social media respective account website links to fix this issue. Kindly assign me this issue, so i can work towards it under GSSoC'24. Thank You

### Add ScreenShots

https://github.com/arghadipmanna101/Flipkart_Clone/assets/115927008/763c9e1e-12d6-48c7-84b4-29acd7ea6cb9

please assign this issue under GSSoC'24. Thank You!!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by traptijindal** [comment]
kindly assign this issue to me ..
