### ISSUE TITLE
Remove overlapping between contents

### ISSUE THREAD

**Issue by ankitgupta143** [arghadipmanna101/Flipkart_Clone#426]
### Describe the feature

@arghadipmanna101 as you see on the top right corner there is overlapping between toggle button and cart tabs
Assign me the issue I can fix this problem

### Add ScreenShots

@arghadipmanna101 I can also improve the hover effect with better UI
![Screenshot 2024-05-14 110918](https://github.com/arghadipmanna101/Flipkart_Clone/assets/114281117/b9699f75-c38e-45c3-8a37-7019ae83a13c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Raghavi-22** [comment]
I would like to work on this issue.Could you assign it to me under GSSOC'24 **@arghadipmanna101**
