### ISSUE TITLE
BUG: Navbar elements are overlapped

### ISSUE THREAD

**Issue by suma30** [arghadipmanna101/Flipkart_Clone#429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-05-14 112736](https://github.com/arghadipmanna101/Flipkart_Clone/assets/112741893/06cd59f1-1df9-482c-b2e7-8dfe18b18328)

 The elements of the navbar are overlapped by the search bar
I want to fix this problem
Please assign me this issue under GSSOC'24 @arghadipmanna101 @yash

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sonia09-coder** [comment]
The navbar section is colliding, so please assign this task to me! @arghadipmanna101

**Comment by Raghavi-22** [comment]
I would like to work on this issue.Could you assign me this issue under GSSOC'24 **@arghadipmanna101** .

**Comment by traptijindal** [comment]
I would like to work on this issue.
