### ISSUE TITLE
BUG: Make the navbar hover more better

### ISSUE THREAD

**Issue by cxde-Sujal** [arghadipmanna101/Flipkart_Clone#431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

To make the hover effect with better colour remove the underline that's coming and make it bit circular  and when it resolutes to smaller size also the change will be made 

### Record
![Screenshot (150)](https://github.com/arghadipmanna101/Flipkart_Clone/assets/137087363/ef2e6126-10f3-43cc-babc-80646d5fc57e)

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by darshjnn** [comment]
As a GSSOC participant, I would like to work on this issue and make the navbar buttons more interactive.

**Comment by tahsinfatma1234** [comment]
I would like to work on this issue.please assign this task to me

**Comment by usharani222** [comment]
i would like to solve this issue .please assign it to me
Thank you
