### ISSUE TITLE
SOCIAL MEDIA ICONS (HOVERING +SIZE) ISSUE

### ISSUE THREAD

**Issue by Nih1tGupta** [arghadipmanna101/Flipkart_Clone#438]
### Describe the feature

WANT TO APPLY HOVERING EFFECT TO ICONS
AND ALSO TO INCREASE THIER SIZE

### Add ScreenShots

Example (previous work by me)
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/119615342/39e4271f-223f-4b39-9605-30a783c34891)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Nih1tGupta** [comment]
@arghadipmanna101 Please assign this issue to me. under GSSOC'24

**Comment by arghadipmanna101** [comment]
no need. you can work on another issue. thank you.
