### ISSUE TITLE
Feat: Improve the scrollbar look. 

### ISSUE THREAD

**Issue by GauravGupta993** [arghadipmanna101/Flipkart_Clone#443]
### Describe the feature

Improve the look of scrollbar by reducing its width, adding hover effect, and adding color to its track. 

### Add ScreenShots

from this
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/123398315/b24866ab-bf04-48c6-90e0-92b4c28a0d70) 
to
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/123398315/d3c64f78-2689-4ac1-b6d3-5f83c68f5c84)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by GauravGupta993** [comment]
Also is the scrollbar given in the above image fine or shall I use some other color combination for the scrollbar and its track?

**Comment by vanshm2703** [comment]
assign me this task

**Comment by Bhavishya2601** [comment]
I don't think the scrollbar looks nice
and moreover, This is a Flipkart clone, so we should remove the scrollbar as in the official Flipkart website just like the image

You can find some projects on my profile, it is featured on my profile and grabbed 4th position

So i think so I am the best fit.
![Uploading Screenshot 2024-05-16 205203.png…]()
