### ISSUE TITLE
Feat: INTEGRATE LOGIN FEATURE WITH GOOGLE

### ISSUE THREAD

**Issue by MuthuvelA** [arghadipmanna101/Flipkart_Clone#445]
### Describe the feature

Hey @arghadipmanna101  I am Muthuvel and I have prior experience of working with MERN stack. I would like to work on this issue. could you assign this issue to me with GSSOC'24 label.

Ok, now talking about Adding google authentication:-

We can do it using Passport.js npm library.
we can follow this steps to do so :-
Create a button called "Login with Google"
At backend, create a route, say "/auth" and on that route create a middleware to use passport.js functionalities.
"/auth" route authenticate user gmail and return its credentials to frontend.
Finally, At frontend we will store that credentials in localstorage.
Using Google OAuth
This feature will make the user easy to login.

I have read the code of conduct and expecting positive response. Thank you

### Add ScreenShots

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/125255596/c84ff1f9-be2b-47ea-ace1-7917e293250e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [x] I want to work on this issue

**Comment by MuthuvelA** [comment]
@arghadipmanna101 i will do it sir

**Comment by agarwalhimanshugaya** [comment]
as it was open one month before so i want please give me a chance to implement this i try to fix this issue .
please assigm me this issue under gssoc'24
