### ISSUE TITLE
Improve footer design and navbar designBUG:

### ISSUE THREAD

**Issue by Sameena10** [arghadipmanna101/Flipkart_Clone#448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Footer design and navbar design is not looking good we can add some good design  and hover buttons

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Sameena10** [comment]
See my issue

**Comment by CharanAdithya6505** [comment]
please assign this task to me, i have good experience in and did some good projects in HTML,CSS & JS.

**Comment by Mdazar123** [comment]
I'm proficient in design and have a strong grasp of CSS. I've created clones of Zomato and Netflix. Please consider assigning this task to me.

**Comment by izharisnia** [comment]
I would like to contribute on this project. Please assign it to me. @Sameena10

**Comment by hritika2409** [comment]
Hey.I can help you with this please assign me this task under GSSoC'24  as a contributor.

**Record**

- [ ]  I agree to follow this project's Code of Conduct
- [ ]  I'm a GSSOC'24 contributor
- [ ]  I want to work on this issue
@arghadipmanna101
