### ISSUE TITLE
Adding deals and products page

### ISSUE THREAD

**Issue by Madhu-mac** [arghadipmanna101/Flipkart_Clone#45]
The clone looks similar but it doesn't have any deals and products page in it, which makes the clone inconsistent. So i would like to add this feature to that page. 

Expected Design: 

![Screenshot_20240509_223129](https://github.com/arghadipmanna101/Flipkart_Clone/assets/99901964/86174181-2170-4bd1-b060-adefe737ea52)
<br><br>

![Screenshot_20240509_223211](https://github.com/arghadipmanna101/Flipkart_Clone/assets/99901964/8364cb26-335d-4f62-8c3b-71a2b59adaee)

**Comment by arghadipmanna101** [comment]
sure. Go ahead @Madhu-mac

**Comment by PayalKumari10** [comment]
@arghadipmanna101   i want to work on this issues,  can you assign me ?

**Comment by royalrajputayush** [comment]
i want to improve this issue more effectively

**Comment by Madhu-mac** [comment]
@arghadipmanna101 can you look into this PR, and let me know if any changes i need to make
