### ISSUE TITLE
Feat: To make products/mobile deals section display as CARDS

### ISSUE THREAD

**Issue by divyalaldinani** [arghadipmanna101/Flipkart_Clone#454]
### Describe the feature

before:
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/82147067/7be5ab1a-42c9-4b92-9259-4934a17e37f7)

after:
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/82147067/6a8482f3-e944-4af5-8712-7830aba502e3)

### Add ScreenShots

added above

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AmishaKri** [comment]
I would like to work on this project. Please assign it to me.

**Comment by divyalaldinani** [comment]
hii, deleted this forked repo as it had conflicts with main, i created a new fork and made same changes, should i create a new issue and raise a pr, or only create a new pr and tag this issue..
@arghadipmanna101 
final result:
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/82147067/87511fb2-b6ec-4cc8-bf23-0fbf5584645a)
