### ISSUE TITLE
Feat: Create Orders Page

### ISSUE THREAD

**Issue by anandachanta19** [arghadipmanna101/Flipkart_Clone#456]
### Describe the feature

I want to add orders page replicating flipkart's order page clone. Please assign this to me @arghadipmanna101 

### Add ScreenShots

![Screenshot (51)](https://github.com/arghadipmanna101/Flipkart_Clone/assets/149881203/f63b7c59-fe6d-4a6b-99fe-140f9ed01152)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anandachanta19** [comment]
#510 Resolves this issue

**Comment by anandachanta19** [comment]
Created Orders Page #510

**Comment by anandachanta19** [comment]
#510

**Comment by izharisnia** [comment]
I would like to contribute on this project. Please assign it to me. @anandachanta19
