### ISSUE TITLE
Feat: Adding content to the page .

### ISSUE THREAD

**Issue by sshivangi882** [arghadipmanna101/Flipkart_Clone#468]
### Describe the feature

Hey! Can you assign me again this task, I have already made the page but still it is not attended on the main page, let me do it again .
Assign me under GSSOC'24

### Add ScreenShots

![Screenshot (865)](https://github.com/arghadipmanna101/Flipkart_Clone/assets/122531720/397ceb31-58b0-4118-98dc-71c312ef7917)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by vandana79039** [comment]
i would want to work on this issue.
please assign me under GSSoC'24.

**Comment by ananyag309** [comment]
Hi, I hope this message finds you well.

I am writing to express my interest in contributing to the issue. I am enthusiastic about participating in GSSoC'24 and believe that working on this issue will allow me to make a meaningful contribution to the project.

Could you please assign this issue to me under GSSoC'24?

Thank you for considering my request.
