### ISSUE TITLE
Feat:Add Hover Effects to Social Media Icons and Footer Elements

### ISSUE THREAD

**Issue by thevijayshankersharma** [arghadipmanna101/Flipkart_Clone#472]
### Describe the feature

Enhance the user experience by implementing hover effects on social media icons and other elements in the footer. This feature will provide visual feedback to users when they interact with these elements, making the interface more engaging and intuitive. The hover effects will include subtle animations and color changes to indicate active states, improving the overall aesthetic and usability of the website.

### Add ScreenShots

As you can see, there is no hover effect on the social icons. I would like to implement it, along with resizing the icons.

![Screenshot 2024-05-14 211109](https://github.com/arghadipmanna101/Flipkart_Clone/assets/109781385/e40bb4ea-c501-48b2-92f3-871e9972daab)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by newcodergit** [comment]
I would like to work on this project. Please assign it to me.

**Comment by richasriva** [comment]
I can fix this issue properly. Kindly assign me this work @arghadipmanna101 .
