### ISSUE TITLE
BUG: Fix footer links

### ISSUE THREAD

**Issue by Jyoti040** [arghadipmanna101/Flipkart_Clone#473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The links in footer of about us and contact us on clicking does not navigate to right section . 
Instead on clicking, it goes to the top of page .
I want to fix this.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by CharanAdithya6505** [comment]
I wii do this i have good experience on solving the given problem , i had local setup of it

**Comment by arghadipmanna101** [comment]
already done
