### ISSUE TITLE
Feat: forgot password during signin.

### ISSUE THREAD

**Issue by kiruthigaa-k** [arghadipmanna101/Flipkart_Clone#474]
### Describe the feature

Add a feature to implement forgot password functionality while  the user tries to login to the website

### Add ScreenShots

![Screenshot 2024-05-14 220912](https://github.com/arghadipmanna101/Flipkart_Clone/assets/112771633/c560637a-beff-4016-b90f-c1cca289eb62)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Rajneeshkarya** [comment]
hey @kiruthigaa-k I would like to work on this issue. Could you assign this issue to me under GSSOC'24?

**Comment by Rajneeshkarya** [comment]
@arghadipmanna101  Could you assign me this issue?

**Comment by vandana79039** [comment]
hi, I am vandana kumari GSSOC'24 Contributor.
Could you please assign this task to me.
