### ISSUE TITLE
BUG:Navbar is not properly aligned.

### ISSUE THREAD

**Issue by traptijindal** [arghadipmanna101/Flipkart_Clone#478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

please assign this task to me..

![Screenshot 2024-05-14 235937](https://github.com/arghadipmanna101/Flipkart_Clone/assets/130233959/ccf4abbf-5721-4583-8e83-977cb5674f80)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by simitnamdev027** [comment]
hello, @arghadipmanna101 I want to work on this issue. please assign me this issue.

**Comment by tanishka786** [comment]
I would like to contribute in this project , so please assign this issue to me .

**Comment by Akshit462005** [comment]
Please assign this issue to me. I am a Technical Executive at the IEEE CUIET Organization.  
I would like to work on this issue. Providing you with the best results. I have already worked on projects like this and would like to contribute.

**Comment by Soujanya2004** [comment]
Hi, I have been following your project and would love to contribute. Can you please assign me this issue.
