### ISSUE TITLE
Feat: We can improve the description section.

### ISSUE THREAD

**Issue by traptijindal** [arghadipmanna101/Flipkart_Clone#479]
### Describe the feature

We can add font, color ,change size to it to make this look good.
![Screenshot 2024-05-15 000117](https://github.com/arghadipmanna101/Flipkart_Clone/assets/130233959/b1d61306-265f-46fd-86dc-1b2f68b05494)

### Add ScreenShots

![Screenshot 2024-05-15 000425](https://github.com/arghadipmanna101/Flipkart_Clone/assets/130233959/fefbed1c-23c5-44bd-991e-46ce88c81b91)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by thisismevri** [comment]
I would like to work on this issue please assign this task to me.

**Comment by traptijindal** [comment]
Hey! @arghadipmanna101.I have resolved this issue ,kindly review my pull request and close this issue.

**Comment by thisismevri** [comment]
Thank you sir
