### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by LunaNika** [arghadipmanna101/Flipkart_Clone#48]
I want to add the footer in the Home (main) page.
![Screenshot 2024-05-09 232517](https://github.com/arghadipmanna101/Flipkart_Clone/assets/169382952/98adf13b-375d-49d7-82ac-32ab9bc0f098)
There're some repeated things like about us, career also copyright is missing there I just want to update it.
@arghadipmanna101  can you please assigned this task to me?

**Comment by arghadipmanna101** [comment]
ok. go and solve it. @LunaNika

**Comment by Kashish0047** [comment]
i want to olve this issue.. can you please assign this task to me?
