### ISSUE TITLE
Feat: We can add hover effect to profile dropdown .

### ISSUE THREAD

**Issue by traptijindal** [arghadipmanna101/Flipkart_Clone#480]
### Describe the feature

We can improving by adding hover effects or changing colour.PLease assign this task to me.

### Add ScreenShots

![Screenshot 2024-05-15 000514](https://github.com/arghadipmanna101/Flipkart_Clone/assets/130233959/0d8da08d-8cf4-44c7-bc32-929f13936f00)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Syed0206** [comment]
Iam also interested to work on this issue @arghadipmanna101  can you please assign me this issue under GSSOC'245

**Comment by traptijindal** [comment]
Hey! @arghadipmanna101. I have resolved profile dropdown hovering issue. Kindly review my pull request.

**Comment by traptijindal** [comment]
Hey! @arghadipmanna101 . I have solved the merging issue .Please review it and close this issue as competed.
