### ISSUE TITLE
BUG: Add hover effect to all the images using Transition property of CSS

### ISSUE THREAD

**Issue by Sapta-Dev27** [arghadipmanna101/Flipkart_Clone#481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I want to add hover effect to all the images that are present in the shopping section using Transition ,hover effects , zoom properties of CSS

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by newcodergit** [comment]
I would like to work on this project. Please assign it to me.

**Comment by Syed0206** [comment]
Iam also interested to work on this issue @arghadipmanna101 can you please assign me this issue under GSSOC'24.

**Comment by himadeepthi1** [comment]
Hello ! @arghadipmanna101  , I'm a GSSOC'24 contributor and I would like to work on this issue

**Comment by DevNandini02** [comment]
@arghadipmanna101 sir, please assign me this task, i want to work on this issue.

**Comment by Sapta-Dev27** [comment]
@arghadipmanna101 sir , I'm grateful to you for assigning me the task ...I will be starting the work as soon as possible

**Comment by Sapta-Dev27** [comment]
@arghadipmanna101 sir , I've opened a pull request on the issue #481 , kindly check it and merge accordingly

**Comment by himadeepthi1** [comment]
@arghadipmanna101 , I have added hover effect to all the images using transition , hover effects , kindly check and merge #571 accordingly
