### ISSUE TITLE
Improve the ui of footer

### ISSUE THREAD

**Issue by Syed0206** [arghadipmanna101/Flipkart_Clone#483]
### Describe the feature

I would like to improve the ui of footer @arghadipmanna101  can you please assign me this issue under GSSOC'24.I have added screenshot of how footer will look after changes are applied.

### Add ScreenShots

<img width="1440" alt="Screenshot 2024-05-15 at 12 45 55 AM" src="https://github.com/arghadipmanna101/Flipkart_Clone/assets/123359660/28819fec-5b41-4579-82f7-7c3f93cb25f3">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by DevNandini02** [comment]
@arghadipmanna101 sir please assign me this task.

**Comment by hritika2409** [comment]
Hey.I can help you with this please assign me this task under GSSoC'24  as a contributor.

**Record**

- [ ]  I agree to follow this project's Code of Conduct
- [ ]  I'm a GSSOC'24 contributor
- [ ]  I want to work on this issue
