### ISSUE TITLE
BUG: Icons are not aligned properly in footer section

### ISSUE THREAD

**Issue by Manishar55** [arghadipmanna101/Flipkart_Clone#488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hii @arghadipmanna101 
The icons in the footer section are very small and are not properly aligned I will fix them.
Can you please assign this task to me under gssoc24

Before:
![Screenshot 2024-05-15 094444](https://github.com/arghadipmanna101/Flipkart_Clone/assets/154615478/2cd23d72-d181-48ce-b4d1-a18e3e7ed716)

After:
![Screenshot 2024-05-15 094602](https://github.com/arghadipmanna101/Flipkart_Clone/assets/154615478/c1c89bca-7321-4638-a5ef-6376dcaf0528)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Karthikkariappa08** [comment]
Hi Manishar55 ,
I'm excited to tackle the task of Icons are not aligned properly in footer section webpage. With my experience in website development using HTML, CSS, and JavaScript.



Please assign this task to me under GSSoC 24, and I'll get started right away!
Looking forward to your approval and the opportunity to contribute!

Thank you 😊!!

**Comment by vanshm2703** [comment]
Please can you assign me this issue under gssoc 24 , i would love working on it

**Comment by himadeepthi1** [comment]
Hello ! @arghadipmanna101  ,I'm a GSSOC'24 contributor and I would like to work on this issue

**Comment by izharisnia** [comment]
I would like to contribute on this project. Please assign it to me @Manishar55

**Comment by akdwivedi-explorer** [comment]
I can do this task, please assign me this under GSSoC'24.

**Comment by ANIRUDH130903** [comment]
Good morning, sir, can I please work on this issue @Manishar55.
