### ISSUE TITLE
BUG: The Product section is not properly ordered and layout is going out.

### ISSUE THREAD

**Issue by MuraliDharan7** [arghadipmanna101/Flipkart_Clone#489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The 4th image section is not properly formatted. That is need to redesign or the layout should be properly given.

Please Assign me this task under GSSoC'24.
![Screenshot 2024-05-15 111437](https://github.com/arghadipmanna101/Flipkart_Clone/assets/130668745/d4fd7c8b-ee3c-42d9-b34c-a061e4f96552)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by DevNandini02** [comment]
@arghadipmanna101 sir i want to work on this issue. Please assign me this task under gssoc' 24.

**Comment by MuraliDharan7** [comment]
@arghadipmanna101  check PR #520 here I had solve the issue and the PR has been merge by you. Kindly update this by closed. Thankyou
