### ISSUE TITLE
BUG: At Footer telephone call is not working so we can trigger it

### ISSUE THREAD

**Issue by Ayush170803** [arghadipmanna101/Flipkart_Clone#491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

At Footer We can trigger the telephone button by which it redirects to calling application in phone. Kindly assign me this issue, so i can work towards it under GSSoC'24. Thank You

https://github.com/arghadipmanna101/Flipkart_Clone/assets/115927008/3212b126-ef3e-4f05-9ff4-fa19e10ca798

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Dev-AyushTrivedi** [comment]
i can fix this issue please assign this to me

**Comment by Ayush170803** [comment]
@arghadipmanna101 i have succesfully committed changes and request pull request kindly merge it
