### ISSUE TITLE
Feat: Adding "Become a Seller" Page

### ISSUE THREAD

**Issue by ShubhamPaliwal03** [arghadipmanna101/Flipkart_Clone#493]
### Describe the feature

I would like to add a Sell Online Page to Become a Seller menu item in the Nav Bar and footer, which is currently not redirecting to any page.

### Add ScreenShots

Current State : ![Screenshot (1442)](https://github.com/arghadipmanna101/Flipkart_Clone/assets/85409061/52e4f365-a5e0-48b3-b110-399ee4eca6c2)

Proposed State : 
![Screenshot (1441)](https://github.com/arghadipmanna101/Flipkart_Clone/assets/85409061/98dc1685-017f-43aa-8cf9-161eb49cd751)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ShubhamPaliwal03** [comment]
I request @ arghadipmanna101 to add a gssoc label to this issue, assign this issue to me, and allow me to contribute.

**Comment by ShubhamPaliwal03** [comment]
Thanks @arghadipmanna101, I have started working on it, will make a PR once I am done.

**Comment by izharisnia** [comment]
I would like to contribute on this project. Please assign it to me. @ShubhamPaliwal03

**Comment by thisismevri** [comment]
please label the issues

**Comment by ShubhamPaliwal03** [comment]
@izharisnia I am working on it, I have designed and added the main components, I will be completing it soon, you can find out and work on other issues, thanks.

**Comment by thisismevri** [comment]
Sure

**Comment by ShubhamPaliwal03** [comment]
@arghadipmanna101, since I am making this page responsive,  as well as implementing all the interactive features, I request you to update the level to level3, or else you can also see my work when I am done, and then update it to level3, since this is a complex and time taking task, Thanks.

**Comment by ShubhamPaliwal03** [comment]
@arghadipmanna101, by the way, I am done with half of the work, I wanted to request you to upgrade the level to level3, as this issue comes under "Refactoring / Adding new features" from complete scratch, and it took a lot of time and effort to make this page, and I will be putting more effort in the remaining 50% of the work.

Below attached is the GSSOC point distribution for your reference, kindly mark it as level3. Will be making a PR as soon as it fully complete it. Thanks

![Screenshot (1446)](https://github.com/arghadipmanna101/Flipkart_Clone/assets/85409061/2bdbea02-9d49-46b4-87a0-7922bb6e127a)

**Comment by ShubhamPaliwal03** [comment]
@arghadipmanna101 50% of the task done.
![Screenshot (1447)](https://github.com/arghadipmanna101/Flipkart_Clone/assets/85409061/934a07a0-a622-4446-b9bd-0214c461b0eb)

**Comment by ShubhamPaliwal03** [comment]
Thanks @arghadipmanna101, I will be adding tons of more features and functionalities and making it the same as the Flipkart reference page, working on it.
