### ISSUE TITLE
BUG:NO NEED OF LARGE SWIPER BUTTON NOW.

### ISSUE THREAD

**Issue by Nih1tGupta** [arghadipmanna101/Flipkart_Clone#498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/119615342/dddcb24b-c6b5-44ed-9870-3013ee3a115e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ShahHetviIT** [comment]
I'm eager to lead the Flipkart_Clone project. With a solid background in HTML, CSS, JavaScript, and ReactJS, I'm confident in my ability to make substantial contributions to this project. Could you please assign me to this issue through GSSOC?

**Comment by arghadipmanna101** [comment]
already solved.
