### ISSUE TITLE
adding hover feature to the icons at top 

### ISSUE THREAD

**Issue by solanki505** [arghadipmanna101/Flipkart_Clone#5]
adding hover feature to the icons at top and adding a separate search page.

I would like to work on this issue please assign me this under GSSOC'24.

**Comment by Kkt04** [comment]
Please do assign me this.. Will add hover feature to the icons at top

**Comment by vaishnavip27** [comment]
Hey! I would really like to work on this issue. Can you please assign it to me? Looking forward for the approval

**Comment by BlazingBC** [comment]
As a front-end developer with expertise in Vanilla CSS, JavaScript, and HTML5, I, T Bharath Chandra, am eager to contribute to resolving the hover effect issue. With my experience and proficiency, I assure you that I can resolve this matter efficiently within 12 hours upon assignment. I am keen on collaborating with you to ensure a swift and effective solution. Looking forward to the opportunity to work together.

**Comment by Divi-1026** [comment]
As a front-end-developer I am eager to resolving the hover effect issue .I am already created a Amazon clone so I can assure you that I am successfully resolve that issue in very short amount of time .
Please assign this issue to me .
Thank You!!

**Comment by Paromita-maji** [comment]
hello, I am a GSSoC contributor, can you please assign me this issue?

**Comment by arghadipmanna101** [comment]
@solanki505   go ahead you have been assigned in this work.

**Comment by shuhaki** [comment]
i have very good experience in fronted part, i did some good projects related to fronted so, could you please assaign it to me i will do it

**Comment by arghadipmanna101** [comment]
Go ahead guys

**Comment by anushkapal28** [comment]
Hi there,

I'm keen on contributing to GSSoC'24! I'd love to take on the task of adding a hover feature to the icons at the top and creating a separate search page. Could you please assign me this task?

Looking forward to making these enhancements!

**Comment by Gokilp** [comment]
Assign this issue to me under GSSoc'24 so that i can work on it

**Comment by HeyimSomnath** [comment]
can you assign this to me, i can make it more refine.

**Comment by AditiJeena** [comment]
Can you please assign me this issue?

**Comment by yashika0432** [comment]
assign his issue to me as I have been doing the web development for a few days now and I would do my best

**Comment by USERASHOKG** [comment]
please assign me this i can also do this!!!
