### ISSUE TITLE
Feat: Enhance the UI of nav bar

### ISSUE THREAD

**Issue by Naincy04** [arghadipmanna101/Flipkart_Clone#503]
### Describe the feature

Provide a consistent style to the  links and buttons in the navigation bar.
Align the design with the overall style of the website.

### Add ScreenShots

Current state :-

![Screenshot from 2024-05-15 18-30-37](https://github.com/arghadipmanna101/Flipkart_Clone/assets/111273192/a28e3aae-8b88-4276-855b-42f19ae68dd8)

Proposed state :- 

![Screenshot from 2024-05-15 19-32-24](https://github.com/arghadipmanna101/Flipkart_Clone/assets/111273192/7b8fcd59-a6ed-41d2-91d0-727f814d8675)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by YashkShrivas4491** [comment]
@Naincy04 
note: whenever you are submitting an issue always try to add a proposed screenshot of what you want to change and why ok.
so it will make a better impact on the maintainer of a particular open-source project

**Comment by Naincy04** [comment]
Okk...Thank you for your suggestion. I have included a proposed screenshot with this issue and will make sure to include screenshots in future submissions to improve the clarity and impact of my requests. 

Kindly assign me this issue under GSSOC'24.

**Comment by YashkShrivas4491** [comment]
> @YashkShrivas4491 Okk...Thank you for your suggestion. I have included a proposed screenshot with this issue and will make sure to include screenshots in future submissions to improve the clarity and impact of my requests.
> 
> Kindly assign me this issue under GSSOC'24.

**Comment by Anshravicode89** [comment]
@YashkShrivas4491 the navigation bar is still not fixed. Kindly assign me this issue under GSSOC'24
![Screenshot 2024-05-16 115100](https://github.com/arghadipmanna101/Flipkart_Clone/assets/166092579/1b5baa1c-d3d4-4fd9-9da7-62d6045cc743)

**Comment by Aradhyajha** [comment]
hello @arghadipmanna101 
Please assign this task to me, i want to work on this issue

**Comment by MangaFlood** [comment]
hello, I'm a GSSOC'24 contributor and I would like to solve this issue for you and recreate the nav-bar @arghadipmanna101

**Comment by simitnamdev027** [comment]
hey @arghadipmanna101 i would like to work on this issue

**Comment by drick-infinity** [comment]
can you assign this issue to me under gssoc'24 as I learned MERN stack development in I can design smae navabar as actual filkart has can you assign me under gssoc'24

**Comment by tanishka786** [comment]
I would like to contribute in this project , so please assign this issue to me .

**Comment by Ananya-Nair20** [comment]
Hello @arghadipmanna101 

I am participating in GSSOC'24. I am interested in resolving this issue Could you please assign this task to me under GSSOC'24 with relevant level labels?

Thank you
