### ISSUE TITLE
Documentation Error 

### ISSUE THREAD

**Issue by Kamna-712** [arghadipmanna101/Flipkart_Clone#505]
### What's wrong with the existing documentation

There is some documentation error is the written code of navbar.html

### Add ScreenShots

![Screenshot 2024-05-15 184131](https://github.com/arghadipmanna101/Flipkart_Clone/assets/130769466/255e4bc4-991e-4d75-b152-f11cbb390949)
Like here unnecessary bracket is written in the code and in the same way there are many small changes in all the code files.. I would like to correct this documentation error in all the code files 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Kamna-712** [comment]
and please do add labels to it and assign this task to me

**Comment by ananyag309** [comment]
Hi, I hope this message finds you well.

I am writing to express my interest in contributing to the issue. I am enthusiastic about participating in GSSoC'24 and believe that working on this issue will allow me to make a meaningful contribution to the project.

Could you please assign this issue to me under GSSoC'24?

Thank you for considering my request.
