### ISSUE TITLE
Fix the back to the top button 

### ISSUE THREAD

**Issue by Ramben0909** [arghadipmanna101/Flipkart_Clone#507]
### Describe the feature

I will fix the back to the top button in the bottom of the page so that when we come to the top of the page it does not appears .  

### Add ScreenShots

![Screenshot 2024-05-15 190525](https://github.com/arghadipmanna101/Flipkart_Clone/assets/121795329/b359b91c-c869-41bb-8b2a-9145577ea8b0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ramben0909** [comment]
I have good knowledge of this issue. I will fix the JavaScript to handle this issue . 
Hey @arghadipmanna101 please add level and assign me this issue as a GSSoC contributor

**Comment by ShahHetviIT** [comment]
I'm eager to lead the Flipkart_Clone project. With a solid background in HTML, CSS, JavaScript, and ReactJS, I'm confident in my ability to make substantial contributions to this project. Could you please assign me to this issue through GSSOC?

**Comment by shubham6m** [comment]
@Ramben0909 please assign this issue to me

**Comment by niteshbca** [comment]
@Ramben0909 please assign to me task.

**Comment by Ramben0909** [comment]
hey @arghadipmanna101   I have resolved it and made pull request please review it
