### ISSUE TITLE
BUG: Optimize the size of images to improve page load speed .

### ISSUE THREAD

**Issue by janhvi1813** [arghadipmanna101/Flipkart_Clone#514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Large images can significantly slow down the loading time of your webpage, especially on slower internet connections.Pls assign the work to me @arghadipmanna101 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sheryar-bit** [comment]
Can I work on this issue please assign this issue to me @arghadipmanna101

**Comment by supriyabharane** [comment]
I would  Like to work on this. Please assign this issue to me@arghadipmanna101
