### ISSUE TITLE
login page

### ISSUE THREAD

**Issue by Sandhyarani23** [arghadipmanna101/Flipkart_Clone#515]
### Describe the feature

I will add the login and sign up pages to this clone. and bottom to top button align it to the right side. and also the navbar icons alignment is not looking elegant i can make the changes to look good by aligning them.in dark mode the three dots cant be seen i will update that.and at last it will look good if the images border radius and card hover effects are applied.
kindly assign me this issue under GSSOC'24 and level.thank you.

### Add ScreenShots

![Screenshot 2024-05-15 221151](https://github.com/arghadipmanna101/Flipkart_Clone/assets/147230518/29c0f0a9-a3f5-41d5-acf3-6a636d5aa47a)

![Screenshot 2024-05-15 221236](https://github.com/arghadipmanna101/Flipkart_Clone/assets/147230518/2d527952-1308-495c-bef2-9d5e29fa9d7c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sandhyarani23** [comment]
Thank you for your response.I will do it my best

**Comment by ananyag309** [comment]
Hi, I hope this message finds you well.

I am writing to express my interest in contributing to the issue. I am enthusiastic about participating in GSSoC'24 and believe that working on this issue will allow me to make a meaningful contribution to the project.

Could you please assign this issue to me under GSSoC'24?

Thank you for considering my request.
