### ISSUE TITLE
BUG: Repetition of icons

### ISSUE THREAD

**Issue by tat-tvam-asii** [arghadipmanna101/Flipkart_Clone#522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The same icons are present twice on the webpage

SS : 
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/143332267/3705482b-8d15-49eb-bff0-7e484dffde61)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by thisismevri** [comment]
I would like to work on this issue please assign this task to me

**Comment by SuhainaFathimaM** [comment]
@arghadipmanna101 Please assign me this issue
