### ISSUE TITLE
BUG: not responsive

### ISSUE THREAD

**Issue by Aanyaa26** [arghadipmanna101/Flipkart_Clone#527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/128315909/4b6e48c3-64f6-44a5-b902-368fb6e13b96)
the site is not responsive enough so that it can adjust on varied screen sizes!
E-commerce websites are crucial ones and must be responsive!
please assign me to debug this error!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by tanishka786** [comment]
I would like to contribute in this project , so please assign this issue to me .
