### ISSUE TITLE
BUG: Responsiveness  is not working properly

### ISSUE THREAD

**Issue by GOURAVSINGH19** [arghadipmanna101/Flipkart_Clone#529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://github.com/arghadipmanna101/Flipkart_Clone/assets/120244528/5754e36b-b7e0-4922-a307-55018ea7ce61

As @arghadipmanna101 can see it work properly and I want to correct this issue .
Can you assign me 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by amitkumar2308** [comment]
hey! @arghadipmanna101 can you assign me this issue

**Comment by simitnamdev027** [comment]
@arghadipmanna101 please assign me this issue .
  i am GSsoc contributor

**Comment by Neha14-14** [comment]
@arghadipmanna101 . I would like to contribute . please assign to me
