### ISSUE TITLE
Feat: ADD CONSUMER POLICYS 

### ISSUE THREAD

**Issue by Vaibhav22p-qw** [arghadipmanna101/Flipkart_Clone#530]
### Describe the feature

ADD CONSUMER POLICYS PAGE ,WHERE ALL THE POLICYS ARE DEFINED

### Add ScreenShots

![duck](https://github.com/arghadipmanna101/Flipkart_Clone/assets/75926745/80f43a72-2541-48e0-9d13-bf54d934629d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by arghadipmanna101** [comment]
already solved.
