### ISSUE TITLE
Feat: ADD ABOUT US SECTION 

### ISSUE THREAD

**Issue by Vaibhav22p-qw** [arghadipmanna101/Flipkart_Clone#531]
### Describe the feature

ADD ALL SECTION PAGE (Which is given below)

### Add ScreenShots

![DUCK2](https://github.com/arghadipmanna101/Flipkart_Clone/assets/75926745/81470e14-ddc9-4165-997f-e2093140e9ad)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Rauukr** [comment]
assing me this as GSSOC'24 contribution and add level

**Comment by arghadipmanna101** [comment]
already solved.
