### ISSUE TITLE
Improving Flipkart plus zone page

### ISSUE THREAD

**Issue by gaddevinay** [arghadipmanna101/Flipkart_Clone#533]
The text in the image is not clearly visible.
Fixing navbar adding search icon and dark mode.
Adding some products .
Fotter also need some improvements.
![Screenshot_20240516-074123](https://github.com/arghadipmanna101/Flipkart_Clone/assets/128584849/88018f32-f5b9-4979-acaa-06907d8d9984)

**Comment by tanishkaa08** [comment]
i would love to fix this issue. please assign it to me.
