### ISSUE TITLE
Feat: Style the details section on home page

### ISSUE THREAD

**Issue by anishpujari** [arghadipmanna101/Flipkart_Clone#534]
### Describe the feature

Style the details section on home page to match it to the original flipkart website. Styling the font as well as the background.

### Add ScreenShots

Flipkart_Clone:
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/91270040/04494b4f-41a7-45b5-9cc9-33a3bdea4c47)

Original Flipkart:
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/91270040/ed44878b-b860-438c-a1c3-f15da4712879)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by rounakdey6** [comment]
I would like to work on this issue. Please assign this issue to me @anishpujari
