### ISSUE TITLE
BUG: No content in Top deals page and the description not given

### ISSUE THREAD

**Issue by MuraliDharan7** [arghadipmanna101/Flipkart_Clone#536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Top Deals page has no description and what the top deal is.
I can add the description and the deals for each product category 

Please assign this task to me under GSSoC'24.

![topDeals](https://github.com/arghadipmanna101/Flipkart_Clone/assets/130668745/82d88bbb-6d07-4acd-93aa-1f4bfe9749e3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by supriyabharane** [comment]
I would Like to work on this. Please assign this issue to me

**Comment by MuraliDharan7** [comment]
I solved it and made a PR #593. Kindly check and merge it.
Thank you.

**Comment by MuraliDharan7** [comment]
The issue closes when PR merged.  

Fixes #593

**Comment by SuhainaFathimaM** [comment]
@arghadipmanna101 Please assign me this issue
