### ISSUE TITLE
BUG: Night Mode Icon and Download App button are overlapping .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [arghadipmanna101/Flipkart_Clone#537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the navbar the Night Mode icon is overlapping with the download app button .
![Screenshot 2024-05-16 150325](https://github.com/arghadipmanna101/Flipkart_Clone/assets/118350936/ed2e5c65-deb1-4414-80f0-1a9dc1033868)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Siddhant-Mahato** [comment]
Hello @arghadipmanna101 , Can you please assign it to me so the i an fix it and please add level to it.

**Comment by MangaFlood** [comment]
hello, I'm a GSSOC'24 contributor and I would like to solve this issue for you @arghadipmanna101

**Comment by Ayushmaanagarwal1211** [comment]
Hii i will Send PR today
