### ISSUE TITLE
Add a Cart page

### ISSUE THREAD

**Issue by Surajit0573** [arghadipmanna101/Flipkart_Clone#54]
Currently Cart button is not working, I want to add a new page for Cart. Please assign me under Gssoc'24.

**Comment by arghadipmanna101** [comment]
go ahead bro

**Comment by Justaditi** [comment]
PLease assign me this

**Comment by arghadipmanna101** [comment]
> PLease assign me this

One person is working on this issue. Wait for him

**Comment by royalrajputayush** [comment]
@arghadipmanna101 please assign me work on this issue for more appropriate solution

**Comment by vaishnavip27** [comment]
Hey! @arghadipmanna101 I would love to work on this issue as I have good experience with building it. As a designer and a developer i can bring much on the table. Please assign me with this issue. Looking forward for the approval

**Comment by madanmishra19** [comment]
i would like to work on this project. Please assigned it to me.
