### ISSUE TITLE
Feat: The Text will be justified for the text after Products .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [arghadipmanna101/Flipkart_Clone#540]
### Describe the feature

I think that if the text will be justified from both the sides then it may increase user experience .

### Add ScreenShots

![Screenshot 2024-05-16 150625](https://github.com/arghadipmanna101/Flipkart_Clone/assets/118350936/3b5d8291-8162-4a72-868a-840d973652de)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Manishar55** [comment]
Hii @arghadipmanna101 can you please assign this issue to me
