### ISSUE TITLE
BUG: Fixing the nav bar

### ISSUE THREAD

**Issue by Manishar55** [arghadipmanna101/Flipkart_Clone#548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hii @arghadipmanna101 
The search button and the navbar are overlapping so I want to fix this issue
Can you please assign  this issue to me under gssoc24

![Screenshot 2024-05-16 161238](https://github.com/arghadipmanna101/Flipkart_Clone/assets/154615478/7efa5f5a-edc7-405d-bbcf-cd8cfa29bd8b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by MangaFlood** [comment]
hello, I'm a GSSOC'24 contributor and I would like to solve this issue for you and recreate the nav-bar @arghadipmanna101
