### ISSUE TITLE
BUG: the icons of advertise and download app is not aligned in proper way going out of the page

### ISSUE THREAD

**Issue by solanki505** [arghadipmanna101/Flipkart_Clone#551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-05-16 163442](https://github.com/arghadipmanna101/Flipkart_Clone/assets/158484284/95c09c13-8639-432a-81a8-933756fd3e57)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by arghadipmanna101** [comment]
done
