### ISSUE TITLE
Files not organized efficiently

### ISSUE THREAD

**Issue by csathnere** [arghadipmanna101/Flipkart_Clone#554]
### Describe the feature

website files are currently not organized efficiently, making it difficult to locate and manage them effectively.

### Add ScreenShots

![Screenshot_2024-05-16-18-25-56-156_com android chrome](https://github.com/arghadipmanna101/Flipkart_Clone/assets/58299457/3f25971f-e4fd-4591-929a-ebd7ec61ca4d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC'24 contributor
- [x] I want to work on this issue

**Comment by arghadipmanna101** [comment]
what changes you want to do plz explain once.

**Comment by Ananyarawa8t** [comment]
Hey @arghadipmanna101,
A unorganized project structure makes it difficult to maintain and collaborate on. I would like to organize your HTML, CSS, images, icons and JavaScript files for better readability. 
I would like to Create a main project folder. This will hold everything related to your website.
Inside the main folder, create separate subfolders for:
HTML: This will hold all your HTML files, like index.html, about.html, etc.
CSS: This will hold all your stylesheet files, like style.css, layout.css, etc.
Images: This will hold all your website images (logos, icons, backgrounds, etc.)
JavaScript: This will hold all your JavaScript files for interactivity (scripts.js, animations.js, etc.)
Please assign me to fix this as part of GSSOC'24.
Best Regards,
Ananya Rawat
