### ISSUE TITLE
BUG: The profile icon is not properly aligned with div and text

### ISSUE THREAD

**Issue by shnwz-solves** [arghadipmanna101/Flipkart_Clone#558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

BUG: The profile icon is not properly aligned with div and text.
I want to contribute in this project under GSSOC'24.

Screenshot:
![Screenshot 2024-05-16 193820](https://github.com/arghadipmanna101/Flipkart_Clone/assets/126380641/bb5ccac9-d247-4db2-8991-e2df1e4f8e68)

Hey PA,
Please assign me this task. Thankyou.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shnwz-solves** [comment]
Thankyou PA for assigning me this task. I will try to do it asap.

**Comment by radharashmitha** [comment]
Hi @arghadipmanna101 . I have an idea to sort out this issue. I would like to work on it as contributor under gssoc'24. Please assign this issue to me .
