### ISSUE TITLE
Add Dropdown Design 

### ISSUE THREAD

**Issue by Dominic-SR** [arghadipmanna101/Flipkart_Clone#56]
![Screenshot from 2024-05-09 23-58-07](https://github.com/arghadipmanna101/Flipkart_Clone/assets/68345908/4797efdc-8467-4683-a4cc-b895d170da59)

Currently there is no design in the dropdown so assign me in this issue , thank you !

**Comment by PoojaGadagi08** [comment]
Hello @arghadipmanna101 sir
I would like to work on this issue as a contributor to the GSSOC. please assign this to me!
I have relevant skills that definitely help to enhance the website.

**Comment by arghadipmanna101** [comment]
solved
