### ISSUE TITLE
Feat:Add category section to flipkart home

### ISSUE THREAD

**Issue by Pratik2401** [arghadipmanna101/Flipkart_Clone#561]
### Describe the feature

To display category section on flipkart home

### Add ScreenShots

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/105542579/8fe2b4ff-3a19-4aff-8e1a-4bdf1c16e011)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Teja-m9** [comment]
hey @Pratik2401 please assign this to me as i pretty go with the web development and i can able to fix the bugs and improve the code
