### ISSUE TITLE
Feat:Enhancing the flipkart menu and making it more like a flipkart

### ISSUE THREAD

**Issue by Pratik2401** [arghadipmanna101/Flipkart_Clone#562]
### Describe the feature

I will work on profile section menu as in og flipkart and it exact and also i will fix the navbar as needed

### Add ScreenShots

Current
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/105542579/1a84a7ca-5219-4d53-b7e1-d7c74386d316)

Orignal
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/105542579/60c6fa06-12ef-4657-8b1e-e8abd71d67c0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Pratik2401** [comment]
Can I get assign multiple issue bcoz there are a lot of pages missing that i would like to add

**Comment by sxnkush** [comment]
Please assign this issue to me
