### ISSUE TITLE
BUG: card goes out the section on hovering

### ISSUE THREAD

**Issue by Manishar55** [arghadipmanna101/Flipkart_Clone#564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hii @arghadipmanna101 
On hovering the card goes out of the section and the photo gets cut off I want to fix this issue
Can you please assign me this issue under gssoc24.

![Screenshot 2024-05-16 203047](https://github.com/arghadipmanna101/Flipkart_Clone/assets/154615478/6e33c36e-5590-4a0c-99b9-c1614f7746d9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by radharashmitha** [comment]
Hii @arghadipmanna101
I have understood the problem. I would like to work on this issue under GSSOC'24 contributor.
Please assign this issue to me.
