### ISSUE TITLE
Feat: Remove Scrollbar

### ISSUE THREAD

**Issue by Bhavishya2601** [arghadipmanna101/Flipkart_Clone#566]
### Describe the feature

I don't think the scrollbar looks nice
and moreover, This is a Flipkart clone, so we should remove the scrollbar as in the official Flipkart website just like the image

You can find my recent projects on my profile

Hope you would assign this task to me

### Add ScreenShots

.
![Screenshot 2024-05-16 205203](https://github.com/arghadipmanna101/Flipkart_Clone/assets/147748752/1a87c70f-1218-4454-9e40-ead89fdc3467)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SHANMUGAPRIYA-1** [comment]
Please do assign this task to me

**Comment by Bhavishya2601** [comment]
@arghadipmanna101 i have completed the task

Merge the pull request into your repo
