### ISSUE TITLE
BUG: NavBar is Not properly aligned

### ISSUE THREAD

**Issue by Bhavishya2601** [arghadipmanna101/Flipkart_Clone#567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The navbar is not aligned properly, I think so that navbar is the most important thing when coming to the homepage of the website
it is the first thing that should be properly aligned.

Hope you would assign this task, as this task can't be procrastinated

You can check some of my recent projects on my profile, I am also providing the link for my most recent project, you can check it out

[https://bid-out.vercel.app/](url)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ShahHetviIT** [comment]
I'm excited about taking the lead on the Flipkart_Clone project. With my proficiency in HTML, CSS, JavaScript, and ReactJS, I'm confident in my ability to drive significant progress on this initiative. Please assign me to this project via GSSOC.
