### ISSUE TITLE
BUG: Footer's alignment is not proper

### ISSUE THREAD

**Issue by Bhavishya2601** [arghadipmanna101/Flipkart_Clone#568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The alignment of the footer is not as that of the official site

Allow me to correct it, by assigning this task to me 

You can also check out my profile for my recent projects, I am also providing the link for it as well
[https://bid-out.vercel.app/
![Screenshot 2024-05-16 211341](https://github.com/arghadipmanna101/Flipkart_Clone/assets/147748752/1e17dd85-4894-4aff-954d-f44eaae38f17)
](url)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ShahHetviIT** [comment]
I'm excited about taking the lead on the Flipkart_Clone project. With my proficiency in HTML, CSS, JavaScript, and ReactJS, I'm confident in my ability to drive significant progress on this initiative. Please assign me to this project via GSSOC.

**Comment by Bhavishya2601** [comment]
@arghadipmanna101 
can you please reassign this task to me

**Comment by AnirbanChattopadhyay-2004** [comment]
please assign this task to me

**Comment by tanishka786** [comment]
Sir please assign this issue to me .

**Comment by tanishka786** [comment]
I would like to contribute in this project , so please assign this issue to me .
