### ISSUE TITLE
BUG: The text on the homepage 

### ISSUE THREAD

**Issue by Bhavishya2601** [arghadipmanna101/Flipkart_Clone#569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The font and size and alignment of the text on the homepage is not proper and is providing a bad impact on the website

I want to change it from
![Screenshot 2024-05-16 211729](https://github.com/arghadipmanna101/Flipkart_Clone/assets/147748752/cc70049e-7e50-425a-b527-3c3eb10f0543)
to
![Screenshot 2024-05-16 211823](https://github.com/arghadipmanna101/Flipkart_Clone/assets/147748752/d6569625-ba92-4d4e-ab69-c57a03449ea2)

Hope you will assign this task to me, You can also checkout my profile for my recent projects

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [x] I want to work on this issue

**Comment by Bhavishya2601** [comment]
@arghadipmanna101 
Hope you'll assign this task to me

**Comment by thisismevri** [comment]
i will want to work on this issue plz assign me this sir @arghadipmanna101
