### ISSUE TITLE
Signup , sign-In not working fine 

### ISSUE THREAD

**Issue by Meetjain1** [arghadipmanna101/Flipkart_Clone#57]
![Screenshot 2024-05-10 000703](https://github.com/arghadipmanna101/Flipkart_Clone/assets/133582566/681b1bea-3bfe-4a78-bd03-b902708fe619)
there is no need of 3 sections profile, signup,sign in rather than this they can be combine in a single button in working condition , In signup.html existing user button is not working also there is no hover effect also . Also signin page name is coming as signup and vice versa.

**Comment by Meetjain1** [comment]
@arghadipmanna101  Assign this task to me I will do it

**Comment by arghadipmanna101** [comment]
ok. go ahead @Meetjain1 best of luck 🤞

**Comment by Meetjain1** [comment]
@arghadipmanna101 Thankyou sir, I have just raised a PR regarding this issue .

**Comment by Pujan-sarkar** [comment]
is this problem solved ? i want to contribute i am working under GSSOC'24,  @arghadipmanna101 will you assign this problem to me .

**Comment by arghadipmanna101** [comment]
> is this problem solved ? i want to contribute i am working under GSSOC'24, @arghadipmanna101 will you assign this problem to me .

Yes it is working properly no need to change anything in signup and sign-in page if you want to work in backend you can. ok

**Comment by Meetjain1** [comment]
pr #63
