### ISSUE TITLE
BUG: There should be slight spacing between the search bar and the profile.

### ISSUE THREAD

**Issue by simmi123997** [arghadipmanna101/Flipkart_Clone#574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The search bar and the profile are quite close which doesn't make it look perfect.

![Screenshot 2024-05-16 222628](https://github.com/arghadipmanna101/Flipkart_Clone/assets/134286697/4d7a1908-0f93-4d9c-82a1-a746117b0d03)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by simmi123997** [comment]
I would like to work on this issue. Please assign it to me Sir.

**Comment by cpratik1307** [comment]
I am thrilled to be participating in GirlScript Summer of Code 2k24 as a passionate computer science student with a keen interest in web development. I am eager to contribute to your project and leverage my skills to make meaningful contributions. I look forward to collaborating with you and the team to create impactful solutions.
@arghadipmanna101 Sir, I would really like to work on this issue, so please assign it to me.

**Comment by thisismevri** [comment]
I would like to work on this issue. Please assign it to me Sir @arghadipmanna101

**Comment by Vinay-Yadav01** [comment]
Can you please assign to me in gssoc

**Comment by ANIRUDH130903** [comment]
good evening ma'am
please assign me this issue @simmi123997 , i would like to work on it .

**Comment by Maana-Ajmera** [comment]
I would like to work on this issue. Please assign it to me Sir @arghadipmanna101

**Comment by annuk123** [comment]
can you please assign me this issue

**Comment by grasyPatel** [comment]
Hello @arghadipmanna101 ,can you please assign me this issue
