### ISSUE TITLE
BUG: Flipkart Zone cover image is blur and not responsive

### ISSUE THREAD

**Issue by MuraliDharan7** [arghadipmanna101/Flipkart_Clone#575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Cover of the Flipkart zone plus is blur and not even having hover effect or other effect. 

Please assign this task to me under GSSoC'24.

![FlipKart_clone plus zone image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/130668745/96d0d51a-4434-4c00-9f79-35922d7ef748)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SakiraAli1115** [comment]
can you please assign me this issue?

**Comment by MuraliDharan7** [comment]
closes#643
