### ISSUE TITLE
Feat: Updating the Homepage

### ISSUE THREAD

**Issue by jha-niraj** [arghadipmanna101/Flipkart_Clone#576]
### Describe the feature

Updating the Homepage of the website to make it more look alike real flipkart.com.

### Add ScreenShots

Here, I can see that the Homepage of the website is not much like real website and also the responsiveness is not good at all.
Assign me this issue so that I can work on this and submit a new good looking UI with responsiveness added.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by jha-niraj** [comment]
Thanks @arghadipmanna101 for assigning this to me, I will try to complete this as soon as possible.

**Comment by jha-niraj** [comment]
Hey @arghadipmanna101, I think someone has already made an impressive changes to the Homepage and Navbar. So I think I don't have much to change.

**Comment by ananyag309** [comment]
Hi, I hope this message finds you well.

I am writing to express my interest in contributing to the issue. I am enthusiastic about participating in GSSoC'24 and believe that working on this issue will allow me to make a meaningful contribution to the project.

Could you please assign this issue to me under GSSoC'24?

Thank you for considering my request.
