### ISSUE TITLE
BUG: Flipkart logo colliding with profile page 

### ISSUE THREAD

**Issue by MuraliDharan7** [arghadipmanna101/Flipkart_Clone#577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

flipkart logo collides with profile sigin up form. I can solve this issue.

Please assign this to me under GSSoC'24.

![Flipkart profile page](https://github.com/arghadipmanna101/Flipkart_Clone/assets/130668745/bb34d928-0c6a-42b3-9011-1fe226309da9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Anjankumarkamalapur** [comment]
can you pls assign this to me I have worked on this types of issues in my hackathon project I was the web designer so I'm expecting this issue can be resolved easily by me.

**Comment by SuhainaFathimaM** [comment]
@arghadipmanna101 Please assign me this issue

**Comment by Akshit462005** [comment]
I kindly request to be assigned to this issue. As a Technical Executive at the IEEE CUIET Organization, I am well-positioned to address this matter. I am committed to delivering optimal results and have prior experience with similar projects, which I believe will enable me to make a meaningful contribution.

reference for prior work / projects :-|
https://www.linkedin.com/in/akshit-verma-596a0824b/
