### ISSUE TITLE
BUG: In dark mode the website is not clearly visible.

### ISSUE THREAD

**Issue by rohit8289** [arghadipmanna101/Flipkart_Clone#585]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

While using this website in dark mode, the icons are not clearly visible. Specially, the drop-down menu in 3 dots icon. That icon is not visible at all. There are images in which the text is not visible like Electronics.
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/112422573/51cb4ccc-aa4b-40b5-81d9-4c75fcaf1340)
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/112422573/1b2e29af-b15e-48a7-9f40-44b2d8e3fc99)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [x] I want to work on this issue

**Comment by grasyPatel** [comment]
Hello @rohit8289 , i want to work on this issue under gssoc'24 Contributor, please assign me this issue.

**Comment by SuhainaFathimaM** [comment]
@arghadipmanna101 I will fix this issue.. Please assign me this issue

**Comment by rohit8289** [comment]
@arghadipmanna101 assign me once again i will fix this..

**Comment by MangaFlood** [comment]
hello, I'm a GSSOC'24 contributor and I would like to solve this issue for you and improve your website visibility in dark mode @arghadipmanna101

**Comment by Rishitatripathi** [comment]
I would like to work on this issue, Please assign it to me under GSSOC 2024

**Comment by AnirbanChattopadhyay-2004** [comment]
Hello @arghadipmanna101 , i want to work on this issue under gssoc'24 Contributor, please assign me this issue. I will asap after being assigned,

**Comment by K-21** [comment]
@arghadipmanna101 @rohit8289 can you assign me this issue

**Comment by Priyamjain1105** [comment]
Hi @arghadipmanna101 ,

I'd like to work on issue #585. Can you please assign it to me?

Thanks

**Comment by lovelymahor** [comment]
i want to work on this issue under gssoc'24 Contributor, please assign me this issue. I will asap after being assigned,

**Comment by Sayantan-Karmakar** [comment]
I want to work on this issue under GSSOC'24. Kindly assign me this.

**Comment by mdshameera** [comment]
Hi @arghadipmanna101 , I would like to work on this issue by modifying some styles in the code. Please assign this to me. I would love to contribute.

**Comment by DakshantJain** [comment]
Hello @K-21,

I loved your **beautifully** designed website! I noticed a few areas where **improvements** could make it even more **amazing**. I'd be thrilled to help enhance its look and functionality for the best results.

Please consider **assigning** this task to me—I guarantee you'll be pleased with the outcome.

Thank you!

Best,
Dakshant Jain
