### ISSUE TITLE
BUG: Changing twitter logo in footer section

### ISSUE THREAD

**Issue by harikasayani** [arghadipmanna101/Flipkart_Clone#586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Logo of twitter is not correct.
I want to work on this issue.
Please assign me this issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ANIRUDH130903** [comment]
good morning sir can i work on this issue.
@arghadipmanna101 .

**Comment by PrakarshSingh5** [comment]
good morning sir I want to work on this issue plz assign me

**Comment by ananyag309** [comment]
Hi, I hope this message finds you well.

I am writing to express my interest in contributing to the issue. I am enthusiastic about participating in GSSoC'24 and believe that working on this issue will allow me to make a meaningful contribution to the project.

Could you please assign this issue to me under GSSoC'24?

Thank you for considering my request.

**Comment by neharikarout** [comment]
@arghadipmanna101 sir , if it is not closed yet , can you please assign it to me?
