### ISSUE TITLE
Adding animations in the home page

### ISSUE THREAD

**Issue by Sathya-reddy1658** [arghadipmanna101/Flipkart_Clone#59]
i can add animations and micro interactions in the home page to create to more engaging webpage

**Comment by arghadipmanna101** [comment]
assigned you @Sathya-reddy1658

**Comment by parth3083** [comment]
I can add good animation to home page .
I will add using gasp animation.
I am a frontend developer.
I have experienced of 6 months in frontend and has done an internship as frontend intern.

**Comment by SuhainaFathimaM** [comment]
Hi @arghadipmanna101,
I am good at frontend development .
I'd like to take opportunity to "Add animations in the home page"
 I'm confident that I can implement that..

Looking forward to your response.

Best regards

**Comment by Rish-tech1** [comment]
I would like to work on this issue. Pls assign me this!!
