### ISSUE TITLE
BUG: Adding payment options at the end after choosing an item.

### ISSUE THREAD

**Issue by srihitha225h9** [arghadipmanna101/Flipkart_Clone#598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

For making the items payment brought by the customer and enhance its features to look alike as actual Flipkart.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by amitkumar2308** [comment]
Hey! I'm Amit . I have good knowledge about development things. Assign this issue to me so that i start my contribution

**Comment by lassmara** [comment]
Please assign me this issue.
