### ISSUE TITLE
Readme file upgrade 

### ISSUE THREAD

**Issue by arghadipmanna101** [arghadipmanna101/Flipkart_Clone#6]
- .add how to contribute.
- add some interesting pic which related to the sight.
- add contributors.

**Comment by arghadipmanna101** [comment]
@Meetjain1 go ahead

**Comment by Meetjain1** [comment]
sure , let me know is there any pic you want to add in readme.md file

**Comment by Meetjain1** [comment]
OK

**Comment by shailifadadu** [comment]
Hey @arghadipmanna101 I would also like to work upon this issue. I'll add some 3D emojis so that readme looks responsive..

**Comment by arghadipmanna101** [comment]
> Hey @arghadipmanna101 I would also like to work upon this issue. I'll add some 3D emojis so that readme looks responsive..

@shailifadadu you will assign this issue after @Meetjain1 completes. ok

**Comment by Meetjain1** [comment]
@arghadipmanna101 please label this issue as GSSOC24

**Comment by arghadipmanna101** [comment]
> @arghadipmanna101 please label this issue as GSSOC24

ok man.. 😊

**Comment by Meetjain1** [comment]
Thankyou @arghadipmanna101 sir

**Comment by Gokilp** [comment]
please assign to me

**Comment by arghadipmanna101** [comment]
> please assign to me

what do you want to update?

**Comment by Gokilp** [comment]
i added 

.add how to contribute.
add some interesting pic which related to the sight.
add contributors.

**Comment by Gokilp** [comment]
please assign to me

**Comment by Gokilp** [comment]
currently working on issues 

please Give a me details added read me file

**Comment by arghadipmanna101** [comment]
ok go ahead. and make the readme file attractive ok @Gokilp

**Comment by shailifadadu** [comment]
@arghadipmanna101 I've modified readme file. Can you just review it #99

**Comment by Gokilp** [comment]
@arghadipmanna101  please review my pr

**Comment by arghadipmanna101** [comment]
done

**Comment by AditiJeena** [comment]
Can you please assign me this issue

**Comment by arghadipmanna101** [comment]
already solved
