### ISSUE TITLE
BUG: Improvement of Font Styles in Content and Headings on the Web Page

### ISSUE THREAD

**Issue by divyalaldinani** [arghadipmanna101/Flipkart_Clone#600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The current font styles used for both content and headings on the web page are not optimally enhancing readability, user engagement, or the overall aesthetic appeal of the site. This issue affects user experience and may lead to higher bounce rates and lower time spent on the page.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Kaira202** [comment]
Hey @arghadipmanna101, 
I'm interested in HTML, CSS and JS, please assign me this task. I am thriving to do it with my full potential.
