### ISSUE TITLE
Hover size in header section

### ISSUE THREAD

**Issue by Ishmeetkaur36** [arghadipmanna101/Flipkart_Clone#604]
the size of the hover effects over the profile , become  a seller and cart buttons are not of equal size.

**Comment by HimanshuGolyan01** [comment]
Please assign me this issue @arghadipmanna101

**Comment by thisismevri** [comment]
i want to work on this issue please assign this issue to me sir @arghadipmanna101 i will be highly obliged if you let me resolve this issue

**Comment by DhruvJohri** [comment]
please assign this to me @arghadipmanna101
