### ISSUE TITLE
[Enhancement] Fixing the NavBar

### ISSUE THREAD

**Issue by carolinelall** [arghadipmanna101/Flipkart_Clone#606]
### Describing the feature

Navbar needs to be modified inorder to enhance user experience. Following changes needs to be made -

 1) Navbar should remain fixed at the top of the screen during scrolling
 2) Adding hover effects on the navbar items
 3) Applying CSS transition 

@arghadipmanna101 Sir pls assign this issue to me..

### ScreenShot

![WhatsApp Image 2024-05-17 at 9 15 06 PM](https://github.com/arghadipmanna101/Flipkart_Clone/assets/51926095/c2badb9b-66be-4138-9bc7-89e375e77a45)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harsha19-08** [comment]
I would like to work on this issue. Can you assign it to me under GSSOC24

**Comment by kashnx** [comment]
I would like to work on this issue. Can you assign it to me under GSSOC24

**Comment by Aditi-Gupta-dev** [comment]
i still finds this navbar not responsive , i would like to work on this if you assign this issue to me

**Comment by Sajiyasiddiqui** [comment]
I want to work on this issue please assign me.

**Comment by Akshit462005** [comment]
please assign this issue to me 
I would like to work on this issue. Providing you with best results
