### ISSUE TITLE
Navbar is not proper

### ISSUE THREAD

**Issue by kartikmehta18** [arghadipmanna101/Flipkart_Clone#609]
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/125860170/38319bb8-d7bb-4b34-a649-1665d26e0344)
Navbar is not proper can u plz assign me this

**Comment by annuk123** [comment]
hi, I'm Annu Kumari
I want to work on this issue

**Comment by ThakurPrad33p** [comment]
Assign me to fix the issue related to navbar.

**Comment by Sakshi-gupta66** [comment]
I can work on it .Please assign it to me

**Comment by snehasaha1101** [comment]
please let me work in this project

**Comment by kashnx** [comment]
I want to work on this issue. Please assign it to me.

**Comment by lassmara** [comment]
Please assign me this issue.

**Comment by lovelymahor** [comment]
I would like to work on this issue. Can you assign it to me under GSSOC24

**Comment by HJ2207** [comment]
The Navbar requires some changes like on hovering mouse over "profile" and then to "become a seller", the transition effect is not smooth. Also, the day/night mode is a little bit too down, coming out of the bar line a little bit. I would like to work on this issue. Can you please assign it to me.

**Comment by Akshit462005** [comment]
please assign this issue to me
I would like to work on this issue.

**Comment by ashit06** [comment]
want to work upon this issue plz assign it to me .

**Comment by ashit06** [comment]
I want to contribute to this project @arghadipmanna101
