### ISSUE TITLE
Adding logos of Twitter, Youtube ,facebook in the footer(FOLLOW US ON) instead of text

### ISSUE THREAD

**Issue by Shanukumar2929** [arghadipmanna101/Flipkart_Clone#61]
I want to improve user experience so please assign this issue to me under gssoc'24

![Screenshot (608)](https://github.com/arghadipmanna101/Flipkart_Clone/assets/98840506/86c59a5c-05e7-443d-b309-f0447209f535)

**Comment by Kashish0047** [comment]
Can you please assign this issue to me?

**Comment by arghadipmanna101** [comment]
go ahead @Shanukumar2929 . you have been assigned

**Comment by Shanukumar2929** [comment]
Thank You . Working on it!!

**Comment by PoojaGadagi08** [comment]
Hello @arghadipmanna101 sir
I would like to work on this issue as a contributor to the GSSOC. please assign this to me!
I have relevant skills that definitely help to enhance the website.

**Comment by parth3083** [comment]
Assign me the issue, I have the make the whole scrolling a smooth scrolling and will also increase the user experience.
I am frontend developer and have 6 months of experience with this .
Please assign me this issue.

**Comment by arghadipmanna101** [comment]
> Assign me the issue, I will make the whole scrolling a smooth scrolling and will also increase the user experience. I am frontend developer and have 6 months of experience with this . Please assign me this issue.

You Create a new issue and describe that which update you want to solve. ok

**Comment by SuhainaFathimaM** [comment]
Hi @arghadipmanna101,
I am good at frontend development .
I'd like to take opportunity to "Add logos in footer
 I'm confident that I can implement that..

Looking forward to your response.

Best regards

**Comment by paridhi1509** [comment]
Please assign this issue to me as i would like to work on it and i have prior experience in the same

**Comment by arghadipmanna101** [comment]
done.
