### ISSUE TITLE
I want to fix the footer

### ISSUE THREAD

**Issue by 2115425Amar** [arghadipmanna101/Flipkart_Clone#610]
### Describe the feature

Footer needs to be modified inorder to enhance user experience.

1.The height of the footer is too large and need to be fix.
2.Content are not in sequence.
3.list points are to be removed.
4.Font and styling need to be change.

### Add ScreenShots

#Before
![Screenshot (433)](https://github.com/arghadipmanna101/Flipkart_Clone/assets/113373133/f2f78811-6986-4ac7-8841-4fe9c4d79129)

#After
![Screenshot 2024-05-17 233119](https://github.com/arghadipmanna101/Flipkart_Clone/assets/113373133/2e4115fa-5894-4570-9447-941272032795)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by parthsingla15** [comment]
hey can i work on this issue please assign it to me

**Comment by juned072** [comment]
I want to Work on this issue please assign it to me

**Comment by 1404honey** [comment]
I want to work on this issue because the footer is not proper I can improve it by giving my best.Please assign it to me @arghadipmanna101

**Comment by SaiKishor66** [comment]
I want to work on this issue please assign me

**Comment by kashnx** [comment]
I would like to work on this issue. Can you assign it to me under GSSOC24

**Comment by DhruvJohri** [comment]
please assign this issue to me @arghadipmanna101

**Comment by aggrhythm** [comment]
please assign this issue to me @arghadipmanna101

**Comment by Purvi47** [comment]
@arghadipmanna101 plz assign this issue to me

**Comment by lovelymahor** [comment]
I would like to work on this issue. Can you assign it to me under GSSOC24

**Comment by Akshit462005** [comment]
please assign this issue to me @arghadipmanna101 
I would like to work on this issue.

**Comment by ashit06** [comment]
I Want to work upon this issue please assign it to me ,also I have some experience in solving this type of issue.
