### ISSUE TITLE
Feat: Add GIft Cards Page

### ISSUE THREAD

**Issue by Sharmaji513** [arghadipmanna101/Flipkart_Clone#612]
### Describe the feature

**### Description of the Feature: Feature Name: Add GIft Card sPage**
Users are currently experiencing an issue where product category images are absent on the Gift Cart page. This absence hinders visual navigation and comprehension, making it difficult for users to browse and understand the product offerings.

**### Solution:**
To address this issue, we need to integrate the missing images and update the links for a seamless browsing experience. This task includes implementing and modifying the design to match the official site.

@arghadipmanna101, could you please assign me  this issue by implementing and modifying the design to match the official site?

### Add ScreenShots

![2024-05-18-00-12-07](https://github.com/arghadipmanna101/Flipkart_Clone/assets/66481063/99cc1ba3-e265-47da-a549-153916f9d05d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by DhruvJohri** [comment]
please assign this issue to me @arghadipmanna101
