### ISSUE TITLE
BUG:Heading and corner products are out of the screen and not visible clearly

### ISSUE THREAD

**Issue by mohangolakoti** [arghadipmanna101/Flipkart_Clone#619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello @arghadipmanna101, Isuue at latest deals section
-The heading of that section hide into screen
-The Corner product images are not align properly

Screenshot of Issue:
![head](https://github.com/arghadipmanna101/Flipkart_Clone/assets/116739999/904fb052-3e46-454f-aa09-c85ef351ea48)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ANIRUDH130903** [comment]
GOOD MORNING SIR 
PLS ASSIGN ME THIS ISSUE @arghadipmanna101 .I want to work on this .
