### ISSUE TITLE
Feat: reCAPTCHA Implementation

### ISSUE THREAD

**Issue by antriksh-9** [arghadipmanna101/Flipkart_Clone#621]
### Describe the feature

Implementing reCAPTCHA on the website will help in enhancing security, preventing spam and unauthorized access, protecting user data.
This also helps in preventing automated bots from accessing or submitting forms on the website.

### Add ScreenShots

![Screenshot 2024-05-18 113014](https://github.com/arghadipmanna101/Flipkart_Clone/assets/132576984/fc354d37-6892-4b8f-9c81-b64c6d7621ad)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Riya-221** [comment]
please assign this task to me. "I am happy to help."! @arghadipmanna101

**Comment by RekhaKushwaha01** [comment]
I can solve this. Please assign me this issue.

**Comment by TechSenseiX** [comment]
Kindly assigned this issue to me. I will fix it

**Comment by tanishka786** [comment]
I would like to contribute in this project , so please assign this issue to me .

**Comment by bhuvangoel04** [comment]
Please assign me this issue

**Comment by mdshameera** [comment]
Please assign this issue to me. I can solve this issue.

**Comment by Aryan-Shan** [comment]
I am experienced with we development and can easily add this feature please assign it to me.
