### ISSUE TITLE
BUG:The size of all carousels and containers of products is inconsistent

### ISSUE THREAD

**Issue by Gresey** [arghadipmanna101/Flipkart_Clone#624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The carousels and product containers across the website display inconsistent sizes, leading to a disjointed user experience. This inconsistency affects the overall aesthetic and functionality of the site, causing the following issues:
Visual Discrepancies: The carousels and product containers do not align properly, resulting in uneven spacing and misalignment with other elements on the page.
User Experience: The inconsistent sizing disrupts the flow of the website, making it difficult for users to navigate and engage with the content smoothly

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by lassmara** [comment]
Please assign me this issue.
