### ISSUE TITLE
BUG: The nav items are not visible in dark mode

### ISSUE THREAD

**Issue by Aanyaa26** [arghadipmanna101/Flipkart_Clone#625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/128315909/43b38641-e9b0-4c4d-b129-77a7baa9f64e)

the items are not visible in dark mode which is a major bug that needs to be sorted!
Please assign me this issue

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by mehrun171** [comment]
I am interested in this project...Please assign me this issue

**Comment by arghadipmanna101** [comment]
Go ahead @Aanyaa26

**Comment by Rishikesh63** [comment]
@arghadipmanna101  is this issue fixed if  not can you please assign to me

**Comment by ashit06** [comment]
@arghadipmanna101 is this issue fixed if not can you please assign to me
