### ISSUE TITLE
[FEATURE]: Assistant logo is not static

### ISSUE THREAD

**Issue by ujj654** [arghadipmanna101/Flipkart_Clone#626]
### Describe the feature

While scrolling the website your assistant logo in not being static it moves up with the scrolling of the website. So it should be static during scrolling of the website for make the better user experience.

### Add ScreenShots

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/81877649/826898a8-d404-4cf6-8315-cc5a1d6b229b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ujj654** [comment]
@arghadipmanna101  Please assign this issue to me i want to work on this issue. #GSSoc'24

**Comment by ujj654** [comment]
@arghadipmanna101 Please look and merge the PR.

**Comment by lovelymahor** [comment]
i want to work on this issue under gssoc'24 Contributor; please assign me this issue. I will asap after being assigned.
