### ISSUE TITLE
[FEATURE]: Search cancel button

### ISSUE THREAD

**Issue by ujj654** [arghadipmanna101/Flipkart_Clone#627]
### Describe the feature

we have to add a search cancel button [x] in the the search bar because it will improve the user experience of the website.

### Add ScreenShots

Problem:- 

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/81877649/5ec3e3c4-f016-4b82-afbf-9260fa15e969)

Solution:-

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/81877649/e2b882e1-822d-48ee-9301-2b6a89ffd88e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ujj654** [comment]
@arghadipmanna101 Please assign this issue to me i want to work on this issue. #GSSoC'24

**Comment by n14rishitha** [comment]
Hi @arghadipmanna101 
I would like to work on this issue . so please assign this task to me under the label gssoc24 and level1,2,or 3

**Comment by ujj654** [comment]
Issue no #627 has been fixed. Please merge it with appropriate label.
