### ISSUE TITLE
DOC:  Add Pull Request Template

### ISSUE THREAD

**Issue by officeneerajsaini** [arghadipmanna101/Flipkart_Clone#629]
#### Describe the issue
Without a proper pull request (PR) template, contributors sometimes submit PRs without providing adequate descriptions of the changes they have made. This lack of information makes it challenging for reviewers to understand the purpose and scope of the changes, verify them effectively, and ensure that the code meets the project's standards. Consequently, reviewers often need to spend extra time reviewing the entire codebase, which is inefficient and time-consuming.

#### Steps To Reproduce
1. A contributor raises a PR without using a PR template.
2. The PR lacks a clear description of the changes made.
3. Reviewers have to manually inspect all the code changes to understand their purpose.
4. The review process becomes lengthy and cumbersome.

#### Expected Behavior
When a PR template is used:
- Contributors provide a clear and concise description of the changes made.
- The template helps outline what areas of the code were modified and why.
- Reviewers can quickly understand the context of the changes.
- The review process becomes more efficient and less time-consuming.

#### Additional Information
Implementing a PR template can significantly improve the efficiency of the code review process. A well-defined template should prompt contributors to provide:
- A summary of the changes made.
- The reasons for the changes.
- Any relevant issue numbers or references.
- Instructions for testing the changes.
- Any additional notes or context that might help the reviewers.

By using a PR template, we can ensure that all necessary information is provided upfront, allowing reviewers to focus on the quality and correctness of the code rather than spending excessive time deciphering what changes have been made and why. This will not only save time for reviewers but also improve the overall quality of the codebase.

### Add ScreenShots

![Screenshot from 2024-05-18 17-42-22](https://github.com/Vijayy-ai/Talker.ai/assets/118799941/74e7b3e1-9dcc-4957-bb65-448eee8b4563)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by vctigerrfab** [comment]
I want to work on this project.Please assign this issue to me.under gssoc24

**Comment by officeneerajsaini** [comment]
@arghadipmanna101 assign to me .

**Comment by Akshitha28112004** [comment]
Hey, I already have the template ready. Can you please assign me this issue under gssoc'24?

**Comment by n14rishitha** [comment]
@arghadipmanna101 I would like to work on this issue . so please assign this task to me under the label gssoc24 and level1,2,or 3

**Comment by suhanipaliwal** [comment]
Duplicate issue. Already worked on #615
