### ISSUE TITLE
Want to add download page under 3 dot section in right side of our website

### ISSUE THREAD

**Issue by PrabhjotBajwa** [arghadipmanna101/Flipkart_Clone#632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@arghadipmanna101 plz assign this issue to me undere gssoc24 label .

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by n14rishitha** [comment]
@arghadipmanna101 I would like to work on this issue . so please assign this task to me under the label gssoc24 and level1,2,or 3

**Comment by PrabhjotBajwa** [comment]
@arghadipmanna101 already done by me under #578 issue plz give label to that merge request
