### ISSUE TITLE
Feat: Improvised cart page.

### ISSUE THREAD

**Issue by Anushi-111** [arghadipmanna101/Flipkart_Clone#634]
### Describe the feature

Hovering over the login button in the Flipkart site leads to a dropdown menu.
This feature can be added in the project.

### Add ScreenShots

![Screenshot 2024-05-18 224511](https://github.com/arghadipmanna101/Flipkart_Clone/assets/154834742/9f2d7a5f-6914-4f68-9da4-3eb969bb5fc3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by vctigerrfab** [comment]
I want to work on this project.Please assign this issue to me.under gssoc24

**Comment by n14rishitha** [comment]
@arghadipmanna101
 I would like to work on this issue . so please assign this task to me under the label gssoc24 and level1,2,or 3
