### ISSUE TITLE
Add wishlist page under profile section 

### ISSUE THREAD

**Issue by PrabhjotBajwa** [arghadipmanna101/Flipkart_Clone#636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@arghadipmanna101 plz assign this issue under label of  gssoc24 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by vctigerrfab** [comment]
I want to work on this project.Please assign this issue to me.under gssoc24

**Comment by n14rishitha** [comment]
@arghadipmanna101 
I would like to work on this issue . so please assign this task to me under the label gssoc24 and level1,2,or 3
