### ISSUE TITLE
BUG: Adding footer to cart page

### ISSUE THREAD

**Issue by SuhainaFathimaM** [arghadipmanna101/Flipkart_Clone#638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/153417476/5701217d-38c4-43c0-ac3d-bce28cae96b8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SuhainaFathimaM** [comment]
@arghadipmanna101 Please assign me this issue

**Comment by pulkit49** [comment]
I can help you with that. Please assign me under GSSOC 2024.

**Comment by Shrav08** [comment]
I can fix this. Please assign the issue to me.

**Comment by n14rishitha** [comment]
@arghadipmanna101 
I would like to work on this issue .I can fix this . so please assign this task to me under the label gssoc24 and level1,2,or 3

**Comment by SuhainaFathimaM** [comment]
@arghadipmanna101 Please label this issue
