### ISSUE TITLE
BUG: Images not properly working

### ISSUE THREAD

**Issue by AtharvKasar04** [arghadipmanna101/Flipkart_Clone#653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/108543702/264f7e19-9773-48c8-a3da-c1677a17388f)

In this section, one image does not have a transparent background and the other images are not even loading, which makes it look not good.
@arghadipmanna101 Can you please assign me this issue under GSSoC'24.
Thank You!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aman7100** [comment]
Can i work on this issue??

**Comment by vctigerrfab** [comment]
I want to work on this project.Please assign this issue to me.under gssoc24
