### ISSUE TITLE
BUG: images quality and size is not perfect 

### ISSUE THREAD

**Issue by uppercircuit** [arghadipmanna101/Flipkart_Clone#656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

images size is not perfectly fitting plus the image quality is not user friendly need improvement in footer section 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by n14rishitha** [comment]
@arghadipmanna101 
I would like to work on this issue . I can do this .so please assign this task to me under the label gssoc24 and level1,2,or 3
