### ISSUE TITLE
BUG: Homepage is not properly responsive

### ISSUE THREAD

**Issue by prasukjain07** [arghadipmanna101/Flipkart_Clone#657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Home page is not responsive, when window size is decreased, the site looks bad.
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/115997785/a491d6a2-0128-44e6-a579-8e1b30675975)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by vctigerrfab** [comment]
I want to work on this project.Please assign this issue to me.under gssoc24

**Comment by pulkit49** [comment]
I can help you with that. Please assign me under GSSOC 2024.

**Comment by Anjankumarkamalapur** [comment]
I would like to contribute to Flipkart clone project by working on making of responsive home page. Could you please assign this task to me?
