### ISSUE TITLE
Add become a seller page as it is not working on right side of your website

### ISSUE THREAD

**Issue by PrabhjotBajwa** [arghadipmanna101/Flipkart_Clone#660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@arghadipmanna101 plz assign this issue to me under gssoc24 label 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by pulkit49** [comment]
I can help you with that. Please assign me under GSSOC 2024.

**Comment by sakshiSakshi77** [comment]
@arghadipmanna101 
Issue : i can work on it by creating seller page , do assign me this issues , i would like to contribute for it

Record
 I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue
