### ISSUE TITLE
BUG: The 3 dots in the navbar (For Dropdown ) are hiding in Dark Mode

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [arghadipmanna101/Flipkart_Clone#661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the dark mode the three dots are hiding due to its dark color that's why it id hiding in the color .
![Screenshot 2024-05-19 104101](https://github.com/arghadipmanna101/Flipkart_Clone/assets/118350936/4cbc6b5b-feb1-48a3-8b53-13eadef91588)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by vctigerrfab** [comment]
I want to work on this project.Please assign this issue to me.under gssoc24
