### ISSUE TITLE
Lots of improvement in Footer section

### ISSUE THREAD

**Issue by PrabhjotBajwa** [arghadipmanna101/Flipkart_Clone#664]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@arghadipmanna101 plz assign this issue to me under gssoc24 label i will update your footer section to next level.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Shristi613** [comment]
@arghadipmanna101 assign this issue to me as i am a contributer in gssoc24

**Comment by Dev-AyushTrivedi** [comment]
@arghadipmanna101 assign this issue to me as i have a strong command on web development i can fix this quickly... i am working as a contributor under gssoc24
