### ISSUE TITLE
Feat:Create  about us page

### ISSUE THREAD

**Issue by agastya3636** [arghadipmanna101/Flipkart_Clone#668]
### Describe the feature

Create  about us page

### Add ScreenShots

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/124435030/c2e73f91-0c88-42ff-82ff-390e165dd137)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by pulkit49** [comment]
I can help you with that. Please assign me under GSSOC 2024.
