### ISSUE TITLE
Inconsistent code formatting

### ISSUE THREAD

**Issue by The-Phoenics** [arghadipmanna101/Flipkart_Clone#67]
Hi, I've noticed that the codebase has inconsistent code indentation which could lead to reduced readability and maintainability. Here's an example of code
https://github.com/arghadipmanna101/Flipkart_Clone/blob/840f514b1b3c7a0e725cdd48aca4af35a8f8c2a8/Product.js#L103-L126

It is a good practise to have consistent code formatting throughtout the project.
To resolve this a tool like Prettier could be used for consistent code formatting.

Here's how it would look like after applied formatting
```js
function Product() {
  collection.map((element) => {
    let box = document.createElement("div");

    let innerbox = document.createElement("div");
    let price1 = document.createElement("span");
    price1.innerHTML = element.price;
    let price2 = document.createElement("span");
    price2.innerHTML = element.actualprice;

    innerbox.append(price1, price2);
    innerbox.className = "innerbox";
    let avatar = document.createElement("img");
    avatar.src = element.img_src;
    avatar.className = "avatar";
    let brand = document.createElement("p");
    brand.innerHTML = element.Brand;
    box.append(avatar, brand, innerbox);
    document.getElementById("collection").append(box);
  });
}
```

I would like to work on this for GSSoC 2024. Could you please assign this issue to me?

**Comment by Justaditi** [comment]
Please assign me this issue .

**Comment by SuhainaFathimaM** [comment]
Hi @arghadipmanna101,
I am good at frontend development .
please assign me this issue..
 I'm confident that I can implement that..

Looking forward to your response.

Best regards

**Comment by The-Phoenics** [comment]
https://github.com/arghadipmanna101/Flipkart_Clone/pull/115

**Comment by shendgeshraddha** [comment]
I would like to work on this for GSSoC 2024. Could you please assign this issue to me??

**Comment by arghadipmanna101** [comment]
the issue solved.
