### ISSUE TITLE
BUG: Spelling errors

### ISSUE THREAD

**Issue by debangi29** [arghadipmanna101/Flipkart_Clone#674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/117537653/8cf6c40e-12eb-4b1b-83fb-0b8be4d080d8)

"EPR Compilance" must be "EPR Compliance" Spelling error

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Akshitha28112004** [comment]
Hey, Can you please assign me this issue under gssoc'24?

**Comment by JanitKumar** [comment]
assign me this issue

**Comment by ahinagangopadhyay** [comment]
I would like to work on this issue.Please assign me this issue under GSSOC'24.

**Comment by debangi29** [comment]
Will there be no levels for this issue under Gssoc?
