### ISSUE TITLE
become a seller not working

### ISSUE THREAD

**Issue by thesri** [arghadipmanna101/Flipkart_Clone#68]
become a seller hover isnt working in the main page or isnt even providing any issue . please assign it under gssoc 24

**Comment by arghadipmanna101** [comment]
ok. go ahead @thesri

**Comment by thesri** [comment]
> ok. go ahead @thesri

how many days will i get to work on it? and where should it direct? to a page where they can give their details?

**Comment by arghadipmanna101** [comment]
> > ok. go ahead @thesri
> 
> how many days will i get to work on it? and where should it direct? to a page where they can give their details?

max 3 days you can take but  make it properly ok.

**Comment by thesri** [comment]
> > > ok. go ahead @thesri
> 
> > 
> 
> > how many days will i get to work on it? and where should it direct? to a page where they can give their details?
> 
> 
> 
> max 3 days you can take but  make it properly ok.

It should point to a separate page? Is it the task?

**Comment by yashika0432** [comment]
assign this task to me

**Comment by PayalKumari10** [comment]
@arghadipmanna101   i want to work on this issues,  can you assign me ?

**Comment by Aradhya-005** [comment]
i would to like to work on this . please assign it to me

**Comment by Anusrita-Karmakar** [comment]
Looking forward to work on this.
Please assign this to me.

**Comment by 21VV1A0541SAILU** [comment]
I woulld like to work on this issue 
can you please assign it to me
