### ISSUE TITLE
BUG: Button not visible in Dark mode

### ISSUE THREAD

**Issue by dharshini2022** [arghadipmanna101/Flipkart_Clone#690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the dark mode, the 3 dots button next to the mode selection button is not visible
![Screenshot 2024-05-19 225258](https://github.com/arghadipmanna101/Flipkart_Clone/assets/123349807/7420818c-44d1-460f-91c2-121e7634335c)
![Screenshot 2024-05-19 225312](https://github.com/arghadipmanna101/Flipkart_Clone/assets/123349807/7339a696-ce4c-4137-af09-237e168f5f25)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by arpit4521** [comment]
Please assign me this issue so that i correct these smalls bug and bring out my best form of front end skills by just using this small change @arghadipmanna101 as i have not got any assigned and wanted to learn

**Comment by dharshini2022** [comment]
@arghadipmanna101 pls assign labels under GSSOC guidelines
![Screenshot 2024-05-31 094333](https://github.com/arghadipmanna101/Flipkart_Clone/assets/123349807/ff818a83-4397-4974-a281-14c29ae29ece)
