### ISSUE TITLE
Feat: Styling the home page

### ISSUE THREAD

**Issue by dharshini2022** [arghadipmanna101/Flipkart_Clone#691]
### Describe the feature

Enhance the home page styles. Make it visually appealing

### Add ScreenShots

![Screenshot 2024-05-19 225517](https://github.com/arghadipmanna101/Flipkart_Clone/assets/123349807/25609fd3-c7e8-4bb1-b83a-ceb7cd5b3c02)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Priyanjali24** [comment]
I want to work on this issue

**Comment by Poonam-Kashyap12** [comment]
I want to work on this issue

**Comment by dharshini2022** [comment]
@arghadipmanna101 Please label this issue under GSSOC 24 guidelines 
![Screenshot 2024-05-31 094333](https://github.com/arghadipmanna101/Flipkart_Clone/assets/123349807/f6eb698b-7b2b-4f73-b48a-739e1aef3442)
