### ISSUE TITLE
contributor

### ISSUE THREAD

**Issue by harsh160311** [arghadipmanna101/Flipkart_Clone#7]
hi i am a open source contributor in gssos 24 can you assign me your project

**Comment by arghadipmanna101** [comment]
> hi i am a open source contributor in gssos 24 can you assign me your project

What upgradation you want to do?

**Comment by harsh160311** [comment]
I need to do it like filpkart with a few changes

**Comment by arghadipmanna101** [comment]
> I need to do it like filpkart with a few changes

What changes?

**Comment by harsh160311** [comment]
Check my pull reqest

**Comment by arghadipmanna101** [comment]
> Check my pull reqest

close the PR and resend the PR.ok

**Comment by ishikat** [comment]
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/72931967/4f680774-c312-4c50-bd2b-1767b1cf533d)
Hii @arghadipmanna101
I would like to enhance this section of the flipkart website by adding hover effect.
can you assign it to me under GSSOC24.
