### ISSUE TITLE
BUG:  Fixing hovering effect

### ISSUE THREAD

**Issue by reshamsai150** [arghadipmanna101/Flipkart_Clone#700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/164533685/cfce0741-39c1-4d96-b5b7-6b5251f87c16)
when hovered on these cards they collide on each other proper hovering effecting is needed or the spacing needs to be changed 
looking forward to contributing on this issue @arghadipmanna101 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Anjankumarkamalapur** [comment]
I would like to contribute to Flipkart_Clone project by working on Fixing hovering effect. Could you please assign this task to me?

**Comment by reshamsai150** [comment]
Assign level label as well as GSSOC label @arghadipmanna101
