### ISSUE TITLE
BUG: HTML/CSS error with wrong choice of font family and wrong size proportion of images used.

### ISSUE THREAD

**Issue by Sheersh01** [arghadipmanna101/Flipkart_Clone#703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The HTML code is not Correct to perfectly fit the CSS applied and moreover the CSS part is also not going with the elements of the page. The font is also not correct and same goes with the color of the elements. The images are of not same size.  Allow me to solve these issues by letting me contribute. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by arpit4521** [comment]
Please assign me this issue so that i correct these smalls bug and bring out my best form of front end skills by just using this small change @arghadipmanna101 as i have not got any assigned and wanted to learn
