### ISSUE TITLE
DOC: Update Contribution Guide with git pull upstream

### ISSUE THREAD

**Issue by Amruta7203** [arghadipmanna101/Flipkart_Clone#706]
### What's wrong with the existing documentation

**Missing Step**: The provided contribution guidelines don't explicitly mention the git pull upstream command.

**Importance of Pulling Updates:** 
This command is essential for fetching the latest changes from the original repository (upstream) and integrating them into your local branch.

**Potential Issues:** 
Without this step, developers might be working on outdated code and their changes might conflict with recent changes made in the original repository. This can lead to merge conflicts and difficulties when creating pull requests.

### Add ScreenShots

Existing DOC does not contain the pull upstream command.
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/116087736/25c54ab6-cfed-44c8-9e76-58c9aa10885f)

The command that needs to be included after "git remote add upstream https://github.com/<original-owner>/Flipkart_Clone/"
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/116087736/566e9e78-9a0e-49a1-b570-72c19de6d959)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Amruta7203** [comment]
@arghadipmanna101 Pls add the relevant gssoc labels.

**Comment by shivathmikavemula** [comment]
@arghadipmanna101  please assign me this issue and provide the gssoc labels.

**Comment by shivathmikavemula** [comment]
I had completed the task 
https://github.com/arghadipmanna101/Flipkart_Clone/pull/888
in the README.md file itself
