### ISSUE TITLE
BUG: FAQ section

### ISSUE THREAD

**Issue by bhumika-1127** [arghadipmanna101/Flipkart_Clone#708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I wanted to add a drop down which when clicked will show the detailed solution of that question. @arghadipmanna101 Kindly assign me this task under GSSOC'24.

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/137604220/93bf9d08-c216-44be-8c7d-a8903784cef8)
 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by 22-0304** [comment]
Can you assign me this issue @arghadipmanna101

**Comment by bhumika-1127** [comment]
@arghadipmanna101 Kindly add the gssoc and level label.
