### ISSUE TITLE
alignment of sections 

### ISSUE THREAD

**Issue by Soumya6Tiwari** [arghadipmanna101/Flipkart_Clone#710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/117037441/a6f091bb-b787-40bf-bc54-8e4b64f92554)
in the above pic we can see that grocery and food is written 2 times and it is also not aligned with rest of the sections ,so we will align it.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Soumya6Tiwari** [comment]
@arghadipmanna101  kindly assign me the above issue

**Comment by Shrutibhargava2004** [comment]
I want to work on this issue
