### ISSUE TITLE
bright and dark modes are hiding the cart items

### ISSUE THREAD

**Issue by shivathmikavemula** [arghadipmanna101/Flipkart_Clone#712]
### Describe the feature

bright and dark modes are hiding the cart items

### Add ScreenShots

![Screenshot (9)](https://github.com/arghadipmanna101/Flipkart_Clone/assets/133566953/75dc3ebc-5d79-4d74-924a-c4db07537ef1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shivathmikavemula** [comment]
I wanted to work on the issued raised.

**Comment by Shrutibhargava2004** [comment]
I want to work on this issue
