### ISSUE TITLE
Feat: Changing the look of Top deal section

### ISSUE THREAD

**Issue by SadafKausar2025** [arghadipmanna101/Flipkart_Clone#715]
### Describe the feature

I have made card and added images and also button to add to card with icons
and also I have written the imformation related to that content
now the top deal section look very good

### Add ScreenShots

https://github.com/arghadipmanna101/Flipkart_Clone/assets/137484958/dd3abefa-9fbb-455e-8349-1cf5345ec38c

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SadafKausar2025** [comment]
hey @arghadipmanna101 
can you please assign me this issue?

**Comment by shrutitembhre1** [comment]
@arghadipmanna101 I m interested in this project! Please assign this issue to me !

**Comment by SadafKausar2025** [comment]
@arghadipmanna101 
I have raise the pull request for this issue 
PR NO IS  #716 
can you please merge this PR?

**Comment by Khushico** [comment]
hey @arghadipmanna101
can you please assign me this issue

**Comment by aggrhythm** [comment]
hey @arghadipmanna101
can you please assign me this issue

**Comment by Purvi47** [comment]
@arghadipmanna101 plz assign me this issue

**Comment by Taranpreet10451** [comment]
@arghadipmanna101 I can effectively solve this issue with the best solution according to me and I would also be glad to do so. Please assign me this issue.

**Comment by rashi0409** [comment]
@arghadipmanna101
I am a GSSOC'24 Contributor please assign me the issue. I believe I will be able to do it efficiently
