### ISSUE TITLE
BUG: Flipkart text is not visible in Cart page navbar

### ISSUE THREAD

**Issue by nagalakshmi08** [arghadipmanna101/Flipkart_Clone#718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the cart page, The Flipkart text in Navbar is not being visible because of it's colour.
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/121669832/824e1850-a815-4b80-9c0a-21ca695354b8)
I would like to solve this issue. Please assign me this task under GSSoC'24. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by tikaram1912** [comment]
Please aasign this issue to me. I want to work on it under GSSoC'24.
