### ISSUE TITLE
Search bar not visually appealing

### ISSUE THREAD

**Issue by ManasiDhotkar** [arghadipmanna101/Flipkart_Clone#721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Increasing the width of the search bar can make it more visually appealing and user-friendly.

![Screenshot 2024-05-21 164645](https://github.com/arghadipmanna101/Flipkart_Clone/assets/99855497/de766dc1-8acc-4e06-b333-69b912645688)

**Just like :** 
![Screenshot 2024-05-21 170733](https://github.com/arghadipmanna101/Flipkart_Clone/assets/99855497/e72ef91d-4af8-490c-8f6f-2da26ea40568)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ManasiDhotkar** [comment]
hey @arghadipmanna101 
can you please assign me this issue?

**Comment by lovelymahor** [comment]
Please assign me this issue.. I would like to work on this issue

**Comment by Mehak1524** [comment]
Please assign this issue to me , I would like to work on it under GSSoC .
