### ISSUE TITLE
BUG: Problem with drop down option

### ISSUE THREAD

**Issue by rko0211** [arghadipmanna101/Flipkart_Clone#722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![dropdown](https://github.com/arghadipmanna101/Flipkart_Clone/assets/97402824/f970133f-e249-4745-832d-acbc53ff8733)

When click on more link button a drop down box is appeared which is not properly implemented. So, kindly review my Issue and assign me this issue under GSSOC24.

Thank you.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by lovelymahor** [comment]
Please assign me this issue.. I would like to work on this issue
