### ISSUE TITLE
BUG: Change the styling of the products listed on the homepage

### ISSUE THREAD

**Issue by Bhavishya2601** [arghadipmanna101/Flipkart_Clone#723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The styling of the products listed on the homepage is not the same as it is of Flipkart
I want to work on this issue, hope you would assign this task to me 

![Screenshot 2024-05-21 195137](https://github.com/arghadipmanna101/Flipkart_Clone/assets/147748752/30e3bd86-4d3e-4295-ab05-af4430c47a87)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by tikaram1912** [comment]
Please aasign this issue to me. I want to work on it under GSSoC'24.
