### ISSUE TITLE
Feat: Want to add a product detail page.

### ISSUE THREAD

**Issue by Hardikchandra** [arghadipmanna101/Flipkart_Clone#724]
### Describe the feature

When clicking on any product it just refreshes the (home page) . because there is no product detail page which an e-commerce website must have.
@arghadipmanna101 , I want to contribute to this project by creating a product detail page for the product on your  project.
which consist of ;

1. Price.
2. Images.
3. Description.
4. Reviews.
5. Star ratings.
6. any many more.

 

### Add ScreenShots

n/a

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by adii9410** [comment]
please assifn me this task i will solve the issue of image loading

**Comment by Kaustubhraidev** [comment]
I want to add following stuffs in product detail section: - 

- rating
- original and discount price
- review  
- high quality images
- favorites
- available sizes
- types of materials used
- how to handle
- and many more

**Comment by DivyaCodingWorld** [comment]
Hii,
I'm interested to work on this issues .Please assigned to me on this project.

**Comment by Hardikchandra** [comment]
@arghadipmanna101 please add a gssoc level tag.

**Comment by Hardikchandra** [comment]
@arghadipmanna101 , I Want to contribute on this issue under GSSoc24. Please add the level tag .
