### ISSUE TITLE
BUG:Icons/Images are not loading.

### ISSUE THREAD

**Issue by Hardikchandra** [arghadipmanna101/Flipkart_Clone#725]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Profile section icon not missing or unable to load , and when click on it other many icons also not apearing.
Hence, resulting in a bad UI.
<img width="958" alt="Screenshot 2024-05-21 203054" src="https://github.com/arghadipmanna101/Flipkart_Clone/assets/159153956/77baad7f-9097-4e92-9655-45ac347f0a48">
<img width="252" alt="Screenshot 2024-05-21 203119" src="https://github.com/arghadipmanna101/Flipkart_Clone/assets/159153956/850fb17d-e0d3-4a88-a19e-776287285fb6">

@arghadipmanna101 , want to work on this Bug/Issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by adii9410** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue
please assign me this task i will fix the issue

**Comment by Khushico** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue
Assign this task to me i will fix the bug

**Comment by Hardikchandra** [comment]
@arghadipmanna101 , I Want to contribute on this issue under GSSoc24. Please add the level tag .
