### ISSUE TITLE
BUG:Navbar is not properly visible in mobile view 

### ISSUE THREAD

**Issue by meetarora10** [arghadipmanna101/Flipkart_Clone#727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The navbar contains overlapping and repeated text and is also clear in responsive view.

![Screenshot (438)](https://github.com/arghadipmanna101/Flipkart_Clone/assets/143121854/f5dcb987-77c9-4564-b1cc-19d963522204)
Assign this task to me and I will add proper styling to the navbar which will be suitable for various devices.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by tikaram1912** [comment]
Please assign this issue to me. I want to work on it under GSSoC'24.
