### ISSUE TITLE
Add more section of pictures in our landing page of Flipkart 

### ISSUE THREAD

**Issue by PrabhjotBajwa** [arghadipmanna101/Flipkart_Clone#731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@arghadipmanna101 assign this issue to me under label gssoc24 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Rishitatripathi** [comment]
I would like to work on this issue, Please assign it to me under GSSOC 2024
