### ISSUE TITLE
BUG: Light mode and dark mode are switched

### ISSUE THREAD

**Issue by aditisingh02** [arghadipmanna101/Flipkart_Clone#732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When clicking for the option of dark mode we're getting light mode
Also the button for switching between these modes is misalligned

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Shrutibhargava2004** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue
