### ISSUE TITLE
Feat: Improving Home page

### ISSUE THREAD

**Issue by SrijaVuppala295** [arghadipmanna101/Flipkart_Clone#735]
### Describe the feature

The Home page  needs to improve , i want to add login button to the navbar, and improve the navbar color to white, add images for profile section and grocery section. 

### Add ScreenShots

Adding  image for grocery

![Screenshot 2024-05-22 144518](https://github.com/arghadipmanna101/Flipkart_Clone/assets/140592148/512854cc-4ae5-4409-b9e5-fc094c94d89a)

Adding image for profile section 

![Screenshot 2024-05-22 144540](https://github.com/arghadipmanna101/Flipkart_Clone/assets/140592148/7815368a-3bcb-406f-9cce-b19e392418d2)

Want to add login button and dark mode toggle is not in the correct format and improve the navbar colour to white  to look attractive and responisve

![Screenshot 2024-05-22 144914](https://github.com/arghadipmanna101/Flipkart_Clone/assets/140592148/eb20c334-a2b8-4d8a-8a92-e55a7dbeb87d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SrijaVuppala295** [comment]
@arghadipmanna101 ,please /assign this issue

**Comment by jyoshnadasari** [comment]
good evening sir.
please assign this issue

**Comment by Kaira202** [comment]
Can you please assign me this issue?

**Comment by SrijaVuppala295** [comment]
Please add labels @arghadipmanna101
