### ISSUE TITLE
BUG: The Grocery Image does not appear at the page

### ISSUE THREAD

**Issue by MuraliDharan7** [arghadipmanna101/Flipkart_Clone#738]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Image for Grocery category is not appear or having error at there.

Please assign this task to me under GSSoC'24.

![flipkare issue](https://github.com/arghadipmanna101/Flipkart_Clone/assets/130668745/7275451a-189d-4f48-985e-0ce88da5d24e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by lovelymahor** [comment]
Please assign me this issue.. I would like to work on this issue
