### ISSUE TITLE
BUG: The Hover effect is not there for electronics

### ISSUE THREAD

**Issue by MuraliDharan7** [arghadipmanna101/Flipkart_Clone#739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The hover effect is not here in the electronics page.
I can add the Hover effect for each category which will make this page more responsible and creative.

Please assign this task to me under GSSoC'24.

![flipkart issue 2](https://github.com/arghadipmanna101/Flipkart_Clone/assets/130668745/98a7132a-04e1-4e59-8414-54879a6b15ac)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by adii9410** [comment]
I can add the Hover effect for each category which will make this page more responsible and creative.

Please assign this task to me under GSSoC'24.

**Comment by KomalSrivastava** [comment]
@arghadipmanna101 Embark on a journey of creativity and functionality with a mission to enhance the user experience on our Electronics page! Picture this: with a simple hover, users will be treated to an interactive and visually captivating experience unlike any other.

I propose to add a stunning hover effect to each category on the Electronics page, elevating its responsiveness and injecting a touch of innovation. Imagine seamlessly gliding your cursor over each category, only to be met with an enticing visual cue that beckons exploration and engagement.

I'm eager to take charge of this task and breathe new life into our Electronics page. Please entrust me with this opportunity under GSSoC'24, where I'll infuse creativity and functionality into every pixel. Together, let's craft an experience that leaves users spellbound and coming back for more!
