### ISSUE TITLE
[Feature] : Product details page

### ISSUE THREAD

**Issue by sivaprasath2004** [arghadipmanna101/Flipkart_Clone#742]
### Describe the feature

- If the product can be click that was not open the product details page.
- In the product details page contains product detail and `cart` option.
- please assign me...
- I will work on this project.

### Add ScreenShots

[Screencast from 2024-05-23 08-21-53.webm](https://github.com/arghadipmanna101/Flipkart_Clone/assets/121082414/d61b5398-f67f-4755-b406-e5d9ecd2310c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by KomalSrivastava** [comment]
@arghadipmanna101 Introducing an exciting new feature enhancement: now, with just a simple click, users can effortlessly navigate to the product details page directly from any clickable product item. Gone are the days of frustration when you can't easily access the information you need!

Once on the product details page, users will find a treasure trove of information about the product, along with convenient options to add it to their cart seamlessly. No more navigating through multiple pages or cumbersome processes—everything you need is right at your fingertips!

I'm thrilled to take on this challenge and enhance user experience. Please assign me this task, and I'll dive right in! Check out the accompanying screenshots and screencast for a sneak peek of what's to come.
Of course, I wholeheartedly agree to abide by this project's Code of Conduct and am eager to contribute as a GSSOC'24 participant. Let's make this feature shine!
