### ISSUE TITLE
Auto commenting feature for new PR raised

### ISSUE THREAD

**Issue by suhanipaliwal** [arghadipmanna101/Flipkart_Clone#744]
This feature aims to address the problem of delayed and inconsistent communication following the raising of PRs. By automatically commenting on PRs as soon as they are raised, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

Could you please assign me this issue under GSSOC'24.

**Comment by KomalSrivastava** [comment]
@arghadipmanna101 Introducing a groundbreaking feature crafted to revolutionize the way we communicate following the submission of PRs! No more waiting in frustration for acknowledgment. With this innovation, comments are automatically injected into PRs the moment they're created, ensuring contributors receive instant recognition for their dedication. Say hello to a dynamic, supportive collaboration environment that ignites passion and drives ongoing engagement from all contributors.

Would you be so kind as to assign me this captivating issue under GSSOC'24?

**Comment by suhanipaliwal** [comment]
Please add the labels of gssoc and appropriate level as per gssoc guidelines on this issue.
