### ISSUE TITLE
BUG:Navbar Grocery Item Misalignment and Missing Icon

### ISSUE THREAD

**Issue by Pranjalidhale0711** [arghadipmanna101/Flipkart_Clone#747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Description:
The "Grocery" item in the navbar is not properly aligned with the other text items. Additionally, the "Grocery" item is missing an icon, which makes it inconsistent with the other items in the navbar.

Steps to Reproduce:
1]Open the website.
2]Look at the navbar at the top of the page.
3]Observe the alignment of the "Grocery" text compared to other items.
4]Notice the absence of an icon next to the "Grocery" item.

Expected Behavior:
The "Grocery" text should be aligned properly with the other items in the navbar. There should also be a consistent icon next to the "Grocery" item, similar to other navbar items.

Actual Behavior:
The "Grocery" text is misaligned with other navbar items and does not have an icon.

Screenshot:
<img width="1437" alt="Screenshot 2024-05-23 at 12 56 57 PM" src="https://github.com/arghadipmanna101/Flipkart_Clone/assets/123875758/574424b3-e49b-4c07-9874-9c0198997e2c">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Pranjalidhale0711** [comment]
Please assign this issue to me so that i can fix it

**Comment by Khushico** [comment]
i have practiced a lot in frontend part and i can fix this issue! pls assign this issue to me
