### ISSUE TITLE
BUG:Navbar Button Hover Effect - Icons Not Visible and Misaligned

### ISSUE THREAD

**Issue by Pranjalidhale0711** [arghadipmanna101/Flipkart_Clone#748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Description:
When hovering over buttons in the navbar, their icons are not visible and the alignment is also not proper. This affects the overall user experience and visual consistency of the navbar.

Steps to Reproduce:
1]Open the website.
2]Navigate to the navbar at the top of the page.
3]Hover over any button in the navbar.
4]Observe the visibility and alignment of the icons.

Expected Behavior:
When hovering over a button in the navbar, the icon should remain visible and the alignment should be consistent with other elements in the navbar.

Actual Behavior:
Upon hovering over a button in the navbar, the icon becomes invisible and the alignment is off.

Screenshots:
<img width="1437" alt="Screenshot 2024-05-23 at 12 56 57 PM" src="https://github.com/arghadipmanna101/Flipkart_Clone/assets/123875758/4930c76e-e0a6-40e8-ac04-78969bfdde1b">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Pranjalidhale0711** [comment]
Please assign this issue to me I will fix it

**Comment by lovelymahor** [comment]
I want to work on this issue please assign it to me

**Comment by Sanchayita23104** [comment]
I would love to work on this issue. Please assign me this task

**Comment by TechSenseiX** [comment]
Kindly assigned this issue to me. I will fix it

**Comment by Isha2923** [comment]
Kindly assign this issue to me. I have fixed it.
