### ISSUE TITLE
BUG: Not Responsive on Smaller Screens

### ISSUE THREAD

**Issue by ajaynegi45** [arghadipmanna101/Flipkart_Clone#754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The current website does not adapt well to smaller screen sizes. 

https://github.com/arghadipmanna101/Flipkart_Clone/assets/97536703/3982423e-0d6d-45b9-93c6-de4948b74630

Assign this issue to me.

### Record

- [x] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by TechSenseiX** [comment]
Kindly assigned this issue to me. I will fix the issue and make the website responsive
