### ISSUE TITLE
Feat: Correcting the alignment of the Homepage (Much Necessary)

### ISSUE THREAD

**Issue by Bhavishya2601** [arghadipmanna101/Flipkart_Clone#757]
### Describe the feature

The alignment on the homepage is not correct and doesn't match that of the official flipkart website
So please assign this task to me so that I can correct it's alignment

### Add ScreenShots

![Screenshot 2024-05-23 232249](https://github.com/arghadipmanna101/Flipkart_Clone/assets/147748752/295ffd14-b3b3-41b7-88ed-b4e88b019cf9)
![Screenshot 2024-05-23 232428](https://github.com/arghadipmanna101/Flipkart_Clone/assets/147748752/80799083-23ab-4e63-91b9-7d04649521ba)
![Screenshot 2024-05-23 232440](https://github.com/arghadipmanna101/Flipkart_Clone/assets/147748752/f180d29d-a568-468d-a664-7ebc4959e79a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by 1754riya** [comment]
I would like to contribute to this issue. I will properly align each of the designs and make the necessary fixes. I'll give my best to do this. Please assign me to this task.
