### ISSUE TITLE
BUG: FAQ's on Homepage

### ISSUE THREAD

**Issue by Bhavishya2601** [arghadipmanna101/Flipkart_Clone#758]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The FAQ's on the homepage aren't looking good, moreover it isn't on the official site, I suggest to remove it from there, and can add them in contact us page and also the UI of the FAQ is not the best, so I suggest to change it 

Hope you would assign this task to me

![Screenshot 2024-05-23 232723](https://github.com/arghadipmanna101/Flipkart_Clone/assets/147748752/34aec57c-97a3-4685-835f-9ca6465ce5c1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by FaizanAli192** [comment]
I agree to follow this project's Code of Conduct
I'm a GSSOC'24 contributor
I want to work on this issue
