### ISSUE TITLE
Making the Header part responsive

### ISSUE THREAD

**Issue by Varshi45** [arghadipmanna101/Flipkart_Clone#76]
The header part of the site is odd and needs to be replaced with better working header that is more responsive and suitable for small or large devices equally.

I'm one of the contributors at GsSOC 2024 and I've a good experience of working with Web development and I assure you that I can fix the issue and more minor issues if any.
So please assign this to me.

![Screenshot 2024-05-10 111908](https://github.com/arghadipmanna101/Flipkart_Clone/assets/116535984/a4a1c18f-ca35-4f4a-a08a-716e73dd73e4)

**Comment by arghadipmanna101** [comment]
sure. go ahead @Varshi45

**Comment by SuhainaFathimaM** [comment]
Hi @arghadipmanna101,
I am good at frontend development .
please assign me this issue..
 I'm confident that I can implement that..

Looking forward to your response.

Best regards

**Comment by arghadipmanna101** [comment]
ok. go ahead @SuhainaFathimaM

**Comment by prishviii** [comment]
hey I'm one of the contributors at GSSOC and i'm really good with coding and i assure you to fix this issue and any other issues regarding it.

**Comment by supriyagaut** [comment]
@arghadipmanna101 sir i want to work on this issue please assign to me i assure yo u to fix this issue

**Comment by supriyagaut** [comment]
@arghadipmanna101 i have experience of amazon prime clone, zomato clone ao i can do better for this issue please assign me to this issue
