### ISSUE TITLE
Feat: Design About Us Page

### ISSUE THREAD

**Issue by Hemashree21** [arghadipmanna101/Flipkart_Clone#763]
### Describe the feature

I want to work on designing the About Us page for the website and add the route in the Footer link. I will make the page responsive as well.
@arghadipmanna101 can you please assign this to me?

### Add ScreenShots

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/138188163/25781f37-e1fd-480a-b3c7-f145e270ac20)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by yash21sriv** [comment]
I want to work on this project kindly assign me this project

**Comment by S-i-y-a-g** [comment]
please assign me this issue

**Comment by syma-parween** [comment]
assign me this issue
