### ISSUE TITLE
Feat: Organizing all assets in single folder 

### ISSUE THREAD

**Issue by DhairyaMajmudar** [arghadipmanna101/Flipkart_Clone#764]
### Describe the feature

While exploring the codebase it is found that many assets are  located in the root dir. of the folder structure which is not a good practice of project structure.

Tasks to be done:

- [ ] Add the assets (.png, .jpg, .webp, ). 
- [ ] Modify the import paths in each file for these assets.
- [ ] Adding `alt` text to increase WCAG compliance of the project.

Solution: 

1. In the images folder of the project shift all the assets and change their paths accordingly in the HTML files or any other files where they are imported.
2. Add an `alt` tag to every image this modification will increase the web accessibility of  website allowing a wider range of users to use it. 

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by ravijat2026** [comment]
I want to work on this project kindly assign me this project

**Comment by ravijat2026** [comment]
@arghadipmanna101  can you pls. assign this to me, thanks.

**Comment by Amitanand0123** [comment]
I want to work on this issue kindly assign this to me.

**Comment by Amitanand0123** [comment]
@arghadipmanna101 pls. once have a look and if this looks good to you, can you assign. Thankyou :)
