### ISSUE TITLE
Feat: Login signup pge

### ISSUE THREAD

**Issue by Shivani756** [arghadipmanna101/Flipkart_Clone#765]
### Describe the feature

I want to design a login signup page for customers to keep track of their activities on the website
![signup](https://github.com/arghadipmanna101/Flipkart_Clone/assets/139329176/d04da220-d7db-495e-aba4-47077aa9b871)

### Add ScreenShots

![signup](https://github.com/arghadipmanna101/Flipkart_Clone/assets/139329176/a3305db0-9152-46b5-811a-01fdd46688e4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Shivani756** [comment]
hello @arghadipmanna101 sir..
I would request you to please assign label on this issue

**Comment by arghadipmanna101** [comment]
> hello @arghadipmanna101 sir.. I would request you to please assign label on this issue

After send me your PR i will check the pr and then i will add levels.

**Comment by Shivani756** [comment]
okay sir thank you
