### ISSUE TITLE
Changing UI UX design to the frontend

### ISSUE THREAD

**Issue by SHANMUGAPRIYA-1** [arghadipmanna101/Flipkart_Clone#767]
### Describe the feature

I will make changes to the UI/UX design in to creative manner

### Add ScreenShots

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/123299623/1da0848e-d54f-4078-a5d3-09335a5aa47d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
I am able to make better UI/UX in creative manner please assign this task to me.

**Comment by SHANMUGAPRIYA-1** [comment]
Will you please label this issue
