### ISSUE TITLE
BUG: Carousel images on home page overlap captions on larger screens

### ISSUE THREAD

**Issue by AmulyaJain2004** [arghadipmanna101/Flipkart_Clone#768]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

When viewing the carousel on larger screens, the images overlap with the captions of the items above them. This issue affects the user experience by obscuring important information. On smaller screens, the carousel appears correctly.

Steps to Reproduce:
1. Open the website with the carousel on a desktop or larger screen.
2. Observe that the carousel images overlap with the captions above them.
3. Resize the browser window to a smaller width and height.
4. Notice that the carousel images now appear correctly.

On small width screen: -
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/143023082/d1c0f078-7372-4088-9f24-9d4f1091166b)

On bigger width screen like normal browser window width: -
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/143023082/8e63f11c-fe21-4474-8d7f-90145cffb39a)

Expected Behavior:
The carousel images should not overlap with the captions regardless of screen size. The layout should be responsive and adapt to different screen sizes properly.

I think I can work on this. Please assign me this task under GSSOC 2024.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AnirbanChattopadhyay-2004** [comment]
Please assign this issue to me so that I can have a contribution under gssoc 24.

**Comment by AmulyaJain2004** [comment]
@arghadipmanna101 Sir I was working on this issue but I discovered today that this issue was resolved by "the-indian-hustler" who resolved issue: #726 by pull request: Fixed navbar position issue #871 which was merged yesterday. 
Can I close as this issue as it has resolved?
