### ISSUE TITLE
Feat:Adding icon to the title.

### ISSUE THREAD

**Issue by AnirbanChattopadhyay-2004** [arghadipmanna101/Flipkart_Clone#775]
### Describe the feature

There is no icon in the title of this website,so a favicon icon can be added.Please add labels to this issue and assign this issue to me.

### Add ScreenShots

[Screenshot 2024-05-24 180147](https://github.com/arghadipmanna101/Flipkart_Clone/assets/124513264/33567db5-af4c-4e1f-891d-95cb65d6690f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by syma-parween** [comment]
I want to work of this issue

**Comment by S-i-y-a-g** [comment]
please assign me this issue

**Comment by TitikshyaChanda** [comment]
Please assign this task to me, GSSOC'24

**Comment by AnirbanChattopadhyay-2004** [comment]
Please add labels to this issue

**Comment by AnirbanChattopadhyay-2004** [comment]
Please add labels and assign level to this issue.
