### ISSUE TITLE
Icons are not visible in dropdown of profile section

### ISSUE THREAD

**Issue by Isha2923** [arghadipmanna101/Flipkart_Clone#777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Icons on the dropdown of profile section were not visible. This issue has been resolved and all icons are now visible and properly aligned, enhancing the user experience. Redundancy in the dropdown has been removed, ensuring consistent navigation across different sections such as signup, wishlist, orders, etc.

Adding Screenshots
Before
![Screenshot 2024-05-24 195419](https://github.com/arghadipmanna101/Flipkart_Clone/assets/122515895/d1d01245-fa02-405e-86e0-f661b4261dc8)

After
![Screenshot 2024-05-24 195434](https://github.com/arghadipmanna101/Flipkart_Clone/assets/122515895/6670bd9c-de68-4c1e-adf8-e1065171f360)

Thank you for considering this issue.
@arghadipmanna101 Kindly assign this issue to me so that the overall user experience is improved and bug is resolved.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by S-i-y-a-g** [comment]
please assign me this issue
