### ISSUE TITLE
BUG: Improving the Nav bar 

### ISSUE THREAD

**Issue by aditi75432** [arghadipmanna101/Flipkart_Clone#779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

improving the nav bar as it looks disoriented

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aditi75432** [comment]
@arghadipmanna101 please assign me this issue

**Comment by saiumasankar** [comment]
Assign me this issue. I have experience in cloning E-commerce website like Amazon using HTML, CSS and JavaScript.

**Comment by Kaustubhraidev** [comment]
Please assign me this issue. I have experience of more than 2 years.

**Comment by aryan-1309** [comment]
Please Assign this to me.
