### ISSUE TITLE
Fix the Footer

### ISSUE THREAD

**Issue by jency1** [arghadipmanna101/Flipkart_Clone#780]
### Describe the feature

There are several issues with the footer section of the website that need to be addressed to improve functionality and user experience. The issues include broken links, alignment problems, and missing styles.

The footer section should have fully functional links, proper alignment, and consistent styling.

I'm GSSOC'24 Contributor.

Please assign this issue to me so I can investigate and resolve these problems.

### Add ScreenShots

Current Footer : [footer-bug-flipkart](https://github.com/arghadipmanna101/Flipkart_Clone/assets/149723236/ae6fc4f7-5ce7-4480-83ee-642fe98a50f1)

Expected Footer : [Flipkart-footer](https://github.com/arghadipmanna101/Flipkart_Clone/assets/149723236/e9d324f4-174d-4c7c-8de8-9a7f23aefa1e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by S-i-y-a-g** [comment]
please assign me this issue as Gssoc contributor

**Comment by saiumasankar** [comment]
I would like to contribute to this issue. Please assign me this issue.

**Comment by somyagupta05** [comment]
I would like to contribute inorder to fix th footer. pls assign it to me.

**Comment by Dishaaa-T** [comment]
@arghadipmanna101 I would like to help to fix the footer, pls assign it to me under GSSOC'24

**Comment by Saloni0111-cpu** [comment]
pls assign me the issue

**Comment by jency1** [comment]
@arghadipmanna101 Please add the labels. (gssoc and level of difficulty).
