### ISSUE TITLE
BUG: Banner overlaping

### ISSUE THREAD

**Issue by gyanshankar1708** [arghadipmanna101/Flipkart_Clone#781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Banner is overlapping to the product section

![Screenshot 2024-05-24 230903](https://github.com/arghadipmanna101/Flipkart_Clone/assets/155980409/6b90eff3-b67a-4436-acf7-63b6976417da)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by gyanshankar1708** [comment]
@arghadipmanna101,
I had raised PR for this issue 
PR #828

**Comment by arghadipmanna101** [comment]
> @arghadipmanna101, I had raised PR for this issue PR #828
> 
> Mark this as GSSOC

done
