### ISSUE TITLE
BUG:Sidebar not opening on click of Hamburger Menu Icon

### ISSUE THREAD

**Issue by Gresey** [arghadipmanna101/Flipkart_Clone#785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

**Description**: The hamburger menu icon (three lines) is unresponsive when clicked. The sidebar does not open, preventing users from accessing the sidebar content.

**Steps to Reproduce**:

Navigate to the website.
Click on the hamburger menu icon.
Expected Result:
The sidebar should open upon clicking the hamburger menu icon.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by vermagithubcs** [comment]
@arghadipmanna101, Please assign this issue to me!
I fix the sidebar not opening when click of hamburger Menu Icon.
