### ISSUE TITLE
footer modification needed

### ISSUE THREAD

**Issue by Meetjain1** [arghadipmanna101/Flipkart_Clone#79]
Footer section is still not the exact clone of flipkart

**Comment by Meetjain1** [comment]
@arghadipmanna101 assign this issue to me , I am working under Gssoc24 .

**Comment by arghadipmanna101** [comment]
> Footer section is still not the exact clone of flipkart

sure. go ahead @Meetjain1

**Comment by Meetjain1** [comment]
@arghadipmanna101 sure sir

**Comment by R1MO9** [comment]
assign this issue to me

**Comment by Anshydv18** [comment]
assign this issue to me, i will make it better than others , please

**Comment by Aditya19110** [comment]
Assign me the issue please i am also working usnder GSSoc24

**Comment by AbhinayBhadauria99** [comment]
Assign me the issue please i am also working usnder GSSoc24

**Comment by Meetjain1** [comment]
@arghadipmanna101 just created a PR #142 regarding this issue . Thanks
