### ISSUE TITLE
BUG: Enhancement of the navbar

### ISSUE THREAD

**Issue by krittika2004** [arghadipmanna101/Flipkart_Clone#791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/119474375/bfbeec2c-eac7-4f6a-bf1a-63585ea9da9b)
this navbar looks very basic and needs enhancement. Please assign me this issue under gssoc 2024

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by DhruvJohri** [comment]
please assign this issue to me under gssoc24

**Comment by tanyaachaturvedi** [comment]
Please assign me this issue.

**Comment by krittika2004** [comment]
Yes, I will be working on this
