### ISSUE TITLE
BUG: Add OTP feature, and add Terms and Conditions page, from SignUp Page

### ISSUE THREAD

**Issue by Prakhar-Garg7** [arghadipmanna101/Flipkart_Clone#794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

**On the SignUp Page**

![website_photo](https://github.com/arghadipmanna101/Flipkart_Clone/assets/142152761/045105ef-f368-45b9-b0de-51f660060e87)

- _**Request OTP**_ feature is not working
- **_Terms and Conditions_** Page doesn't exist
- **_Privacy Policy_** Page doesn't exist

Sir, I am eager to work on this issue. 
Sir, please give me an opportunity to show my skills.

Thankyou

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Prakhar-Garg7** [comment]
Sir, please assign me this issue

**Comment by Iamkiranpanigrahi** [comment]
i would like to work on the issue.please assign the task to me.
