### ISSUE TITLE
Icon image is not getting loaded for Grocery&Food

### ISSUE THREAD

**Issue by vishal02527** [arghadipmanna101/Flipkart_Clone#798]
### Describe the feature

@arghadipmanna101 I found an issue that icon image is not getting loaded for Grocery&Food.

### Add ScreenShots

![Screenshot 2024-05-27 150303](https://github.com/arghadipmanna101/Flipkart_Clone/assets/135222259/782aba63-7778-4028-ab35-6967e49a5710)

I want to work on this issue.
So please add labels on this issue and assign this issue to me.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by DivyaCodingWorld** [comment]
![Screenshot (30)](https://github.com/arghadipmanna101/Flipkart_Clone/assets/149899712/a188e2c0-5ccd-444d-b458-fa7ffb53039c)
I found an issue that icon image is not getting loaded for Grocery &Food. please assign it to me..

**Comment by vishal02527** [comment]
@arghadipmanna101 I resolved this issue but please add label on this issue so that I can create a PR for thi.

**Comment by arghadipmanna101** [comment]
> @arghadipmanna101 I resolved this issue but please add label on this issue so that I can create a PR for this.

After send me your PR i will check the pr and then i will add levels.
