### ISSUE TITLE
missing Favicon

### ISSUE THREAD

**Issue by Meetjain1** [arghadipmanna101/Flipkart_Clone#80]
favicon of flipkart in our clone is missing

**Comment by Meetjain1** [comment]
@arghadipmanna101 sir assign this to me I will add flipkart favicon , working under gssoc24

**Comment by arghadipmanna101** [comment]
ok. go ahead @Meetjain1

**Comment by Meetjain1** [comment]
Favicon issue is now solved @arghadipmanna101 sir
