### ISSUE TITLE
Feat: google sign in and sign up feature

### ISSUE THREAD

**Issue by Subhams-GIT** [arghadipmanna101/Flipkart_Clone#804]
### Describe the feature

adding a google auth feature 

### Add ScreenShots

![Screenshot (297)](https://github.com/arghadipmanna101/Flipkart_Clone/assets/143584912/b78fec58-1fd8-44f1-bab1-6dfdc98b4264)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by DivyaCodingWorld** [comment]
Hii,
I'm interested to work on this project to solve this issues. please assigned it to me ..

**Comment by Subhams-GIT** [comment]
there are two signin and  signup files 
i am confused where to implement this.
