### ISSUE TITLE
UI/UX of Footer

### ISSUE THREAD

**Issue by GauriGA** [arghadipmanna101/Flipkart_Clone#805]
### Describe the feature

I would like to enhance the UI/UX of the footer. Also I would like to add the social media icons to it.

### Add ScreenShots

![WhatsApp Image 2024-05-29 at 10 00 39_16f7e58f](https://github.com/arghadipmanna101/Flipkart_Clone/assets/118062523/4ec8ba9e-a1c8-4012-b7e0-89c73459ae4c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by GauriGA** [comment]
@arghadipmanna101 Can you assign me this issue under the GSOC'24 label?

**Comment by niteshbca** [comment]
@GauriGA please assign to me task.

**Comment by GauriGA** [comment]
@niteshbca I am not the mentor of this project. I just created an issue to work on it. 
@arghadipmanna101 is the mentor. Can you assign it to me?

**Comment by niteshbca** [comment]
@arghadipmanna101 please assign to me task and solved the problem.

**Comment by GauriGA** [comment]
@arghadipmanna101 Can you add the gsoc'24 label also?
