### ISSUE TITLE
BUG: Twitter icon is not aligned in same line.

### ISSUE THREAD

**Issue by tarushi29** [arghadipmanna101/Flipkart_Clone#807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-05-29 104837](https://github.com/arghadipmanna101/Flipkart_Clone/assets/128239884/68dfd019-2d8a-435a-be8d-e1d66930874f)
The twitter icon is not in line.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by niteshbca** [comment]
@tarushi29 please assign to me task.
