### ISSUE TITLE
BUG: Products Name not shown

### ISSUE THREAD

**Issue by MadMax1311** [arghadipmanna101/Flipkart_Clone#808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Products or other names are not shown properly 
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/140179838/8d5839bd-3e47-4741-8214-cacdf43e1b4d)

Please assign this issue to me. @arghadipmanna101 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by DivyaCodingWorld** [comment]
Hello,
I'm interested to participate in this project. I can solve this issues . So, please assign this project to me...
### GSSOC'24 contributor.

**Comment by MadMax1311** [comment]
Please assign me label

**Comment by arghadipmanna101** [comment]
After send me your PR i will check the pr and then i will add levels.

**Comment by Komalyadav2021** [comment]
Hello,
I'm participating in this project. I can solve this issues. So, please assign this project to me... @komalyadav2021

GSSOC'24 contributor.
