### ISSUE TITLE
BUG: Improve the footer section.

### ISSUE THREAD

**Issue by DebapriyaJha** [arghadipmanna101/Flipkart_Clone#811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![pr](https://github.com/arghadipmanna101/Flipkart_Clone/assets/111692420/2a17abd8-300c-4fd8-a74c-75eda83b7048)

I think the marked parts in the footer section needs to be improved. Please assign this task to me under the gssoc and level labels.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by vaishali-gupta32** [comment]
@arghadipmanna101 please assign this task to me. I'm willing to do the changes. Also, please add the gssoc and level label to it.
