### ISSUE TITLE
Add Contact Us form

### ISSUE THREAD

**Issue by Nikuunj** [arghadipmanna101/Flipkart_Clone#815]
### Describe the feature

**Type of Issue**
- [x] Bug 🐛
- [x] New Feature 🚀
- [ ] Documentation 📚

---
**Description Issue**

I want like to contribute for contact us form.

@arghadipmanna101 (Please assign me) 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by DiyaMittal02** [comment]
please assign this task to me

**Comment by Nikuunj** [comment]
@arghadipmanna101

**Comment by Salusha** [comment]
please assign this task to me

**Comment by Nikuunj** [comment]
@arghadipmanna101  plz give me gssoc tags

**Comment by arghadipmanna101** [comment]
After send me your PR i will check the pr and then i will add levels.

**Comment by Nikuunj** [comment]
@arghadipmanna101  Could you please provide labels for the issue as well?
