### ISSUE TITLE
Implement Product Listing Page for Flipkart Clone

### ISSUE THREAD

**Issue by anjali04thecoder** [arghadipmanna101/Flipkart_Clone#82]
The goal of this task is to create a responsive Product Listing Page that displays a list of products with key information like product image, name, price, and a button to add to cart.

**Comment by arghadipmanna101** [comment]
sure. Go ahead @anjali04thecoder

**Comment by anjali04thecoder** [comment]
Sir how many days will i get to work on it?

**Comment by arghadipmanna101** [comment]
> Sir how many days will i get to work on it?

How many days you want?

**Comment by Sneha-2049** [comment]
Sir Due to my university exam are going on I need atleast one week to complete this task

**Comment by anjali04thecoder** [comment]
Sir due to my university exam going on I need atleast one week.

**Comment by arghadipmanna101** [comment]
> Sir due to my university exam going on I need atleast one week.

You take maximum 3 days.

**Comment by Yashasvi213** [comment]
Sir I would be delighted if you assign me this issue, it is within my tech-stack and  I can do it in limited time

**Comment by anjali04thecoder** [comment]
> > Sir due to my university exam going on I need atleast one week.
> 
> You take maximum 3 days.

ok sir I will try

**Comment by arghadipmanna101** [comment]
> > > Sir due to my university exam going on I need atleast one week.
> > 
> > 
> > You take maximum 3 days.
> 
> ok sir I will try

sure. all the best
