### ISSUE TITLE
Currently background is dark which is different from UI and real website to this issue need to be solve.

### ISSUE THREAD

**Issue by soniya-malviy** [arghadipmanna101/Flipkart_Clone#827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Real flipkart website have background as light but here background is dark which is different and some font size we can change to make this proper clone of real flipkart website.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Kritika-Jha** [comment]
i want to work on this issue
