### ISSUE TITLE
BUG:Chatbot Support Icon Not Moving Down with Scroll on Homepage

### ISSUE THREAD

**Issue by savvymonk05** [arghadipmanna101/Flipkart_Clone#839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The chatbot support icon on the Flipkart clone homepage is not moving down as the user scrolls down the page. It remains stuck in a fixed position, instead of staying at the bottom-right corner of the viewport. This issue affects user experience as the chatbot icon is not accessible when scrolling down the page.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ayushkrrana** [comment]
@savvymonk05 can you tell me the folder in which the code of the chatbot is written , don't be able to find out
