### ISSUE TITLE
Making product details page

### ISSUE THREAD

**Issue by KhushiTiwarii** [arghadipmanna101/Flipkart_Clone#84]
Making a product details page which will open upon clicking on the product and will display the details of the given product.Please assign me this under gssoc'24

**Comment by arghadipmanna101** [comment]
Ok. Go ahead @KhushiTiwarii

**Comment by ScriptSherpa** [comment]
hello @arghadipmanna101 please assign the label
I am interested to work on this issue. please assign it to me. I have work on similar problem of linking social media
