### ISSUE TITLE
Feat: Improving the nav-bar

### ISSUE THREAD

**Issue by sshivangi882** [arghadipmanna101/Flipkart_Clone#843]
### Describe the feature

The nav-bar is not looking good and the color of the UI is not suitable

### Add ScreenShots

![Screenshot (905)](https://github.com/arghadipmanna101/Flipkart_Clone/assets/122531720/03bacc54-162b-4153-af88-57e13871a44b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ananya2125** [comment]
I want to contribute to this issue under GSSOC'24. Kindly, assign it to me.
