### ISSUE TITLE
Feat: Create a 404 not found page for your website

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [arghadipmanna101/Flipkart_Clone#846]
### Describe the feature

 Create a 404 not found page for your website

### Add ScreenShots

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/125277258/151416a5-8c6f-4ca1-a92a-c8e206e72ffa)
its look not good we need to handle in a better manner

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by dvnshi** [comment]
Please assign this issue to me under GSSOC .

**Comment by RamakrushnaBiswal** [comment]
issue solved with  #1119
