### ISSUE TITLE
BUG: Profile section logo not shown

### ISSUE THREAD

**Issue by MadMax1311** [arghadipmanna101/Flipkart_Clone#850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Description

In Profile section, logos are not shown 

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/140179838/6ae0e879-a2f3-4faf-b6c1-3128119bf1ef)

Please, @arghadipmanna101 assign me this issue with the label.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by dvnshi** [comment]
Please assign this issue to me under GSSOC .
