### ISSUE TITLE
Feat: Title for homr page should be same as the original Flipkart website

### ISSUE THREAD

**Issue by sanyaP19** [arghadipmanna101/Flipkart_Clone#853]
### Describe the feature

The home page title for the clone is "Flipkart" which is different from the original Flipkart website i.e. "Online Shopping Site for Mobiles, Electronics, Furniture, Grocery.." and since it is a clone therefore it should be same!

### **Our Clone Website Title**
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/78594569/e9388045-6113-4b4e-958b-8f8236a05bb7)

### **Original Website Title**
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/78594569/54a06d7e-9764-469a-828a-d7ff8e5a85bd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by dvnshi** [comment]
Please assign this issue to me under GSSOC .
