### ISSUE TITLE
[bug] bug in profile section 

### ISSUE THREAD

**Issue by dineshh2003** [arghadipmanna101/Flipkart_Clone#86]
**PROBLEM**
when we switch in options in profile section the profile section heading in navbar changes accordingly when we click back button

**RECREATE**
1. go to home-page
2. click on profile section
3. click on sign-in 
4. click on back-button 
5. it will show sign in place of profile

provide me this task I'll fix that bug and also add better UI to profile section under gssoc'24.

**Comment by arghadipmanna101** [comment]
ok. Go ahead @dineshh2003

**Comment by Sudiksha18** [comment]
Hello @arghadipmanna101, can you please assign this issue to me under gssoc'24?

**Comment by ScriptSherpa** [comment]
Hello @arghadipmanna101, can you please assign this issue to me under gssoc'24?
