### ISSUE TITLE
Feat: Adding a contact us page

### ISSUE THREAD

**Issue by ayush-848** [arghadipmanna101/Flipkart_Clone#872]
### Describe the feature

This page will have a form that needs name, email and message.
This will act upon clicking the contact us in the footer

### Add ScreenShots

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/126975547/f1e524e4-fda7-4e32-8c83-6b5ea36d1acd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

@arghadipmanna101 Please assign this issue to me

**Comment by SheetalDawar** [comment]
I would like to work on this project, please assign it to me
