### ISSUE TITLE
BUG: Responsive Design Overflowing 

### ISSUE THREAD

**Issue by aarushroyy** [arghadipmanna101/Flipkart_Clone#873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When switched to Mobile View, the website is overflowing horizontally producing unwanted white space. Making also difficult to navigate in Mobile View.

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/69352438/be2ae777-c918-4930-996d-08eddead964e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by deepxnshiiii** [comment]
@arghadipmanna101 hey there,, i can help make it responsive, please assign me this with label gssoc
