### ISSUE TITLE
BUG: Navbar items not aligned

### ISSUE THREAD

**Issue by aarushroyy** [arghadipmanna101/Flipkart_Clone#874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The items in the navbar after the search are not at all aligned with a few taking double-line space, while the triple dots being necessarily small. 

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/69352438/1ee70ce4-e035-45d7-b922-5d2aef08a34d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Johnchinnu** [comment]
I would like to work on this project. Please assign this to me.

**Comment by pulkit49** [comment]
I can help you with that. Please assign me this issue under GSSOC 2024.
