### ISSUE TITLE
BUG: The Dark Mode Switch button is Misaligned

### ISSUE THREAD

**Issue by kashvi9** [arghadipmanna101/Flipkart_Clone#875]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Switch to Dark Mode Button is misaligned.
It is coming out of the Navigation bar or Header Section

Here's a screenshot of how it looks:
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/169376061/4b0f3a3d-2dc6-4729-a964-072a2e9af82e)

Hello PA @arghadipmanna101 ,
I request you to assign me this issue under GSSOC'24.
Thank You!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Poonam-Kashyap12** [comment]
i want to work on this issue

**Comment by kashvi9** [comment]
Sorry but I think due to enhancements, the dark mode button has been removed.
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/169376061/1fd4e68c-b5db-419c-95b9-600eba016106)
