### ISSUE TITLE
Add more section to the Landing-page.

### ISSUE THREAD

**Issue by dineshh2003** [arghadipmanna101/Flipkart_Clone#88]
**Feature**
want to add more section to the home-page and create a link to the product list when click on the slider in homepage plz assign me this task under gssoc'24

**Comment by Justaditi** [comment]
Please assign me this issue

**Comment by Saloni-0465** [comment]
I'm interested in making some enhancements to the landing page to improve user engagement and provide more informative sections beyond the initial images. 
Kindly assign me the issue .

**Comment by Ashutosh-0506** [comment]
Hey there! I'm Ashutosh Kumar, a full-stack MERN web developer. With experience in numerous successful MERN stack  projects, I excel in  HTML, CSS,JavaScript,C, C++,jQuery, Node.js, React.js, Bootstrap, Tailwind, Express, MongoDB, API,GraphQL,WebRTC. 
You can find me on LinkedIn : https://www.linkedin.com/in/ashutosh-kumar-60b262251/ 
 GitHub : https://github.com/Ashutosh-0506. 
Looking forward to contributing to GSSOC 2024!

**Comment by arghadipmanna101** [comment]
> Hey there! I'm Ashutosh Kumar, a full-stack MERN web developer. With experience in numerous successful MERN stack projects, I excel in HTML, CSS,JavaScript,C, C++,jQuery, Node.js, React.js, Bootstrap, Tailwind, Express, MongoDB, API,GraphQL,WebRTC. You can find me on LinkedIn : https://www.linkedin.com/in/ashutosh-kumar-60b262251/ GitHub : https://github.com/Ashutosh-0506. Looking forward to contributing to GSSOC 2024!

credit a issue where you want to contribute. ok

**Comment by Aditya19110** [comment]
I can contribute here please assign me the issue

**Comment by ShivamPant1321** [comment]
Would like to contribute in the project by adding more content to the landing page.
Kindly assign this issue to me.

**Comment by Ashutosh-0506** [comment]
> > Hey there! I'm Ashutosh Kumar, a full-stack MERN web developer. With experience in numerous successful MERN stack projects, I excel in HTML, CSS,JavaScript,C, C++,jQuery, Node.js, React.js, Bootstrap, Tailwind, Express, MongoDB, API,GraphQL,WebRTC. You can find me on LinkedIn : https://www.linkedin.com/in/ashutosh-kumar-60b262251/ GitHub : https://github.com/Ashutosh-0506. Looking forward to contributing to GSSOC 2024!
> 
> credit a issue where you want to contribute. ok

Sir I can add the "Top Brand Stories" Section in the codebase along with some other minor adjustments
