### ISSUE TITLE
BUG: Missing favicon

### ISSUE THREAD

**Issue by Athul28** [arghadipmanna101/Flipkart_Clone#880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is no favicon for the website
![Screenshot 2024-05-31 125407](https://github.com/arghadipmanna101/Flipkart_Clone/assets/79209367/45ae2394-5c03-4569-a83f-88772285e119)

I can add the flipkart favicon

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Salusha** [comment]
please assign me this issue

**Comment by Gokilp** [comment]
i assign to me

**Comment by Gokilp** [comment]
please Review my pr @arghadipmanna101

**Comment by Athul28** [comment]
@Gokilp you can't assign issues to yourself, @arghadipmanna101 please look into this, this issue was raised by me

**Comment by Gokilp** [comment]
no can assign the issue please merge my pr

**Comment by Gokilp** [comment]
Please assign to me 

under Gssoc label
