### ISSUE TITLE
BUG: Unnecessary spacing in the footer

### ISSUE THREAD

**Issue by Athul28** [arghadipmanna101/Flipkart_Clone#881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-05-31 125824](https://github.com/arghadipmanna101/Flipkart_Clone/assets/79209367/9b553f1a-bfa8-4b43-809f-7df5e4006492)

There is an unnecessary spacing around the footer, I can remove that and also make changes in the footer to exactly look like the actual flipkart website

![Screenshot 2024-05-31 130000](https://github.com/arghadipmanna101/Flipkart_Clone/assets/79209367/7b9c0a81-939c-4598-9f62-d07befbf6295)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by 22-0304** [comment]
Can you assign me this issue @arghadipmanna101

**Comment by vaishali-gupta32** [comment]
@arghadipmanna101 please assign the task to me

**Comment by Athul28** [comment]
@arghadipmanna101 please assign me this issue
