### ISSUE TITLE
Improvement to the UI of the login and order page

### ISSUE THREAD

**Issue by MadhunishaBala** [arghadipmanna101/Flipkart_Clone#89]
Can I please improve the UI of the login and order page to make it more visually appealing under the GSSOC'24?

**Comment by Pooja-013** [comment]
please assign this to me under GSSOC'24

**Comment by aashkaaaaaa** [comment]
i want working of this issue, please assign me

**Comment by bhaveshnegi** [comment]
I have made a Zomato clone, so I can improve the Ul of login and order page can u assign it to me.

**Comment by Aditya19110** [comment]
I can help you in this please assign me as i am doing it under GSSoc24
