### ISSUE TITLE
Brand Directory 

### ISSUE THREAD

**Issue by Kkt04** [arghadipmanna101/Flipkart_Clone#9]
Can add Brand Directory above the footer and below the main content, where the most searched products on flipkart are listed.

**Comment by arghadipmanna101** [comment]
> Can add Brand Directory above the footer and below the main content, where the most searched products on flipkart are listed.

sure. you can. you have been assigned. Go ahead

**Comment by shamayitadatta** [comment]
contribute on this ..please assign me
