### ISSUE TITLE
BUG: Glitch in the nav bar when hovering on the right part

### ISSUE THREAD

**Issue by Supriya-saha** [arghadipmanna101/Flipkart_Clone#904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

While hovering on the mid of buttons of "profile" and "Become a seller", it forming a glitching triggering hover actions of both. As both cannot accomodate, it creating a switching effect.
Solution:-
1. Adding some padding in between them to overcome the bug.
2. Adjusting the onhover box size so that they dont overlap.

Check out the image for reference.
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/122046950/a6f30090-d956-4ab5-8638-7050bfd510d0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [x] I want to work on this issue

**Comment by Supriya-saha** [comment]
please assign the issue to me.

**Comment by pulkit49** [comment]
I can help you with that. Please assign me this issue under GSSOC 2024.

**Comment by Supriya-saha** [comment]
Have generated a pull request #1142 . Please check it out.
