### ISSUE TITLE
Feat:Gift card link not working

### ISSUE THREAD

**Issue by kashnx** [arghadipmanna101/Flipkart_Clone#905]
### Describe the feature

Add a gift card page.
please assign this issue to me under gssoc'24

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Khushiirani25** [comment]
assign this issue to me i want to work on this under  GSSOC'24 contributor

**Comment by Gokilp** [comment]
please issue assign the issue to me

**Comment by Gokilp** [comment]
please Review my pr

**Comment by pulkit49** [comment]
I can help you with that. Please assign me this issue under GSSOC 2024.

**Comment by Gokilp** [comment]
Please assign to me
