### ISSUE TITLE
Making responsive the Signup and Signin page 

### ISSUE THREAD

**Issue by Pujan-sarkar** [arghadipmanna101/Flipkart_Clone#91]
The  Sign up and Sign in page will be more attractive if  We made it responsive.

**Comment by Pujan-sarkar** [comment]
@arghadipmanna101  I want to contribute and make the sign up and sign in page responsive under GSSOC'24. will you please assign it to me .

**Comment by Khushinkm15** [comment]
If we can add media-query within the signup and signin page , the clone will be a more better version.
So will you assign task to me !!

**Comment by arghadipmanna101** [comment]
> If we can add media-query within the signup and signin page , the clone will be a more better version. So will you assign this task to me !!

sure. you can do it. go ahead @Khushinkm15

**Comment by Pujan-sarkar** [comment]
@arghadipmanna101  i have send a pr regarding this issue can you check ?

**Comment by Pujan-sarkar** [comment]
@arghadipmanna101 i have send a pr regarding solving this issue can you check please

**Comment by Pujan-sarkar** [comment]
@arghadipmanna101 this issue have been solved

**Comment by Pujan-sarkar** [comment]
@arghadipmanna101  this issue is solved by #477  , you can close this issue.
