### ISSUE TITLE
Feat: alignment of the social media links and add Instagram 

### ISSUE THREAD

**Issue by jayanththalla** [arghadipmanna101/Flipkart_Clone#913]
### Describe the feature

enhancement of the footer by adding social media icons and alignment

please assign me @pa

### Add ScreenShots

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/121346142/17c4fb9f-d0b1-4722-94c7-d2e964ef826d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Gokilp** [comment]
can you please assign me

**Comment by Gokilp** [comment]
i wil make pr Please review my pr @arghadipmanna101
