### ISSUE TITLE
add a preloader

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [arghadipmanna101/Flipkart_Clone#92]

**Comment by DharshiBalasubramaniyam** [comment]
Hello @arghadipmanna101, can you please assign this issue to me under gssoc'24?

**Comment by Ashutosh-0506** [comment]
Hey there! I'm Ashutosh Kumar, a full-stack MERN web developer. With experience in numerous successful MERN stack  projects, I excel in  HTML, CSS,JavaScript,C, C++,jQuery, Node.js, React.js, Bootstrap, Tailwind, Express, MongoDB, API,GraphQL,WebRTC. 
You can find me on LinkedIn : https://www.linkedin.com/in/ashutosh-kumar-60b262251/ 
 GitHub : https://github.com/Ashutosh-0506. 
Looking forward to contributing to GSSOC 2024!

**Comment by Deathnote45** [comment]
Hi, @arghadipmanna101 can you please assign me to this issue, 
my profile: https://www.linkedin.com/in/shuvangi-de-369071236/
