### ISSUE TITLE
Update index.html

### ISSUE THREAD

**Issue by mahek0620** [arghadipmanna101/Flipkart_Clone#926]
### What's wrong with the existing documentation

It contains duplicated code

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ananyag309** [comment]
Hi, I hope this message finds you well.

I am writing to express my interest in contributing to the issue. I am enthusiastic about participating in GSSoC'24 and believe that working on this issue will allow me to make a meaningful contribution to the project.

Could you please assign this issue to me under GSSoC'24? also please add gssoc label.

Thank you for considering my request.

**Comment by pulkit49** [comment]
I can help you with that. Please assign me this issue under GSSOC 2024.
