### ISSUE TITLE
Improve home page by adding catagories section

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [arghadipmanna101/Flipkart_Clone#93]
I like to add different categories section (electronics, toys, gifts, travels home and kitchen etc) in the home page as below. 
![Screenshot 2024-05-10 150917](https://github.com/arghadipmanna101/Flipkart_Clone/assets/139672976/abeae9e9-78e2-4380-a298-b18ba9c8abde)

@arghadipmanna101 Can you please assign this issue to me?

**Comment by arghadipmanna101** [comment]
ok. go ahead @DharshiBalasubramaniyam .

**Comment by Pujan-sarkar** [comment]
I want to contribute too in this section under GSSOC'24 can you assign it to me please

**Comment by Harshita2027** [comment]
I want to contribute to this section, please assign it to me

**Comment by AbhinayBhadauria99** [comment]
Assign me the issue please i am also working usnder GSSoc24

**Comment by anushreemehta6** [comment]
@arghadipmanna101  please assign me this issue , i can work on it under GSSOC'24
