### ISSUE TITLE
BUG:Improving Navbar UI

### ISSUE THREAD

**Issue by sharmi4590** [arghadipmanna101/Flipkart_Clone#936]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot (511)](https://github.com/arghadipmanna101/Flipkart_Clone/assets/102676949/aa8c74d2-60aa-409b-bb5e-18ca6e2eb65b)

I would like to work on this.
This is my previous work.

https://github.com/arghadipmanna101/Flipkart_Clone/assets/102676949/9529fb49-afe3-4c26-9763-3ee5a61675b1

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PrakarshSingh5** [comment]
Hey @sharmi4590 please assign this task to me
