### ISSUE TITLE
BUG: Search bar 

### ISSUE THREAD

**Issue by SakiraAli1115** [arghadipmanna101/Flipkart_Clone#938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello, PA
@arghadipmanna101 

Search bar is not redirecting to the particular thing . Suppose click electronics but this page not work .

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/169131830/a0c1aa29-332a-4e65-b5f1-16dad7ea4a9f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SakiraAli1115** [comment]
Hello , PA
@arghadipmanna101 
Can you please assign me this issue!

**Comment by pulkit49** [comment]
I can help you with that. Please assign me this issue under GSSOC 2024.
