### ISSUE TITLE
Adding another header which containing categories and subcategroies

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [arghadipmanna101/Flipkart_Clone#94]
A header which displaying categories and when hover each of the categories the sub categories will be shown as below. 

![Screenshot 2024-05-10 151847](https://github.com/arghadipmanna101/Flipkart_Clone/assets/139672976/f62a493e-19fe-4a46-a016-59724ff0b055)

Implementing this feature will add more user experience. Cam you add this issue to me under gssoc'24?

**Comment by arghadipmanna101** [comment]
> A header which displaying categories and when hover each of the categories the sub categories will be shown as below.
> 
> ![Screenshot 2024-05-10 151847](https://private-user-images.githubusercontent.com/139672976/329539554-f62a493e-19fe-4a46-a016-59724ff0b055.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMzc4ODQsIm5iZiI6MTcxNTMzNzU4NCwicGF0aCI6Ii8xMzk2NzI5NzYvMzI5NTM5NTU0LWY2MmE0OTNlLTE5ZmUtNGE0Ni1hMDE2LTU5NzI0ZmYwYjA1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMFQxMDM5NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kY2I4MTdkY2UwMWVjMzI2M2JhYjkxNWE0ODU4ZDlmMjYwODVmODEzNGZjOTgwMjAxYTQ4YjkwZmJlYjkwNGU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.15pkhY5Y45gxQ5zAjMhqtk8PONEToO_is1ePtRmVb0c)
> 
> Implementing this feature will add more user experience. Cam you add this issue to me under gssoc'24?

Yea sure. Go ahead @DharshiBalasubramaniyam

**Comment by paridhi1509** [comment]
Please assign me this issue as i would like to work on it

**Comment by DharshiBalasubramaniyam** [comment]
@paridhi1509 I am currently working on this issue

**Comment by Harshita2027** [comment]
i want to work on this project please assign it to me
