### ISSUE TITLE
fixing tittle

### ISSUE THREAD

**Issue by shuhaki** [arghadipmanna101/Flipkart_Clone#96]
add logo icon in title ... please assign me

**Comment by arghadipmanna101** [comment]
Go ahead @shuhaki

**Comment by Akshar-Saxena** [comment]
I want to solve this issue. Please assign me the task

**Comment by AditiJeena** [comment]
Please assign this issue to me.

**Comment by sys-atasi** [comment]
please assign me this task

**Comment by Peehu1308** [comment]
please assign this to me

**Comment by Manojit-Das-10** [comment]
I want to solve this issue , Please assign me the task.

**Comment by SuhainaFathimaM** [comment]
Hi @arghadipmanna101,
I am good at frontend development .
please assign me this issue..
 I'm confident that I can implement that..

Looking forward to your response.

Best regards

**Comment by SohaFarhana** [comment]
Hello
I am a GSSoC'24 contributor and looking forward to work on this

**Comment by Divya-1612-reddy** [comment]
Please assign this issue to me.

**Comment by Sudiksha18** [comment]
Hello @arghadipmanna101, can you please assign this issue to me under gssoc'24?

**Comment by Sehar-Tahir** [comment]
add logo icon in title  kindly assign it to me

**Comment by gargimukherjee25** [comment]
Hello I am Gargi from IIT Kharagpur! I work with html,css,js,react.js and so on and am eager to learn more. I'd appreciate being assigned this task for GSSoC 24.

**Comment by richasriva** [comment]
Hi, I have good experience in front-end. Please assign this task to me.
