### ISSUE TITLE
Footer titles not being flex

### ISSUE THREAD

**Issue by gungunjain15** [arghadipmanna101/Flipkart_Clone#961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

All the titles in footer section are aligned in a column , they need to be in diff columns
For reference :- 
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/125124845/9973f16b-9714-4e4d-a6ad-d6ee616cdabe)
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/125124845/4787edbc-22ee-45c2-98ae-5acd445050ea)
 
@arghadipmanna101 Please assign this issue to me

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by pulkit49** [comment]
I can help you with that. Please assign me this issue under GSSOC 2024.
