### ISSUE TITLE
Adding the GSAP (JS Library) Animations to the website

### ISSUE THREAD

**Issue by suraj-9849** [arghadipmanna101/Flipkart_Clone#97]
I would like to add the animations to the website which can make this website look cool and better user interface.
So can you please assign this issue to me. @arghadipmanna101 under @GSSOC24

**Comment by arghadipmanna101** [comment]
sure. go ahead @suraj-9849

**Comment by suraj-9849** [comment]
https://github.com/arghadipmanna101/Flipkart_Clone/assets/146669517/34c597f6-42a3-4f47-ac4c-23bc7b501ef5
is this ok or should I add more animations @arghadipmanna101 sir

**Comment by arghadipmanna101** [comment]
> https://github.com/arghadipmanna101/Flipkart_Clone/assets/146669517/34c597f6-42a3-4f47-ac4c-23bc7b501ef5 is this ok or should I add more animations @arghadipmanna101 sir

good work. but there have a conflict in your PR. check it once

**Comment by suraj-9849** [comment]
Yeah sir I made it rectified and pushed again

**Comment by suraj-9849** [comment]
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/146669517/9d2dde02-24d0-4658-9a3e-a743ca65eae6)
