### ISSUE TITLE
Feat: footer is not appropriate 

### ISSUE THREAD

**Issue by siddhant-2002** [arghadipmanna101/Flipkart_Clone#976]
### Describe the feature

Become a seller
[ Gift Cards]
[ Help Center]
©2024 Flipkart.com

this things on the footer don't look well I can style it good and make it look nice

I would like to work on the feature if you assign it to me 

### Add ScreenShots

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/112260375/2db8aff8-9453-41b9-9cd2-7491f83b87b6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by pulkit49** [comment]
I can help you with that. Please assign me this issue under GSSOC 2024.
