### ISSUE TITLE
BUG:UI of the Login page

### ISSUE THREAD

**Issue by ShrutiGuptaaa** [arghadipmanna101/Flipkart_Clone#981]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I think the UI of the Login page could be made more attractive and eye-appealing

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hritika2409** [comment]
Can you please assign me this issue i can work on this..!
