### ISSUE TITLE
Footer Font Style

### ISSUE THREAD

**Issue by 1754riya** [arghadipmanna101/Flipkart_Clone#988]
**Is there an existing issue for this?**_
 I have searched the existing issues
**_What happened?_**
I think the font style of the text in the Footer and other pages can be changed to give it a more professional look

**Record**

1.  I agree to follow this project's Code of Conduct
2.  I'm a GSSOC'24 contributor
3.  I want to work on this issue.

@arghadipmanna101, Please Assign me this Task.

**Comment by ishikat** [comment]
![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/72931967/d204b34b-177b-4161-a9b9-cf87d808656a)

Hii @arghadipmanna101 
I would like to enhance the footer of this flipkart project.
can you assign it to me under GSSOC24.

**Comment by hritika2409** [comment]
Can you please assign me this issue i can work on this..!
