### ISSUE TITLE
Improve the look of top navigation bar in accordance to overall design of website

### ISSUE THREAD

**Issue by Anshravicode89** [arghadipmanna101/Flipkart_Clone#993]
### Describe the feature

As shown in screenshot, the navbar needs abit redesign according to overall look and feel of the site. Kindly assign me this task under GSSOC 24 as I have a good experience in UI designs and frontend.

### Add ScreenShots

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/166092579/eb9cbc72-77e1-43c0-ab30-22097908256c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hritika2409** [comment]
Can you please assign me this issue i can work on this..!
