### ISSUE TITLE
Feat: Change whole navbar and add new same like flipkart

### ISSUE THREAD

**Issue by MadMax1311** [arghadipmanna101/Flipkart_Clone#995]
### Describe the feature

Change and navbar and add new that is same like flipkart.

Please assign me this issue with label

### Add ScreenShots

![image](https://github.com/arghadipmanna101/Flipkart_Clone/assets/140179838/e97b6bcc-d23b-4e9d-b800-9c35f83325b8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ManyaJain246** [comment]
I would like to work on this issue. Please assign this task to me.

**Comment by UnnatiSabu** [comment]
@arghadipmanna101 I would like to work on this issue. Please assign this to me. I will add logo designs and modify the navigation bar, similar to the Flipkart website.

Please assign a label to this issue.
